// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: kratos/skill_evolution_suggestion/v1/skill_evolution_suggestion.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillEvolutionSuggestionService_ListSkillEvolutionSuggestions_FullMethodName   = "/kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService/ListSkillEvolutionSuggestions"
	SkillEvolutionSuggestionService_GetSkillEvolutionSuggestion_FullMethodName     = "/kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService/GetSkillEvolutionSuggestion"
	SkillEvolutionSuggestionService_ApproveSkillEvolutionSuggestion_FullMethodName = "/kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService/ApproveSkillEvolutionSuggestion"
	SkillEvolutionSuggestionService_RejectSkillEvolutionSuggestion_FullMethodName  = "/kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService/RejectSkillEvolutionSuggestion"
	SkillEvolutionSuggestionService_TriggerCuratorFlow_FullMethodName              = "/kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService/TriggerCuratorFlow"
)

// SkillEvolutionSuggestionServiceClient is the client API for SkillEvolutionSuggestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillEvolutionSuggestionServiceClient interface {
	ListSkillEvolutionSuggestions(ctx context.Context, in *ListSkillEvolutionSuggestionsRequest, opts ...grpc.CallOption) (*ListSkillEvolutionSuggestionsResponse, error)
	GetSkillEvolutionSuggestion(ctx context.Context, in *GetSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*GetSkillEvolutionSuggestionResponse, error)
	ApproveSkillEvolutionSuggestion(ctx context.Context, in *ApproveSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*ApproveSkillEvolutionSuggestionResponse, error)
	RejectSkillEvolutionSuggestion(ctx context.Context, in *RejectSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*RejectSkillEvolutionSuggestionResponse, error)
	// TriggerCuratorFlow runs the full Curator Agent semi-automatic evolution
	// pipeline for a skill: trigger detection → draft generation → sandbox verification.
	TriggerCuratorFlow(ctx context.Context, in *TriggerCuratorFlowRequest, opts ...grpc.CallOption) (*TriggerCuratorFlowResponse, error)
}

type skillEvolutionSuggestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillEvolutionSuggestionServiceClient(cc grpc.ClientConnInterface) SkillEvolutionSuggestionServiceClient {
	return &skillEvolutionSuggestionServiceClient{cc}
}

func (c *skillEvolutionSuggestionServiceClient) ListSkillEvolutionSuggestions(ctx context.Context, in *ListSkillEvolutionSuggestionsRequest, opts ...grpc.CallOption) (*ListSkillEvolutionSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillEvolutionSuggestionsResponse)
	err := c.cc.Invoke(ctx, SkillEvolutionSuggestionService_ListSkillEvolutionSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillEvolutionSuggestionServiceClient) GetSkillEvolutionSuggestion(ctx context.Context, in *GetSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*GetSkillEvolutionSuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillEvolutionSuggestionResponse)
	err := c.cc.Invoke(ctx, SkillEvolutionSuggestionService_GetSkillEvolutionSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillEvolutionSuggestionServiceClient) ApproveSkillEvolutionSuggestion(ctx context.Context, in *ApproveSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*ApproveSkillEvolutionSuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveSkillEvolutionSuggestionResponse)
	err := c.cc.Invoke(ctx, SkillEvolutionSuggestionService_ApproveSkillEvolutionSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillEvolutionSuggestionServiceClient) RejectSkillEvolutionSuggestion(ctx context.Context, in *RejectSkillEvolutionSuggestionRequest, opts ...grpc.CallOption) (*RejectSkillEvolutionSuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectSkillEvolutionSuggestionResponse)
	err := c.cc.Invoke(ctx, SkillEvolutionSuggestionService_RejectSkillEvolutionSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillEvolutionSuggestionServiceClient) TriggerCuratorFlow(ctx context.Context, in *TriggerCuratorFlowRequest, opts ...grpc.CallOption) (*TriggerCuratorFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerCuratorFlowResponse)
	err := c.cc.Invoke(ctx, SkillEvolutionSuggestionService_TriggerCuratorFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillEvolutionSuggestionServiceServer is the server API for SkillEvolutionSuggestionService service.
// All implementations must embed UnimplementedSkillEvolutionSuggestionServiceServer
// for forward compatibility.
type SkillEvolutionSuggestionServiceServer interface {
	ListSkillEvolutionSuggestions(context.Context, *ListSkillEvolutionSuggestionsRequest) (*ListSkillEvolutionSuggestionsResponse, error)
	GetSkillEvolutionSuggestion(context.Context, *GetSkillEvolutionSuggestionRequest) (*GetSkillEvolutionSuggestionResponse, error)
	ApproveSkillEvolutionSuggestion(context.Context, *ApproveSkillEvolutionSuggestionRequest) (*ApproveSkillEvolutionSuggestionResponse, error)
	RejectSkillEvolutionSuggestion(context.Context, *RejectSkillEvolutionSuggestionRequest) (*RejectSkillEvolutionSuggestionResponse, error)
	// TriggerCuratorFlow runs the full Curator Agent semi-automatic evolution
	// pipeline for a skill: trigger detection → draft generation → sandbox verification.
	TriggerCuratorFlow(context.Context, *TriggerCuratorFlowRequest) (*TriggerCuratorFlowResponse, error)
	mustEmbedUnimplementedSkillEvolutionSuggestionServiceServer()
}

// UnimplementedSkillEvolutionSuggestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillEvolutionSuggestionServiceServer struct{}

func (UnimplementedSkillEvolutionSuggestionServiceServer) ListSkillEvolutionSuggestions(context.Context, *ListSkillEvolutionSuggestionsRequest) (*ListSkillEvolutionSuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkillEvolutionSuggestions not implemented")
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) GetSkillEvolutionSuggestion(context.Context, *GetSkillEvolutionSuggestionRequest) (*GetSkillEvolutionSuggestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillEvolutionSuggestion not implemented")
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) ApproveSkillEvolutionSuggestion(context.Context, *ApproveSkillEvolutionSuggestionRequest) (*ApproveSkillEvolutionSuggestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveSkillEvolutionSuggestion not implemented")
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) RejectSkillEvolutionSuggestion(context.Context, *RejectSkillEvolutionSuggestionRequest) (*RejectSkillEvolutionSuggestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectSkillEvolutionSuggestion not implemented")
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) TriggerCuratorFlow(context.Context, *TriggerCuratorFlowRequest) (*TriggerCuratorFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerCuratorFlow not implemented")
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) mustEmbedUnimplementedSkillEvolutionSuggestionServiceServer() {
}
func (UnimplementedSkillEvolutionSuggestionServiceServer) testEmbeddedByValue() {}

// UnsafeSkillEvolutionSuggestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillEvolutionSuggestionServiceServer will
// result in compilation errors.
type UnsafeSkillEvolutionSuggestionServiceServer interface {
	mustEmbedUnimplementedSkillEvolutionSuggestionServiceServer()
}

func RegisterSkillEvolutionSuggestionServiceServer(s grpc.ServiceRegistrar, srv SkillEvolutionSuggestionServiceServer) {
	// If the following call panics, it indicates UnimplementedSkillEvolutionSuggestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillEvolutionSuggestionService_ServiceDesc, srv)
}

func _SkillEvolutionSuggestionService_ListSkillEvolutionSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillEvolutionSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvolutionSuggestionServiceServer).ListSkillEvolutionSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvolutionSuggestionService_ListSkillEvolutionSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvolutionSuggestionServiceServer).ListSkillEvolutionSuggestions(ctx, req.(*ListSkillEvolutionSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillEvolutionSuggestionService_GetSkillEvolutionSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillEvolutionSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvolutionSuggestionServiceServer).GetSkillEvolutionSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvolutionSuggestionService_GetSkillEvolutionSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvolutionSuggestionServiceServer).GetSkillEvolutionSuggestion(ctx, req.(*GetSkillEvolutionSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillEvolutionSuggestionService_ApproveSkillEvolutionSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveSkillEvolutionSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvolutionSuggestionServiceServer).ApproveSkillEvolutionSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvolutionSuggestionService_ApproveSkillEvolutionSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvolutionSuggestionServiceServer).ApproveSkillEvolutionSuggestion(ctx, req.(*ApproveSkillEvolutionSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillEvolutionSuggestionService_RejectSkillEvolutionSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectSkillEvolutionSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvolutionSuggestionServiceServer).RejectSkillEvolutionSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvolutionSuggestionService_RejectSkillEvolutionSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvolutionSuggestionServiceServer).RejectSkillEvolutionSuggestion(ctx, req.(*RejectSkillEvolutionSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillEvolutionSuggestionService_TriggerCuratorFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerCuratorFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvolutionSuggestionServiceServer).TriggerCuratorFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvolutionSuggestionService_TriggerCuratorFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvolutionSuggestionServiceServer).TriggerCuratorFlow(ctx, req.(*TriggerCuratorFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillEvolutionSuggestionService_ServiceDesc is the grpc.ServiceDesc for SkillEvolutionSuggestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillEvolutionSuggestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kratos.skill_evolution_suggestion.v1.SkillEvolutionSuggestionService",
	HandlerType: (*SkillEvolutionSuggestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSkillEvolutionSuggestions",
			Handler:    _SkillEvolutionSuggestionService_ListSkillEvolutionSuggestions_Handler,
		},
		{
			MethodName: "GetSkillEvolutionSuggestion",
			Handler:    _SkillEvolutionSuggestionService_GetSkillEvolutionSuggestion_Handler,
		},
		{
			MethodName: "ApproveSkillEvolutionSuggestion",
			Handler:    _SkillEvolutionSuggestionService_ApproveSkillEvolutionSuggestion_Handler,
		},
		{
			MethodName: "RejectSkillEvolutionSuggestion",
			Handler:    _SkillEvolutionSuggestionService_RejectSkillEvolutionSuggestion_Handler,
		},
		{
			MethodName: "TriggerCuratorFlow",
			Handler:    _SkillEvolutionSuggestionService_TriggerCuratorFlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kratos/skill_evolution_suggestion/v1/skill_evolution_suggestion.proto",
}
