// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: kratos/cron/v1/cron.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CronTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,2,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	AgentId       string                 `protobuf:"bytes,8,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,9,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,10,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronTask) Reset() {
	*x = CronTask{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronTask) ProtoMessage() {}

func (x *CronTask) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronTask.ProtoReflect.Descriptor instead.
func (*CronTask) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronTask) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *CronTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CronTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronTask) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CronTask) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CronTask) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CronTask) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *CronTask) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CronTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CronTask) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CronTask) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ListCronTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CronTask            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronTasksResponse) Reset() {
	*x = ListCronTasksResponse{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronTasksResponse) ProtoMessage() {}

func (x *ListCronTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronTasksResponse.ProtoReflect.Descriptor instead.
func (*ListCronTasksResponse) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *ListCronTasksResponse) GetItems() []*CronTask {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskKey       string                 `protobuf:"bytes,1,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	AgentId       string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,8,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronTaskRequest) Reset() {
	*x = CreateCronTaskRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronTaskRequest) ProtoMessage() {}

func (x *CreateCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCronTaskRequest) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *CreateCronTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCronTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCronTaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateCronTaskRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateCronTaskRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateCronTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateCronTaskRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *CreateCronTaskRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type GetCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronTaskRequest) Reset() {
	*x = GetCronTaskRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronTaskRequest) ProtoMessage() {}

func (x *GetCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronTaskRequest.ProtoReflect.Descriptor instead.
func (*GetCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{3}
}

func (x *GetCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task          *CronTask              `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronTaskRequest) Reset() {
	*x = UpdateCronTaskRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronTaskRequest) ProtoMessage() {}

func (x *UpdateCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCronTaskRequest) GetTask() *CronTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronTaskRequest) Reset() {
	*x = DeleteCronTaskRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronTaskRequest) ProtoMessage() {}

func (x *DeleteCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CronTaskRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Trigger       string                 `protobuf:"bytes,7,opt,name=trigger,proto3" json:"trigger,omitempty"`
	RunId         string                 `protobuf:"bytes,8,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	OutputJson    string                 `protobuf:"bytes,9,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronTaskRun) Reset() {
	*x = CronTaskRun{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronTaskRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronTaskRun) ProtoMessage() {}

func (x *CronTaskRun) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronTaskRun.ProtoReflect.Descriptor instead.
func (*CronTaskRun) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{6}
}

func (x *CronTaskRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronTaskRun) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CronTaskRun) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CronTaskRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronTaskRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CronTaskRun) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *CronTaskRun) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *CronTaskRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CronTaskRun) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *CronTaskRun) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CronTaskRun) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListCronTaskRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronTaskId    string                 `protobuf:"bytes,1,opt,name=cron_task_id,json=cronTaskId,proto3" json:"cron_task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronTaskRunsRequest) Reset() {
	*x = ListCronTaskRunsRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronTaskRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronTaskRunsRequest) ProtoMessage() {}

func (x *ListCronTaskRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronTaskRunsRequest.ProtoReflect.Descriptor instead.
func (*ListCronTaskRunsRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{7}
}

func (x *ListCronTaskRunsRequest) GetCronTaskId() string {
	if x != nil {
		return x.CronTaskId
	}
	return ""
}

func (x *ListCronTaskRunsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCronTaskRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCronTaskRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CronTaskRun         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronTaskRunsResponse) Reset() {
	*x = ListCronTaskRunsResponse{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronTaskRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronTaskRunsResponse) ProtoMessage() {}

func (x *ListCronTaskRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronTaskRunsResponse.ProtoReflect.Descriptor instead.
func (*ListCronTaskRunsResponse) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{8}
}

func (x *ListCronTaskRunsResponse) GetItems() []*CronTaskRun {
	if x != nil {
		return x.Items
	}
	return nil
}

type TriggerCronTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCronTaskRequest) Reset() {
	*x = TriggerCronTaskRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCronTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCronTaskRequest) ProtoMessage() {}

func (x *TriggerCronTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCronTaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerCronTaskRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerCronTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResetCronTaskFailuresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCronTaskFailuresRequest) Reset() {
	*x = ResetCronTaskFailuresRequest{}
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCronTaskFailuresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCronTaskFailuresRequest) ProtoMessage() {}

func (x *ResetCronTaskFailuresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_cron_v1_cron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCronTaskFailuresRequest.ProtoReflect.Descriptor instead.
func (*ResetCronTaskFailuresRequest) Descriptor() ([]byte, []int) {
	return file_kratos_cron_v1_cron_proto_rawDescGZIP(), []int{10}
}

func (x *ResetCronTaskFailuresRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_kratos_cron_v1_cron_proto protoreflect.FileDescriptor

const file_kratos_cron_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x19kratos/cron/v1/cron.proto\x12\x0ekratos.cron.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfa\x02\n" +
	"\bCronTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btask_key\x18\x02 \x01(\tR\ataskKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bagent_id\x18\b \x01(\tR\aagentId\x12\x1f\n" +
	"\vconfig_json\x18\t \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rmetadata_json\x18\n" +
	" \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\r \x01(\tR\tdeletedAt\"G\n" +
	"\x15ListCronTasksResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.kratos.cron.v1.CronTaskR\x05items\"\xa6\x02\n" +
	"\x15CreateCronTaskRequest\x12\x1f\n" +
	"\btask_key\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\ataskKey\x12\x18\n" +
	"\x04name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x12\x1f\n" +
	"\vconfig_json\x18\b \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rmetadata_json\x18\t \x01(\tR\fmetadataJson\"*\n" +
	"\x12GetCronTaskRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id\"[\n" +
	"\x15UpdateCronTaskRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id\x12,\n" +
	"\x04task\x18\x02 \x01(\v2\x18.kratos.cron.v1.CronTaskR\x04task\"-\n" +
	"\x15DeleteCronTaskRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id\"\xc1\x02\n" +
	"\vCronTaskRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12\x18\n" +
	"\atrigger\x18\a \x01(\tR\atrigger\x12\x15\n" +
	"\x06run_id\x18\b \x01(\tR\x05runId\x12\x1f\n" +
	"\voutput_json\x18\t \x01(\tR\n" +
	"outputJson\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"i\n" +
	"\x17ListCronTaskRunsRequest\x12 \n" +
	"\fcron_task_id\x18\x01 \x01(\tR\n" +
	"cronTaskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"M\n" +
	"\x18ListCronTaskRunsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.kratos.cron.v1.CronTaskRunR\x05items\".\n" +
	"\x16TriggerCronTaskRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id\"4\n" +
	"\x1cResetCronTaskFailuresRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x02id2\xc6\a\n" +
	"\vCronService\x12f\n" +
	"\rListCronTasks\x12\x16.google.protobuf.Empty\x1a%.kratos.cron.v1.ListCronTasksResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/cron-tasks\x12l\n" +
	"\x0eCreateCronTask\x12%.kratos.cron.v1.CreateCronTaskRequest\x1a\x18.kratos.cron.v1.CronTask\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/cron-tasks\x12h\n" +
	"\vGetCronTask\x12\".kratos.cron.v1.GetCronTaskRequest\x1a\x18.kratos.cron.v1.CronTask\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/cron-tasks/{id}\x12t\n" +
	"\x0eUpdateCronTask\x12%.kratos.cron.v1.UpdateCronTaskRequest\x1a\x18.kratos.cron.v1.CronTask\"!\x82\xd3\xe4\x93\x02\x1b:\x04task2\x13/v1/cron-tasks/{id}\x12l\n" +
	"\x0eDeleteCronTask\x12%.kratos.cron.v1.DeleteCronTaskRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/cron-tasks/{id}\x12\x81\x01\n" +
	"\x10ListCronTaskRuns\x12'.kratos.cron.v1.ListCronTaskRunsRequest\x1a(.kratos.cron.v1.ListCronTaskRunsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/cron-task-runs\x12~\n" +
	"\x0fTriggerCronTask\x12&.kratos.cron.v1.TriggerCronTaskRequest\x1a\x1b.kratos.cron.v1.CronTaskRun\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/cron-tasks/{id}/trigger\x12\x8e\x01\n" +
	"\x15ResetCronTaskFailures\x12,.kratos.cron.v1.ResetCronTaskFailuresRequest\x1a\x18.kratos.cron.v1.CronTask\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/cron-tasks/{id}/reset-failuresB;\n" +
	"\x12api.kratos.cron.v1P\x01Z#aranea-agents/api/kratos/cron/v1;v1b\x06proto3"

var (
	file_kratos_cron_v1_cron_proto_rawDescOnce sync.Once
	file_kratos_cron_v1_cron_proto_rawDescData []byte
)

func file_kratos_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_kratos_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_kratos_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_cron_v1_cron_proto_rawDesc), len(file_kratos_cron_v1_cron_proto_rawDesc)))
	})
	return file_kratos_cron_v1_cron_proto_rawDescData
}

var file_kratos_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kratos_cron_v1_cron_proto_goTypes = []any{
	(*CronTask)(nil),                     // 0: kratos.cron.v1.CronTask
	(*ListCronTasksResponse)(nil),        // 1: kratos.cron.v1.ListCronTasksResponse
	(*CreateCronTaskRequest)(nil),        // 2: kratos.cron.v1.CreateCronTaskRequest
	(*GetCronTaskRequest)(nil),           // 3: kratos.cron.v1.GetCronTaskRequest
	(*UpdateCronTaskRequest)(nil),        // 4: kratos.cron.v1.UpdateCronTaskRequest
	(*DeleteCronTaskRequest)(nil),        // 5: kratos.cron.v1.DeleteCronTaskRequest
	(*CronTaskRun)(nil),                  // 6: kratos.cron.v1.CronTaskRun
	(*ListCronTaskRunsRequest)(nil),      // 7: kratos.cron.v1.ListCronTaskRunsRequest
	(*ListCronTaskRunsResponse)(nil),     // 8: kratos.cron.v1.ListCronTaskRunsResponse
	(*TriggerCronTaskRequest)(nil),       // 9: kratos.cron.v1.TriggerCronTaskRequest
	(*ResetCronTaskFailuresRequest)(nil), // 10: kratos.cron.v1.ResetCronTaskFailuresRequest
	(*emptypb.Empty)(nil),                // 11: google.protobuf.Empty
}
var file_kratos_cron_v1_cron_proto_depIdxs = []int32{
	0,  // 0: kratos.cron.v1.ListCronTasksResponse.items:type_name -> kratos.cron.v1.CronTask
	0,  // 1: kratos.cron.v1.UpdateCronTaskRequest.task:type_name -> kratos.cron.v1.CronTask
	6,  // 2: kratos.cron.v1.ListCronTaskRunsResponse.items:type_name -> kratos.cron.v1.CronTaskRun
	11, // 3: kratos.cron.v1.CronService.ListCronTasks:input_type -> google.protobuf.Empty
	2,  // 4: kratos.cron.v1.CronService.CreateCronTask:input_type -> kratos.cron.v1.CreateCronTaskRequest
	3,  // 5: kratos.cron.v1.CronService.GetCronTask:input_type -> kratos.cron.v1.GetCronTaskRequest
	4,  // 6: kratos.cron.v1.CronService.UpdateCronTask:input_type -> kratos.cron.v1.UpdateCronTaskRequest
	5,  // 7: kratos.cron.v1.CronService.DeleteCronTask:input_type -> kratos.cron.v1.DeleteCronTaskRequest
	7,  // 8: kratos.cron.v1.CronService.ListCronTaskRuns:input_type -> kratos.cron.v1.ListCronTaskRunsRequest
	9,  // 9: kratos.cron.v1.CronService.TriggerCronTask:input_type -> kratos.cron.v1.TriggerCronTaskRequest
	10, // 10: kratos.cron.v1.CronService.ResetCronTaskFailures:input_type -> kratos.cron.v1.ResetCronTaskFailuresRequest
	1,  // 11: kratos.cron.v1.CronService.ListCronTasks:output_type -> kratos.cron.v1.ListCronTasksResponse
	0,  // 12: kratos.cron.v1.CronService.CreateCronTask:output_type -> kratos.cron.v1.CronTask
	0,  // 13: kratos.cron.v1.CronService.GetCronTask:output_type -> kratos.cron.v1.CronTask
	0,  // 14: kratos.cron.v1.CronService.UpdateCronTask:output_type -> kratos.cron.v1.CronTask
	11, // 15: kratos.cron.v1.CronService.DeleteCronTask:output_type -> google.protobuf.Empty
	8,  // 16: kratos.cron.v1.CronService.ListCronTaskRuns:output_type -> kratos.cron.v1.ListCronTaskRunsResponse
	6,  // 17: kratos.cron.v1.CronService.TriggerCronTask:output_type -> kratos.cron.v1.CronTaskRun
	0,  // 18: kratos.cron.v1.CronService.ResetCronTaskFailures:output_type -> kratos.cron.v1.CronTask
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kratos_cron_v1_cron_proto_init() }
func file_kratos_cron_v1_cron_proto_init() {
	if File_kratos_cron_v1_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_cron_v1_cron_proto_rawDesc), len(file_kratos_cron_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_kratos_cron_v1_cron_proto_depIdxs,
		MessageInfos:      file_kratos_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_kratos_cron_v1_cron_proto = out.File
	file_kratos_cron_v1_cron_proto_goTypes = nil
	file_kratos_cron_v1_cron_proto_depIdxs = nil
}
