// Code generated by ent, DO NOT EDIT.

package llmprovidermodel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the llmprovidermodel type in the database.
	Label = "llm_provider_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelKey holds the string denoting the model_key field in the database.
	FieldModelKey = "model_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldConfigJSON holds the string denoting the config_json field in the database.
	FieldConfigJSON = "config_json"
	// FieldMetadataJSON holds the string denoting the metadata_json field in the database.
	FieldMetadataJSON = "metadata_json"
	// FieldCapabilityText holds the string denoting the capability_text field in the database.
	FieldCapabilityText = "capability_text"
	// FieldCapabilityVision holds the string denoting the capability_vision field in the database.
	FieldCapabilityVision = "capability_vision"
	// FieldCapabilityAudio holds the string denoting the capability_audio field in the database.
	FieldCapabilityAudio = "capability_audio"
	// FieldCapabilityFile holds the string denoting the capability_file field in the database.
	FieldCapabilityFile = "capability_file"
	// FieldCapabilityToolCall holds the string denoting the capability_tool_call field in the database.
	FieldCapabilityToolCall = "capability_tool_call"
	// FieldCapabilityCache holds the string denoting the capability_cache field in the database.
	FieldCapabilityCache = "capability_cache"
	// FieldCapabilityThinking holds the string denoting the capability_thinking field in the database.
	FieldCapabilityThinking = "capability_thinking"
	// FieldCapabilityTextOnly holds the string denoting the capability_text_only field in the database.
	FieldCapabilityTextOnly = "capability_text_only"
	// FieldCapabilitiesExplicit holds the string denoting the capabilities_explicit field in the database.
	FieldCapabilitiesExplicit = "capabilities_explicit"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the llmprovidermodel in the database.
	Table = "llm_provider_models"
)

// Columns holds all SQL columns for llmprovidermodel fields.
var Columns = []string{
	FieldID,
	FieldModelKey,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldEnabled,
	FieldSortOrder,
	FieldProvider,
	FieldModel,
	FieldConfigJSON,
	FieldMetadataJSON,
	FieldCapabilityText,
	FieldCapabilityVision,
	FieldCapabilityAudio,
	FieldCapabilityFile,
	FieldCapabilityToolCall,
	FieldCapabilityCache,
	FieldCapabilityThinking,
	FieldCapabilityTextOnly,
	FieldCapabilitiesExplicit,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelKeyValidator is a validator for the "model_key" field. It is called by the builders before save.
	ModelKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultConfigJSON holds the default value on creation for the "config_json" field.
	DefaultConfigJSON string
	// DefaultMetadataJSON holds the default value on creation for the "metadata_json" field.
	DefaultMetadataJSON string
	// DefaultCapabilityText holds the default value on creation for the "capability_text" field.
	DefaultCapabilityText bool
	// DefaultCapabilityVision holds the default value on creation for the "capability_vision" field.
	DefaultCapabilityVision bool
	// DefaultCapabilityAudio holds the default value on creation for the "capability_audio" field.
	DefaultCapabilityAudio bool
	// DefaultCapabilityFile holds the default value on creation for the "capability_file" field.
	DefaultCapabilityFile bool
	// DefaultCapabilityToolCall holds the default value on creation for the "capability_tool_call" field.
	DefaultCapabilityToolCall bool
	// DefaultCapabilityCache holds the default value on creation for the "capability_cache" field.
	DefaultCapabilityCache bool
	// DefaultCapabilityThinking holds the default value on creation for the "capability_thinking" field.
	DefaultCapabilityThinking bool
	// DefaultCapabilityTextOnly holds the default value on creation for the "capability_text_only" field.
	DefaultCapabilityTextOnly bool
	// DefaultCapabilitiesExplicit holds the default value on creation for the "capabilities_explicit" field.
	DefaultCapabilitiesExplicit bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt string
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the LlmProviderModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelKey orders the results by the model_key field.
func ByModelKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByConfigJSON orders the results by the config_json field.
func ByConfigJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigJSON, opts...).ToFunc()
}

// ByMetadataJSON orders the results by the metadata_json field.
func ByMetadataJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataJSON, opts...).ToFunc()
}

// ByCapabilityText orders the results by the capability_text field.
func ByCapabilityText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityText, opts...).ToFunc()
}

// ByCapabilityVision orders the results by the capability_vision field.
func ByCapabilityVision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityVision, opts...).ToFunc()
}

// ByCapabilityAudio orders the results by the capability_audio field.
func ByCapabilityAudio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityAudio, opts...).ToFunc()
}

// ByCapabilityFile orders the results by the capability_file field.
func ByCapabilityFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityFile, opts...).ToFunc()
}

// ByCapabilityToolCall orders the results by the capability_tool_call field.
func ByCapabilityToolCall(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityToolCall, opts...).ToFunc()
}

// ByCapabilityCache orders the results by the capability_cache field.
func ByCapabilityCache(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityCache, opts...).ToFunc()
}

// ByCapabilityThinking orders the results by the capability_thinking field.
func ByCapabilityThinking(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityThinking, opts...).ToFunc()
}

// ByCapabilityTextOnly orders the results by the capability_text_only field.
func ByCapabilityTextOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityTextOnly, opts...).ToFunc()
}

// ByCapabilitiesExplicit orders the results by the capabilities_explicit field.
func ByCapabilitiesExplicit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilitiesExplicit, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
