-- ============================================================
-- Agent 相关表: agents, agent_category_nodes, agent_prompt_files,
--              agent_runtime_settings, avatar_assets, llm_provider_models
-- ============================================================

CREATE TABLE IF NOT EXISTS agents (
  id TEXT PRIMARY KEY,
  agent_key TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL DEFAULT '',
  provider TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  is_default INTEGER NOT NULL DEFAULT 0,
  is_favorite INTEGER NOT NULL DEFAULT 0,
  icon TEXT NOT NULL DEFAULT '',
  agent_description TEXT NOT NULL DEFAULT '',
  category_position_id TEXT NOT NULL DEFAULT '',
  system_prompt_mode TEXT NOT NULL DEFAULT '',
  context_window INTEGER NOT NULL DEFAULT 0,
  budget_monthly_cents INTEGER NOT NULL DEFAULT 0,
  config_json TEXT NOT NULL DEFAULT '',
  roles_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS agent_category_nodes (
  id TEXT PRIMARY KEY,
  category_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  enabled INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  parent_id TEXT NOT NULL DEFAULT '',
  level TEXT NOT NULL DEFAULT '',
  workspace_id TEXT NOT NULL DEFAULT '',
  owner_user_id TEXT NOT NULL DEFAULT '',
  is_system INTEGER NOT NULL DEFAULT 0,
  config_json TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS agent_prompt_files (
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL DEFAULT '',
  file_name TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS agent_runtime_settings (
  agent_id TEXT PRIMARY KEY,
  self_evolve INTEGER NOT NULL DEFAULT 1,
  subagents_enabled INTEGER NOT NULL DEFAULT 1,
  subagents_max_concurrency INTEGER NOT NULL DEFAULT 20,
  subagents_max_generation_depth INTEGER NOT NULL DEFAULT 1,
  subagents_max_children_per_agent INTEGER NOT NULL DEFAULT 5,
  subagents_archive_after_minutes INTEGER NOT NULL DEFAULT 60,
  subagents_max_retries INTEGER NOT NULL DEFAULT 2,
  subagents_model_override TEXT NOT NULL DEFAULT '',
  tools_enabled INTEGER NOT NULL DEFAULT 1,
  tools_profile TEXT NOT NULL DEFAULT 'full',
  tools_tool_call_prefix TEXT NOT NULL DEFAULT '',
  tools_allow_json TEXT NOT NULL DEFAULT '[]',
  tools_deny_json TEXT NOT NULL DEFAULT '[]',
  tools_concurrent_allow_json TEXT NOT NULL DEFAULT '[]',
  memory_enabled INTEGER NOT NULL DEFAULT 1,
  memory_max_chunk_length INTEGER NOT NULL DEFAULT 1000,
  memory_max_results INTEGER NOT NULL DEFAULT 6,
  memory_min_score REAL NOT NULL DEFAULT 0.35,
  heartbeat_enabled INTEGER NOT NULL DEFAULT 0,
  heartbeat_interval_minutes INTEGER NOT NULL DEFAULT 30,
  evolution_self_evolve INTEGER NOT NULL DEFAULT 1,
  evolution_skill_evolve INTEGER NOT NULL DEFAULT 1,
  evolution_metrics_enabled INTEGER NOT NULL DEFAULT 1,
  evolution_suggestions_enabled INTEGER NOT NULL DEFAULT 1,
  guardrail_max_change_per_period REAL NOT NULL DEFAULT 0.1,
  guardrail_min_data_points INTEGER NOT NULL DEFAULT 100,
  guardrail_rollback_on_decline_percent INTEGER NOT NULL DEFAULT 20,
  l0_recent_window_turns INTEGER NOT NULL DEFAULT 12,
  l0_recent_window_tokens INTEGER NOT NULL DEFAULT 0,
  l0_summary_threshold REAL NOT NULL DEFAULT 0.6,
  l0_summary_keep_turns INTEGER NOT NULL DEFAULT 4,
  l0_compress_provider TEXT NOT NULL DEFAULT '',
  l0_compress_model TEXT NOT NULL DEFAULT '',
  l0_truncate_strategy TEXT NOT NULL DEFAULT 'summary',
  l0_inject_l1 INTEGER NOT NULL DEFAULT 1,
  l0_inject_l3 INTEGER NOT NULL DEFAULT 1,
  l0_inject_l4 INTEGER NOT NULL DEFAULT 0,
  l0_l3_max_chunks INTEGER NOT NULL DEFAULT 5,
  l0_l4_max_paths INTEGER NOT NULL DEFAULT 3,
  l0_snapshot_mode TEXT NOT NULL DEFAULT 'on_warning',
  l1_enabled INTEGER NOT NULL DEFAULT 1,
  l1_budget_tokens INTEGER NOT NULL DEFAULT 8192,
  l1_field_max_tokens INTEGER NOT NULL DEFAULT 2048,
  l1_history_keep_revisions INTEGER NOT NULL DEFAULT 10,
  l1_default_schema_id TEXT NOT NULL DEFAULT '',
  l1_archive_on_idle_minutes INTEGER NOT NULL DEFAULT 60,
  l2_episode_enabled INTEGER NOT NULL DEFAULT 1,
  l2_episode_min_importance REAL NOT NULL DEFAULT 0.3,
  l2_index_enabled INTEGER NOT NULL DEFAULT 1,
  l2_index_embedding_model TEXT NOT NULL DEFAULT '',
  l2_recall_enabled INTEGER NOT NULL DEFAULT 0,
  l2_recall_max INTEGER NOT NULL DEFAULT 3,
  l2_retention_days INTEGER NOT NULL DEFAULT 90,
  l2_archive_after_days INTEGER NOT NULL DEFAULT 30,
  l3_enabled INTEGER NOT NULL DEFAULT 1,
  l3_recall_top_k INTEGER NOT NULL DEFAULT 5,
  l3_recall_min_score REAL NOT NULL DEFAULT 0.55,
  l3_recall_scopes_json TEXT NOT NULL DEFAULT '["agent","user","team","workspace"]',
  l3_embedding_model TEXT NOT NULL DEFAULT '',
  l3_decay_interval_hours INTEGER NOT NULL DEFAULT 24,
  l3_archive_threshold REAL NOT NULL DEFAULT 0.2,
  l3_max_per_recall_chars INTEGER NOT NULL DEFAULT 1500,
  l4_enabled INTEGER NOT NULL DEFAULT 1,
  l4_graph_inject_neighbors INTEGER NOT NULL DEFAULT 1,
  l4_graph_max_neighbors INTEGER NOT NULL DEFAULT 6,
  l4_graph_max_hops INTEGER NOT NULL DEFAULT 2,
  l4_identity_inject INTEGER NOT NULL DEFAULT 1,
  l4_strategy_inject INTEGER NOT NULL DEFAULT 0,
  evo_enabled INTEGER NOT NULL DEFAULT 0,
  evo_auto_apply INTEGER NOT NULL DEFAULT 0,
  evo_min_episodes INTEGER NOT NULL DEFAULT 20,
  evo_min_negative_feedback INTEGER NOT NULL DEFAULT 3,
  evo_throttle_hours INTEGER NOT NULL DEFAULT 24,
  evo_proposal_ttl_days INTEGER NOT NULL DEFAULT 14,
  evo_persona_max_chars INTEGER NOT NULL DEFAULT 1500,
  evo_system_prompt_max_appends INTEGER NOT NULL DEFAULT 5,
  skill_runtime_json TEXT NOT NULL DEFAULT '{}',
  intent_pass_enabled INTEGER NOT NULL DEFAULT 1,
  channel_id TEXT NOT NULL DEFAULT '',
  chat_id TEXT NOT NULL DEFAULT '',
  workspace TEXT NOT NULL DEFAULT '',
  reasoning_mode TEXT NOT NULL DEFAULT 'provider_default',
  reasoning_level TEXT NOT NULL DEFAULT 'off',
  variables_json TEXT NOT NULL DEFAULT '{}',
  model_instructions_json TEXT NOT NULL DEFAULT '{}',
  context_compaction_enabled INTEGER NOT NULL DEFAULT 0,
  session_summary_enabled INTEGER NOT NULL DEFAULT 0,
  skill_load_mode TEXT NOT NULL DEFAULT 'auto',
  output_schema_json TEXT NOT NULL DEFAULT '',
  model_selector TEXT NOT NULL DEFAULT 'default',
  tools_retry_enabled INTEGER NOT NULL DEFAULT 0,
  tools_retry_max_attempts INTEGER NOT NULL DEFAULT 2,
  tools_retry_initial_interval_ms INTEGER NOT NULL DEFAULT 500,
  tools_retry_backoff_factor REAL NOT NULL DEFAULT 2.0,
  tools_retry_max_interval_ms INTEGER NOT NULL DEFAULT 5000,
  tools_retry_jitter INTEGER NOT NULL DEFAULT 1,
  tools_parallel_enabled INTEGER NOT NULL DEFAULT 0,
  tools_streaming_enabled INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS avatar_assets (
  id TEXT PRIMARY KEY,
  asset_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  image_data BLOB NOT NULL DEFAULT X'',
  thumbnail_data BLOB,
  mime_type TEXT NOT NULL DEFAULT 'image/png',
  workspace_id TEXT NOT NULL DEFAULT '',
  owner_user_id TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'system',
  is_system INTEGER NOT NULL DEFAULT 0,
  file_size_bytes INTEGER NOT NULL DEFAULT 0,
  width_px INTEGER NOT NULL DEFAULT 0,
  height_px INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  enabled INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  config_json TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS llm_provider_models (
  id TEXT PRIMARY KEY,
  model_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  enabled INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  provider TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '',
  config_json TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT ''
);
