-- ============================================================
-- Memory L2: 情景记忆
-- 表: memory_episodes, memory_l2_index_meta, memory_event_marks
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_episodes (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  run_id TEXT NOT NULL DEFAULT '',
  team_id TEXT NOT NULL DEFAULT '',
  agent_id TEXT NOT NULL DEFAULT '',
  l1_task_id TEXT NOT NULL DEFAULT '',
  episode_kind TEXT NOT NULL DEFAULT 'task',
  title TEXT NOT NULL,
  goal TEXT NOT NULL DEFAULT '',
  outcome TEXT NOT NULL DEFAULT '',
  outcome_summary TEXT NOT NULL DEFAULT '',
  result_preview TEXT NOT NULL DEFAULT '',
  failure_reason TEXT NOT NULL DEFAULT '',
  importance REAL NOT NULL DEFAULT 0.5,
  confidence REAL NOT NULL DEFAULT 0.7,
  user_feedback TEXT NOT NULL DEFAULT '',
  critic_score REAL NOT NULL DEFAULT -1,
  span_count INTEGER NOT NULL DEFAULT 0,
  message_count INTEGER NOT NULL DEFAULT 0,
  tool_call_count INTEGER NOT NULL DEFAULT 0,
  skill_call_count INTEGER NOT NULL DEFAULT 0,
  mcp_call_count INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,
  total_cost_micro_usd INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  l1_snapshot_json TEXT NOT NULL DEFAULT '{}',
  key_decisions_json TEXT NOT NULL DEFAULT '[]',
  key_artifacts_json TEXT NOT NULL DEFAULT '[]',
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dim INTEGER NOT NULL DEFAULT 0,
  embedding_blob BLOB,
  embedding_norm REAL NOT NULL DEFAULT 0,
  consolidation_status TEXT NOT NULL DEFAULT 'pending',
  consolidated_at TEXT NOT NULL DEFAULT '',
  consolidated_l3_count INTEGER NOT NULL DEFAULT 0,
  consolidated_l4_count INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  started_at TEXT NOT NULL DEFAULT '',
  ended_at TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  archived_at TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS memory_l2_index_meta (
  id TEXT PRIMARY KEY,
  episode_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  agent_id TEXT NOT NULL DEFAULT '',
  text_kind TEXT NOT NULL DEFAULT 'episode',
  text_preview TEXT NOT NULL DEFAULT '',
  token_estimate INTEGER NOT NULL DEFAULT 0,
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dim INTEGER NOT NULL DEFAULT 0,
  embedding_blob BLOB,
  embedding_norm REAL NOT NULL DEFAULT 0,
  importance REAL NOT NULL DEFAULT 0.5,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(episode_id, text_kind)
);

CREATE TABLE IF NOT EXISTS memory_event_marks (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  episode_id TEXT NOT NULL DEFAULT '',
  ref_kind TEXT NOT NULL,
  ref_id TEXT NOT NULL,
  mark_type TEXT NOT NULL,
  marked_by TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  weight REAL NOT NULL DEFAULT 1.0,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  deleted_at TEXT NOT NULL DEFAULT '',
  UNIQUE(ref_kind, ref_id, mark_type, marked_by)
);
