extends:
  - "@commitlint/config-conventional"
rules:
  scope-enum:
    - 2
    - always
    - - service
      - biz
      - data
      - plugin
      - tool
      - agent
      - web
      - proto
      - skill
      - ci
      - docs
