FROM debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates  \
		netbase \
		&& rm -rf /var/lib/apt/lists/ \
		&& apt-get autoremove -y && apt-get autoclean -y

COPY bin/linux/admin /app/admin

WORKDIR /app

EXPOSE 8800
EXPOSE 9900
VOLUME /data/conf

CMD ["./admin", "-conf", "/data/conf"]
