import type { AgentRuntimeSettings } from "./types";
import type { AgentAdvancedSettingsForm, AgentRuntimeConfigForm } from "./agentRuntimeConfig";
import { stringifySkillRuntimeJSON } from "./agentSkillRuntimeConfig";

type PromptFileRow = { name: string; body: string };

export function buildRuntimeSettingsPayload(
  config: AgentRuntimeConfigForm,
  advanced: AgentAdvancedSettingsForm,
  extras: Partial<AgentRuntimeSettings> = {},
): AgentRuntimeSettings {
  config.evolution.self_evolve = config.self_evolve;
  return {
    self_evolve: config.self_evolve,
    subagents_enabled: config.subagents.enabled,
    subagents_max_concurrency: config.subagents.max_concurrency,
    subagents_max_generation_depth: config.subagents.max_generation_depth,
    subagents_max_children_per_agent: config.subagents.max_children_per_agent,
    subagents_archive_after_minutes: config.subagents.archive_after_minutes,
    subagents_max_retries: config.subagents.max_retries,
    subagents_model_override: config.subagents.model_override,
    tools_enabled: config.tools.enabled,
    tools_profile: config.tools.profile,
    tools_tool_call_prefix: config.tools.tool_call_prefix,
    tools_allow_json: JSON.stringify(config.tools.allow),
    tools_deny_json: JSON.stringify(config.tools.deny),
    tools_concurrent_allow_json: JSON.stringify(config.tools.concurrent_allow),
    tools_retry_enabled: config.tools.retry.enabled,
    tools_retry_max_attempts: config.tools.retry.max_attempts,
    tools_retry_initial_interval_ms: config.tools.retry.initial_interval_ms,
    tools_retry_backoff_factor: config.tools.retry.backoff_factor,
    tools_retry_max_interval_ms: config.tools.retry.max_interval_ms,
    tools_retry_jitter: config.tools.retry.jitter,
    tools_parallel_enabled: config.tools.parallel_enabled,
    tools_streaming_enabled: config.tools.streaming_enabled,
    memory_enabled: config.memory.enabled,
    memory_max_chunk_length: config.memory.max_chunk_length,
    memory_max_results: config.memory.max_results,
    memory_min_score: config.memory.min_score,
    l0_recent_window_turns: config.memoryL0.recent_window_turns,
    l0_recent_window_tokens: config.memoryL0.recent_window_tokens,
    l0_summary_threshold: config.memoryL0.summary_threshold,
    l0_summary_keep_turns: config.memoryL0.summary_keep_turns,
    l0_compress_provider: config.memoryL0.compress_provider,
    l0_compress_model: config.memoryL0.compress_model,
    memory_worker_provider: config.memoryWorker.provider,
    memory_worker_model: config.memoryWorker.model,
    l0_truncate_strategy: config.memoryL0.truncate_strategy,
    l0_inject_l1: config.memoryL0.inject_l1,
    l0_inject_l3: config.memoryL0.inject_l3,
    l0_inject_l4: config.memoryL0.inject_l4,
    l0_l3_max_chunks: config.memoryL0.l3_max_chunks,
    l0_l4_max_paths: config.memoryL0.l4_max_paths,
    l0_snapshot_mode: config.memoryL0.snapshot_mode,
    l1_enabled: config.memoryL1.enabled,
    l1_budget_tokens: config.memoryL1.budget_tokens,
    l1_field_max_tokens: config.memoryL1.field_max_tokens,
    l1_history_keep_revisions: config.memoryL1.history_keep_revisions,
    l1_default_schema_id: config.memoryL1.default_schema_id,
    l1_archive_on_idle_minutes: config.memoryL1.archive_on_idle_minutes,
    l2_episode_enabled: config.memoryL2.episode_enabled,
    l2_episode_min_importance: config.memoryL2.episode_min_importance,
    l2_index_enabled: config.memoryL2.index_enabled,
    l2_index_embedding_model: config.memoryL2.index_embedding_model,
    l2_recall_enabled: config.memoryL2.recall_enabled,
    l2_recall_max: config.memoryL2.recall_max,
    l2_retention_days: config.memoryL2.retention_days,
    l2_archive_after_days: config.memoryL2.archive_after_days,
    l3_enabled: config.memoryL3.enabled,
    l3_recall_top_k: config.memoryL3.recall_top_k,
    l3_recall_min_score: config.memoryL3.recall_min_score,
    l3_recall_scopes_json: JSON.stringify(config.memoryL3.recall_scopes),
    l3_embedding_model: config.memoryL3.embedding_model,
    l3_decay_interval_hours: config.memoryL3.decay_interval_hours,
    l3_archive_threshold: config.memoryL3.archive_threshold,
    l3_max_per_recall_chars: config.memoryL3.max_per_recall_chars,
    l4_enabled: config.memoryL4.enabled,
    l4_graph_inject_neighbors: config.memoryL4.graph_inject_neighbors,
    l4_graph_max_neighbors: config.memoryL4.graph_max_neighbors,
    l4_graph_max_hops: config.memoryL4.graph_max_hops,
    l4_identity_inject: config.memoryL4.identity_inject,
    l4_strategy_inject: config.memoryL4.strategy_inject,
    evo_enabled: config.evolutionSettings.enabled,
    evo_auto_apply: config.evolutionSettings.auto_apply,
    evo_min_episodes: config.evolutionSettings.min_episodes,
    evo_min_negative_feedback: config.evolutionSettings.min_negative_feedback,
    evo_throttle_hours: config.evolutionSettings.throttle_hours,
    evo_proposal_ttl_days: config.evolutionSettings.proposal_ttl_days,
    evo_persona_max_chars: config.evolutionSettings.persona_max_chars,
    evo_system_prompt_max_appends: config.evolutionSettings.system_prompt_max_appends,
    heartbeat_enabled: config.heartbeat.enabled,
    heartbeat_interval_minutes: config.heartbeat.interval_minutes,
    evolution_self_evolve: config.self_evolve,
    evolution_skill_evolve: config.evolution.skill_evolve,
    evolution_metrics_enabled: config.evolution.evolution_metrics_enabled,
    evolution_suggestions_enabled: config.evolution.evolution_suggestions_enabled,
    guardrail_max_change_per_period: config.evolution_guardrails.max_change_per_period,
    guardrail_min_data_points: config.evolution_guardrails.min_data_points,
    guardrail_rollback_on_decline_percent: config.evolution_guardrails.rollback_on_decline_percent,
    skill_runtime_json: stringifySkillRuntimeJSON(config.skillRuntime),
    code_executor_type: config.code_executor_type || "local",
    intent_pass_enabled: config.intent_pass.enabled,
    channel_id: advanced.channel_id,
    chat_id: advanced.chat_id,
    workspace: advanced.workspace,
    reasoning_mode: advanced.reasoning_mode,
    reasoning_level: advanced.reasoning_level,
    context_compaction_enabled: advanced.context_compaction_enabled,
    session_summary_enabled: advanced.session_summary_enabled,
    ...extras,
  };
}

export function buildAgentConfigJson(config: AgentRuntimeConfigForm, files: PromptFileRow[]) {
  return JSON.stringify({
    self_evolve: config.self_evolve,
    subagents: config.subagents,
    tools: config.tools,
    memory: config.memory,
    memoryL0: config.memoryL0,
    memoryWorker: config.memoryWorker,
    memoryL1: config.memoryL1,
    memoryL2: config.memoryL2,
    memoryL3: config.memoryL3,
    memoryL4: config.memoryL4,
    evolutionSettings: config.evolutionSettings,
    heartbeat: config.heartbeat,
    evolution: config.evolution,
    evolution_guardrails: config.evolution_guardrails,
    skillRuntime: config.skillRuntime,
    intent_pass: config.intent_pass,
    files: files.map((file) => ({ name: file.name, body: file.body })),
  });
}
