// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/backgroundjob"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BackgroundJobCreate is the builder for creating a BackgroundJob entity.
type BackgroundJobCreate struct {
	config
	mutation *BackgroundJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *BackgroundJobCreate) SetKind(v string) *BackgroundJobCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableKind(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetOwnerType sets the "owner_type" field.
func (_c *BackgroundJobCreate) SetOwnerType(v string) *BackgroundJobCreate {
	_c.mutation.SetOwnerType(v)
	return _c
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableOwnerType(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetOwnerType(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *BackgroundJobCreate) SetOwnerID(v string) *BackgroundJobCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableOwnerID(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetParentJobID sets the "parent_job_id" field.
func (_c *BackgroundJobCreate) SetParentJobID(v string) *BackgroundJobCreate {
	_c.mutation.SetParentJobID(v)
	return _c
}

// SetNillableParentJobID sets the "parent_job_id" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableParentJobID(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetParentJobID(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *BackgroundJobCreate) SetPriority(v int) *BackgroundJobCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillablePriority(v *int) *BackgroundJobCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BackgroundJobCreate) SetStatus(v string) *BackgroundJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableStatus(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *BackgroundJobCreate) SetPayload(v []byte) *BackgroundJobCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetWorkerID sets the "worker_id" field.
func (_c *BackgroundJobCreate) SetWorkerID(v string) *BackgroundJobCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableWorkerID(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetWorkerID(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *BackgroundJobCreate) SetAttempts(v int) *BackgroundJobCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableAttempts(v *int) *BackgroundJobCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetMaxAttempts sets the "max_attempts" field.
func (_c *BackgroundJobCreate) SetMaxAttempts(v int) *BackgroundJobCreate {
	_c.mutation.SetMaxAttempts(v)
	return _c
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableMaxAttempts(v *int) *BackgroundJobCreate {
	if v != nil {
		_c.SetMaxAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *BackgroundJobCreate) SetLastError(v string) *BackgroundJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableLastError(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *BackgroundJobCreate) SetScheduledAt(v int64) *BackgroundJobCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableScheduledAt(v *int64) *BackgroundJobCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *BackgroundJobCreate) SetClaimedAt(v int64) *BackgroundJobCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableClaimedAt(v *int64) *BackgroundJobCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *BackgroundJobCreate) SetFinishedAt(v int64) *BackgroundJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableFinishedAt(v *int64) *BackgroundJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BackgroundJobCreate) SetCreatedAt(v string) *BackgroundJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableCreatedAt(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BackgroundJobCreate) SetUpdatedAt(v string) *BackgroundJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BackgroundJobCreate) SetNillableUpdatedAt(v *string) *BackgroundJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BackgroundJobCreate) SetID(v string) *BackgroundJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BackgroundJobMutation object of the builder.
func (_c *BackgroundJobCreate) Mutation() *BackgroundJobMutation {
	return _c.mutation
}

// Save creates the BackgroundJob in the database.
func (_c *BackgroundJobCreate) Save(ctx context.Context) (*BackgroundJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BackgroundJobCreate) SaveX(ctx context.Context) *BackgroundJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackgroundJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackgroundJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BackgroundJobCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := backgroundjob.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.OwnerType(); !ok {
		v := backgroundjob.DefaultOwnerType
		_c.mutation.SetOwnerType(v)
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		v := backgroundjob.DefaultOwnerID
		_c.mutation.SetOwnerID(v)
	}
	if _, ok := _c.mutation.ParentJobID(); !ok {
		v := backgroundjob.DefaultParentJobID
		_c.mutation.SetParentJobID(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := backgroundjob.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := backgroundjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := backgroundjob.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.WorkerID(); !ok {
		v := backgroundjob.DefaultWorkerID
		_c.mutation.SetWorkerID(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := backgroundjob.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.MaxAttempts(); !ok {
		v := backgroundjob.DefaultMaxAttempts
		_c.mutation.SetMaxAttempts(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := backgroundjob.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		v := backgroundjob.DefaultScheduledAt
		_c.mutation.SetScheduledAt(v)
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		v := backgroundjob.DefaultClaimedAt
		_c.mutation.SetClaimedAt(v)
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		v := backgroundjob.DefaultFinishedAt
		_c.mutation.SetFinishedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := backgroundjob.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := backgroundjob.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BackgroundJobCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "BackgroundJob.kind"`)}
	}
	if _, ok := _c.mutation.OwnerType(); !ok {
		return &ValidationError{Name: "owner_type", err: errors.New(`ent: missing required field "BackgroundJob.owner_type"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "BackgroundJob.owner_id"`)}
	}
	if _, ok := _c.mutation.ParentJobID(); !ok {
		return &ValidationError{Name: "parent_job_id", err: errors.New(`ent: missing required field "BackgroundJob.parent_job_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "BackgroundJob.priority"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BackgroundJob.status"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "BackgroundJob.payload"`)}
	}
	if _, ok := _c.mutation.WorkerID(); !ok {
		return &ValidationError{Name: "worker_id", err: errors.New(`ent: missing required field "BackgroundJob.worker_id"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "BackgroundJob.attempts"`)}
	}
	if _, ok := _c.mutation.MaxAttempts(); !ok {
		return &ValidationError{Name: "max_attempts", err: errors.New(`ent: missing required field "BackgroundJob.max_attempts"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "BackgroundJob.last_error"`)}
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		return &ValidationError{Name: "scheduled_at", err: errors.New(`ent: missing required field "BackgroundJob.scheduled_at"`)}
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		return &ValidationError{Name: "claimed_at", err: errors.New(`ent: missing required field "BackgroundJob.claimed_at"`)}
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		return &ValidationError{Name: "finished_at", err: errors.New(`ent: missing required field "BackgroundJob.finished_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BackgroundJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BackgroundJob.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := backgroundjob.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BackgroundJob.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BackgroundJobCreate) sqlSave(ctx context.Context) (*BackgroundJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BackgroundJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BackgroundJobCreate) createSpec() (*BackgroundJob, *sqlgraph.CreateSpec) {
	var (
		_node = &BackgroundJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backgroundjob.Table, sqlgraph.NewFieldSpec(backgroundjob.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(backgroundjob.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.OwnerType(); ok {
		_spec.SetField(backgroundjob.FieldOwnerType, field.TypeString, value)
		_node.OwnerType = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(backgroundjob.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.ParentJobID(); ok {
		_spec.SetField(backgroundjob.FieldParentJobID, field.TypeString, value)
		_node.ParentJobID = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(backgroundjob.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(backgroundjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(backgroundjob.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.WorkerID(); ok {
		_spec.SetField(backgroundjob.FieldWorkerID, field.TypeString, value)
		_node.WorkerID = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(backgroundjob.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.MaxAttempts(); ok {
		_spec.SetField(backgroundjob.FieldMaxAttempts, field.TypeInt, value)
		_node.MaxAttempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(backgroundjob.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(backgroundjob.FieldScheduledAt, field.TypeInt64, value)
		_node.ScheduledAt = value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(backgroundjob.FieldClaimedAt, field.TypeInt64, value)
		_node.ClaimedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(backgroundjob.FieldFinishedAt, field.TypeInt64, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(backgroundjob.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(backgroundjob.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BackgroundJob.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BackgroundJobUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *BackgroundJobCreate) OnConflict(opts ...sql.ConflictOption) *BackgroundJobUpsertOne {
	_c.conflict = opts
	return &BackgroundJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BackgroundJobCreate) OnConflictColumns(columns ...string) *BackgroundJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BackgroundJobUpsertOne{
		create: _c,
	}
}

type (
	// BackgroundJobUpsertOne is the builder for "upsert"-ing
	//  one BackgroundJob node.
	BackgroundJobUpsertOne struct {
		create *BackgroundJobCreate
	}

	// BackgroundJobUpsert is the "OnConflict" setter.
	BackgroundJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *BackgroundJobUpsert) SetKind(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateKind() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldKind)
	return u
}

// SetOwnerType sets the "owner_type" field.
func (u *BackgroundJobUpsert) SetOwnerType(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldOwnerType, v)
	return u
}

// UpdateOwnerType sets the "owner_type" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateOwnerType() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldOwnerType)
	return u
}

// SetOwnerID sets the "owner_id" field.
func (u *BackgroundJobUpsert) SetOwnerID(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldOwnerID, v)
	return u
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateOwnerID() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldOwnerID)
	return u
}

// SetParentJobID sets the "parent_job_id" field.
func (u *BackgroundJobUpsert) SetParentJobID(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldParentJobID, v)
	return u
}

// UpdateParentJobID sets the "parent_job_id" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateParentJobID() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldParentJobID)
	return u
}

// SetPriority sets the "priority" field.
func (u *BackgroundJobUpsert) SetPriority(v int) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdatePriority() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *BackgroundJobUpsert) AddPriority(v int) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldPriority, v)
	return u
}

// SetStatus sets the "status" field.
func (u *BackgroundJobUpsert) SetStatus(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateStatus() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldStatus)
	return u
}

// SetPayload sets the "payload" field.
func (u *BackgroundJobUpsert) SetPayload(v []byte) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdatePayload() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldPayload)
	return u
}

// SetWorkerID sets the "worker_id" field.
func (u *BackgroundJobUpsert) SetWorkerID(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldWorkerID, v)
	return u
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateWorkerID() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldWorkerID)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *BackgroundJobUpsert) SetAttempts(v int) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateAttempts() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *BackgroundJobUpsert) AddAttempts(v int) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldAttempts, v)
	return u
}

// SetMaxAttempts sets the "max_attempts" field.
func (u *BackgroundJobUpsert) SetMaxAttempts(v int) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldMaxAttempts, v)
	return u
}

// UpdateMaxAttempts sets the "max_attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateMaxAttempts() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldMaxAttempts)
	return u
}

// AddMaxAttempts adds v to the "max_attempts" field.
func (u *BackgroundJobUpsert) AddMaxAttempts(v int) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldMaxAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *BackgroundJobUpsert) SetLastError(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateLastError() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldLastError)
	return u
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *BackgroundJobUpsert) SetScheduledAt(v int64) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldScheduledAt, v)
	return u
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateScheduledAt() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldScheduledAt)
	return u
}

// AddScheduledAt adds v to the "scheduled_at" field.
func (u *BackgroundJobUpsert) AddScheduledAt(v int64) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldScheduledAt, v)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BackgroundJobUpsert) SetClaimedAt(v int64) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateClaimedAt() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldClaimedAt)
	return u
}

// AddClaimedAt adds v to the "claimed_at" field.
func (u *BackgroundJobUpsert) AddClaimedAt(v int64) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldClaimedAt, v)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *BackgroundJobUpsert) SetFinishedAt(v int64) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateFinishedAt() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldFinishedAt)
	return u
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *BackgroundJobUpsert) AddFinishedAt(v int64) *BackgroundJobUpsert {
	u.Add(backgroundjob.FieldFinishedAt, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *BackgroundJobUpsert) SetCreatedAt(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateCreatedAt() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BackgroundJobUpsert) SetUpdatedAt(v string) *BackgroundJobUpsert {
	u.Set(backgroundjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BackgroundJobUpsert) UpdateUpdatedAt() *BackgroundJobUpsert {
	u.SetExcluded(backgroundjob.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(backgroundjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BackgroundJobUpsertOne) UpdateNewValues() *BackgroundJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(backgroundjob.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BackgroundJobUpsertOne) Ignore() *BackgroundJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BackgroundJobUpsertOne) DoNothing() *BackgroundJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BackgroundJobCreate.OnConflict
// documentation for more info.
func (u *BackgroundJobUpsertOne) Update(set func(*BackgroundJobUpsert)) *BackgroundJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BackgroundJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *BackgroundJobUpsertOne) SetKind(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateKind() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateKind()
	})
}

// SetOwnerType sets the "owner_type" field.
func (u *BackgroundJobUpsertOne) SetOwnerType(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetOwnerType(v)
	})
}

// UpdateOwnerType sets the "owner_type" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateOwnerType() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateOwnerType()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *BackgroundJobUpsertOne) SetOwnerID(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateOwnerID() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateOwnerID()
	})
}

// SetParentJobID sets the "parent_job_id" field.
func (u *BackgroundJobUpsertOne) SetParentJobID(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetParentJobID(v)
	})
}

// UpdateParentJobID sets the "parent_job_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateParentJobID() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateParentJobID()
	})
}

// SetPriority sets the "priority" field.
func (u *BackgroundJobUpsertOne) SetPriority(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *BackgroundJobUpsertOne) AddPriority(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdatePriority() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *BackgroundJobUpsertOne) SetStatus(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateStatus() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateStatus()
	})
}

// SetPayload sets the "payload" field.
func (u *BackgroundJobUpsertOne) SetPayload(v []byte) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdatePayload() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdatePayload()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *BackgroundJobUpsertOne) SetWorkerID(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateWorkerID() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateWorkerID()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BackgroundJobUpsertOne) SetAttempts(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BackgroundJobUpsertOne) AddAttempts(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateAttempts() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateAttempts()
	})
}

// SetMaxAttempts sets the "max_attempts" field.
func (u *BackgroundJobUpsertOne) SetMaxAttempts(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetMaxAttempts(v)
	})
}

// AddMaxAttempts adds v to the "max_attempts" field.
func (u *BackgroundJobUpsertOne) AddMaxAttempts(v int) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddMaxAttempts(v)
	})
}

// UpdateMaxAttempts sets the "max_attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateMaxAttempts() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateMaxAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BackgroundJobUpsertOne) SetLastError(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateLastError() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateLastError()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *BackgroundJobUpsertOne) SetScheduledAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetScheduledAt(v)
	})
}

// AddScheduledAt adds v to the "scheduled_at" field.
func (u *BackgroundJobUpsertOne) AddScheduledAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateScheduledAt() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateScheduledAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BackgroundJobUpsertOne) SetClaimedAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetClaimedAt(v)
	})
}

// AddClaimedAt adds v to the "claimed_at" field.
func (u *BackgroundJobUpsertOne) AddClaimedAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateClaimedAt() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateClaimedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BackgroundJobUpsertOne) SetFinishedAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *BackgroundJobUpsertOne) AddFinishedAt(v int64) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateFinishedAt() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *BackgroundJobUpsertOne) SetCreatedAt(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateCreatedAt() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BackgroundJobUpsertOne) SetUpdatedAt(v string) *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertOne) UpdateUpdatedAt() *BackgroundJobUpsertOne {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BackgroundJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BackgroundJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BackgroundJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BackgroundJobUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BackgroundJobUpsertOne.ID is not supported by MySQL driver. Use BackgroundJobUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BackgroundJobUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BackgroundJobCreateBulk is the builder for creating many BackgroundJob entities in bulk.
type BackgroundJobCreateBulk struct {
	config
	err      error
	builders []*BackgroundJobCreate
	conflict []sql.ConflictOption
}

// Save creates the BackgroundJob entities in the database.
func (_c *BackgroundJobCreateBulk) Save(ctx context.Context) ([]*BackgroundJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BackgroundJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackgroundJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BackgroundJobCreateBulk) SaveX(ctx context.Context) []*BackgroundJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackgroundJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackgroundJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BackgroundJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BackgroundJobUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *BackgroundJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *BackgroundJobUpsertBulk {
	_c.conflict = opts
	return &BackgroundJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BackgroundJobCreateBulk) OnConflictColumns(columns ...string) *BackgroundJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BackgroundJobUpsertBulk{
		create: _c,
	}
}

// BackgroundJobUpsertBulk is the builder for "upsert"-ing
// a bulk of BackgroundJob nodes.
type BackgroundJobUpsertBulk struct {
	create *BackgroundJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(backgroundjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BackgroundJobUpsertBulk) UpdateNewValues() *BackgroundJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(backgroundjob.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BackgroundJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BackgroundJobUpsertBulk) Ignore() *BackgroundJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BackgroundJobUpsertBulk) DoNothing() *BackgroundJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BackgroundJobCreateBulk.OnConflict
// documentation for more info.
func (u *BackgroundJobUpsertBulk) Update(set func(*BackgroundJobUpsert)) *BackgroundJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BackgroundJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *BackgroundJobUpsertBulk) SetKind(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateKind() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateKind()
	})
}

// SetOwnerType sets the "owner_type" field.
func (u *BackgroundJobUpsertBulk) SetOwnerType(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetOwnerType(v)
	})
}

// UpdateOwnerType sets the "owner_type" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateOwnerType() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateOwnerType()
	})
}

// SetOwnerID sets the "owner_id" field.
func (u *BackgroundJobUpsertBulk) SetOwnerID(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetOwnerID(v)
	})
}

// UpdateOwnerID sets the "owner_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateOwnerID() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateOwnerID()
	})
}

// SetParentJobID sets the "parent_job_id" field.
func (u *BackgroundJobUpsertBulk) SetParentJobID(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetParentJobID(v)
	})
}

// UpdateParentJobID sets the "parent_job_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateParentJobID() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateParentJobID()
	})
}

// SetPriority sets the "priority" field.
func (u *BackgroundJobUpsertBulk) SetPriority(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *BackgroundJobUpsertBulk) AddPriority(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdatePriority() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *BackgroundJobUpsertBulk) SetStatus(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateStatus() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateStatus()
	})
}

// SetPayload sets the "payload" field.
func (u *BackgroundJobUpsertBulk) SetPayload(v []byte) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdatePayload() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdatePayload()
	})
}

// SetWorkerID sets the "worker_id" field.
func (u *BackgroundJobUpsertBulk) SetWorkerID(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetWorkerID(v)
	})
}

// UpdateWorkerID sets the "worker_id" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateWorkerID() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateWorkerID()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BackgroundJobUpsertBulk) SetAttempts(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BackgroundJobUpsertBulk) AddAttempts(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateAttempts() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateAttempts()
	})
}

// SetMaxAttempts sets the "max_attempts" field.
func (u *BackgroundJobUpsertBulk) SetMaxAttempts(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetMaxAttempts(v)
	})
}

// AddMaxAttempts adds v to the "max_attempts" field.
func (u *BackgroundJobUpsertBulk) AddMaxAttempts(v int) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddMaxAttempts(v)
	})
}

// UpdateMaxAttempts sets the "max_attempts" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateMaxAttempts() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateMaxAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BackgroundJobUpsertBulk) SetLastError(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateLastError() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateLastError()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *BackgroundJobUpsertBulk) SetScheduledAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetScheduledAt(v)
	})
}

// AddScheduledAt adds v to the "scheduled_at" field.
func (u *BackgroundJobUpsertBulk) AddScheduledAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateScheduledAt() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateScheduledAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *BackgroundJobUpsertBulk) SetClaimedAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetClaimedAt(v)
	})
}

// AddClaimedAt adds v to the "claimed_at" field.
func (u *BackgroundJobUpsertBulk) AddClaimedAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateClaimedAt() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateClaimedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *BackgroundJobUpsertBulk) SetFinishedAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// AddFinishedAt adds v to the "finished_at" field.
func (u *BackgroundJobUpsertBulk) AddFinishedAt(v int64) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.AddFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateFinishedAt() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *BackgroundJobUpsertBulk) SetCreatedAt(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateCreatedAt() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BackgroundJobUpsertBulk) SetUpdatedAt(v string) *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BackgroundJobUpsertBulk) UpdateUpdatedAt() *BackgroundJobUpsertBulk {
	return u.Update(func(s *BackgroundJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BackgroundJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BackgroundJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BackgroundJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BackgroundJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
