// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/borrowrequest"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BorrowRequest is the model entity for the BorrowRequest schema.
type BorrowRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// target team that wants to borrow the agent
	TeamID string `json:"team_id,omitempty"`
	// agent being borrowed
	AgentID string `json:"agent_id,omitempty"`
	// department that owns the agent
	FromDeptID string `json:"from_dept_id,omitempty"`
	// department that wants to borrow the agent
	ToDeptID string `json:"to_dept_id,omitempty"`
	// pending | approved | rejected | auto_approved
	Status string `json:"status,omitempty"`
	// reason for the borrow request
	Reason string `json:"reason,omitempty"`
	// dept lead agent ID who reviewed
	ReviewedBy string `json:"reviewed_by,omitempty"`
	// reason for approval/rejection
	ReviewReason string `json:"review_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    string `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BorrowRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case borrowrequest.FieldID, borrowrequest.FieldTeamID, borrowrequest.FieldAgentID, borrowrequest.FieldFromDeptID, borrowrequest.FieldToDeptID, borrowrequest.FieldStatus, borrowrequest.FieldReason, borrowrequest.FieldReviewedBy, borrowrequest.FieldReviewReason, borrowrequest.FieldCreatedAt, borrowrequest.FieldUpdatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BorrowRequest fields.
func (_m *BorrowRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case borrowrequest.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case borrowrequest.FieldTeamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.String
			}
		case borrowrequest.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = value.String
			}
		case borrowrequest.FieldFromDeptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_dept_id", values[i])
			} else if value.Valid {
				_m.FromDeptID = value.String
			}
		case borrowrequest.FieldToDeptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_dept_id", values[i])
			} else if value.Valid {
				_m.ToDeptID = value.String
			}
		case borrowrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case borrowrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case borrowrequest.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = value.String
			}
		case borrowrequest.FieldReviewReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_reason", values[i])
			} else if value.Valid {
				_m.ReviewReason = value.String
			}
		case borrowrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case borrowrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BorrowRequest.
// This includes values selected through modifiers, order, etc.
func (_m *BorrowRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BorrowRequest.
// Note that you need to call BorrowRequest.Unwrap() before calling this method if this BorrowRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BorrowRequest) Update() *BorrowRequestUpdateOne {
	return NewBorrowRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BorrowRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BorrowRequest) Unwrap() *BorrowRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BorrowRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BorrowRequest) String() string {
	var builder strings.Builder
	builder.WriteString("BorrowRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(_m.TeamID)
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(_m.AgentID)
	builder.WriteString(", ")
	builder.WriteString("from_dept_id=")
	builder.WriteString(_m.FromDeptID)
	builder.WriteString(", ")
	builder.WriteString("to_dept_id=")
	builder.WriteString(_m.ToDeptID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(_m.ReviewedBy)
	builder.WriteString(", ")
	builder.WriteString("review_reason=")
	builder.WriteString(_m.ReviewReason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// BorrowRequests is a parsable slice of BorrowRequest.
type BorrowRequests []*BorrowRequest
