// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/codingtask"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodingTaskCreate is the builder for creating a CodingTask entity.
type CodingTaskCreate struct {
	config
	mutation *CodingTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWorkspace sets the "workspace" field.
func (_c *CodingTaskCreate) SetWorkspace(v string) *CodingTaskCreate {
	_c.mutation.SetWorkspace(v)
	return _c
}

// SetNillableWorkspace sets the "workspace" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableWorkspace(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetWorkspace(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *CodingTaskCreate) SetSessionID(v string) *CodingTaskCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *CodingTaskCreate) SetAgentID(v string) *CodingTaskCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *CodingTaskCreate) SetProjectID(v string) *CodingTaskCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *CodingTaskCreate) SetPrompt(v string) *CodingTaskCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillablePrompt(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetPrompt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CodingTaskCreate) SetStatus(v string) *CodingTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableStatus(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAcpSessionID sets the "acp_session_id" field.
func (_c *CodingTaskCreate) SetAcpSessionID(v string) *CodingTaskCreate {
	_c.mutation.SetAcpSessionID(v)
	return _c
}

// SetNillableAcpSessionID sets the "acp_session_id" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableAcpSessionID(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetAcpSessionID(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *CodingTaskCreate) SetSummary(v string) *CodingTaskCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableSummary(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *CodingTaskCreate) SetError(v string) *CodingTaskCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableError(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetProgressCount sets the "progress_count" field.
func (_c *CodingTaskCreate) SetProgressCount(v int) *CodingTaskCreate {
	_c.mutation.SetProgressCount(v)
	return _c
}

// SetNillableProgressCount sets the "progress_count" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableProgressCount(v *int) *CodingTaskCreate {
	if v != nil {
		_c.SetProgressCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodingTaskCreate) SetCreatedAt(v string) *CodingTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableCreatedAt(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodingTaskCreate) SetUpdatedAt(v string) *CodingTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableUpdatedAt(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *CodingTaskCreate) SetCompletedAt(v string) *CodingTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *CodingTaskCreate) SetNillableCompletedAt(v *string) *CodingTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CodingTaskCreate) SetID(v string) *CodingTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CodingTaskMutation object of the builder.
func (_c *CodingTaskCreate) Mutation() *CodingTaskMutation {
	return _c.mutation
}

// Save creates the CodingTask in the database.
func (_c *CodingTaskCreate) Save(ctx context.Context) (*CodingTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodingTaskCreate) SaveX(ctx context.Context) *CodingTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodingTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodingTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodingTaskCreate) defaults() {
	if _, ok := _c.mutation.Workspace(); !ok {
		v := codingtask.DefaultWorkspace
		_c.mutation.SetWorkspace(v)
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		v := codingtask.DefaultPrompt
		_c.mutation.SetPrompt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := codingtask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AcpSessionID(); !ok {
		v := codingtask.DefaultAcpSessionID
		_c.mutation.SetAcpSessionID(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := codingtask.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := codingtask.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.ProgressCount(); !ok {
		v := codingtask.DefaultProgressCount
		_c.mutation.SetProgressCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codingtask.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codingtask.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CompletedAt(); !ok {
		v := codingtask.DefaultCompletedAt
		_c.mutation.SetCompletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodingTaskCreate) check() error {
	if _, ok := _c.mutation.Workspace(); !ok {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required field "CodingTask.workspace"`)}
	}
	if v, ok := _c.mutation.Workspace(); ok {
		if err := codingtask.WorkspaceValidator(v); err != nil {
			return &ValidationError{Name: "workspace", err: fmt.Errorf(`ent: validator failed for field "CodingTask.workspace": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "CodingTask.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := codingtask.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "CodingTask.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "CodingTask.agent_id"`)}
	}
	if v, ok := _c.mutation.AgentID(); ok {
		if err := codingtask.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "CodingTask.agent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "CodingTask.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := codingtask.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "CodingTask.project_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "CodingTask.prompt"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CodingTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := codingtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CodingTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AcpSessionID(); !ok {
		return &ValidationError{Name: "acp_session_id", err: errors.New(`ent: missing required field "CodingTask.acp_session_id"`)}
	}
	if v, ok := _c.mutation.AcpSessionID(); ok {
		if err := codingtask.AcpSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "acp_session_id", err: fmt.Errorf(`ent: validator failed for field "CodingTask.acp_session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "CodingTask.summary"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "CodingTask.error"`)}
	}
	if _, ok := _c.mutation.ProgressCount(); !ok {
		return &ValidationError{Name: "progress_count", err: errors.New(`ent: missing required field "CodingTask.progress_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodingTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodingTask.updated_at"`)}
	}
	if _, ok := _c.mutation.CompletedAt(); !ok {
		return &ValidationError{Name: "completed_at", err: errors.New(`ent: missing required field "CodingTask.completed_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := codingtask.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CodingTask.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CodingTaskCreate) sqlSave(ctx context.Context) (*CodingTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CodingTask.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodingTaskCreate) createSpec() (*CodingTask, *sqlgraph.CreateSpec) {
	var (
		_node = &CodingTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codingtask.Table, sqlgraph.NewFieldSpec(codingtask.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Workspace(); ok {
		_spec.SetField(codingtask.FieldWorkspace, field.TypeString, value)
		_node.Workspace = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(codingtask.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(codingtask.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(codingtask.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(codingtask.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(codingtask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AcpSessionID(); ok {
		_spec.SetField(codingtask.FieldAcpSessionID, field.TypeString, value)
		_node.AcpSessionID = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(codingtask.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(codingtask.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.ProgressCount(); ok {
		_spec.SetField(codingtask.FieldProgressCount, field.TypeInt, value)
		_node.ProgressCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codingtask.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codingtask.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(codingtask.FieldCompletedAt, field.TypeString, value)
		_node.CompletedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodingTask.Create().
//		SetWorkspace(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodingTaskUpsert) {
//			SetWorkspace(v+v).
//		}).
//		Exec(ctx)
func (_c *CodingTaskCreate) OnConflict(opts ...sql.ConflictOption) *CodingTaskUpsertOne {
	_c.conflict = opts
	return &CodingTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodingTaskCreate) OnConflictColumns(columns ...string) *CodingTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodingTaskUpsertOne{
		create: _c,
	}
}

type (
	// CodingTaskUpsertOne is the builder for "upsert"-ing
	//  one CodingTask node.
	CodingTaskUpsertOne struct {
		create *CodingTaskCreate
	}

	// CodingTaskUpsert is the "OnConflict" setter.
	CodingTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetWorkspace sets the "workspace" field.
func (u *CodingTaskUpsert) SetWorkspace(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldWorkspace, v)
	return u
}

// UpdateWorkspace sets the "workspace" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateWorkspace() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldWorkspace)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *CodingTaskUpsert) SetSessionID(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateSessionID() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldSessionID)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *CodingTaskUpsert) SetAgentID(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateAgentID() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldAgentID)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *CodingTaskUpsert) SetProjectID(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateProjectID() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldProjectID)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *CodingTaskUpsert) SetPrompt(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdatePrompt() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldPrompt)
	return u
}

// SetStatus sets the "status" field.
func (u *CodingTaskUpsert) SetStatus(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateStatus() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldStatus)
	return u
}

// SetAcpSessionID sets the "acp_session_id" field.
func (u *CodingTaskUpsert) SetAcpSessionID(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldAcpSessionID, v)
	return u
}

// UpdateAcpSessionID sets the "acp_session_id" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateAcpSessionID() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldAcpSessionID)
	return u
}

// SetSummary sets the "summary" field.
func (u *CodingTaskUpsert) SetSummary(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateSummary() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldSummary)
	return u
}

// SetError sets the "error" field.
func (u *CodingTaskUpsert) SetError(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateError() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldError)
	return u
}

// SetProgressCount sets the "progress_count" field.
func (u *CodingTaskUpsert) SetProgressCount(v int) *CodingTaskUpsert {
	u.Set(codingtask.FieldProgressCount, v)
	return u
}

// UpdateProgressCount sets the "progress_count" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateProgressCount() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldProgressCount)
	return u
}

// AddProgressCount adds v to the "progress_count" field.
func (u *CodingTaskUpsert) AddProgressCount(v int) *CodingTaskUpsert {
	u.Add(codingtask.FieldProgressCount, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CodingTaskUpsert) SetCreatedAt(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateCreatedAt() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodingTaskUpsert) SetUpdatedAt(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateUpdatedAt() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldUpdatedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *CodingTaskUpsert) SetCompletedAt(v string) *CodingTaskUpsert {
	u.Set(codingtask.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CodingTaskUpsert) UpdateCompletedAt() *CodingTaskUpsert {
	u.SetExcluded(codingtask.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(codingtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CodingTaskUpsertOne) UpdateNewValues() *CodingTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(codingtask.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CodingTaskUpsertOne) Ignore() *CodingTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodingTaskUpsertOne) DoNothing() *CodingTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodingTaskCreate.OnConflict
// documentation for more info.
func (u *CodingTaskUpsertOne) Update(set func(*CodingTaskUpsert)) *CodingTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodingTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspace sets the "workspace" field.
func (u *CodingTaskUpsertOne) SetWorkspace(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetWorkspace(v)
	})
}

// UpdateWorkspace sets the "workspace" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateWorkspace() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateWorkspace()
	})
}

// SetSessionID sets the "session_id" field.
func (u *CodingTaskUpsertOne) SetSessionID(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateSessionID() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateSessionID()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *CodingTaskUpsertOne) SetAgentID(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateAgentID() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateAgentID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *CodingTaskUpsertOne) SetProjectID(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateProjectID() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateProjectID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *CodingTaskUpsertOne) SetPrompt(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdatePrompt() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdatePrompt()
	})
}

// SetStatus sets the "status" field.
func (u *CodingTaskUpsertOne) SetStatus(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateStatus() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetAcpSessionID sets the "acp_session_id" field.
func (u *CodingTaskUpsertOne) SetAcpSessionID(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetAcpSessionID(v)
	})
}

// UpdateAcpSessionID sets the "acp_session_id" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateAcpSessionID() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateAcpSessionID()
	})
}

// SetSummary sets the "summary" field.
func (u *CodingTaskUpsertOne) SetSummary(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateSummary() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateSummary()
	})
}

// SetError sets the "error" field.
func (u *CodingTaskUpsertOne) SetError(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateError() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateError()
	})
}

// SetProgressCount sets the "progress_count" field.
func (u *CodingTaskUpsertOne) SetProgressCount(v int) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetProgressCount(v)
	})
}

// AddProgressCount adds v to the "progress_count" field.
func (u *CodingTaskUpsertOne) AddProgressCount(v int) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.AddProgressCount(v)
	})
}

// UpdateProgressCount sets the "progress_count" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateProgressCount() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateProgressCount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CodingTaskUpsertOne) SetCreatedAt(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateCreatedAt() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodingTaskUpsertOne) SetUpdatedAt(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateUpdatedAt() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CodingTaskUpsertOne) SetCompletedAt(v string) *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CodingTaskUpsertOne) UpdateCompletedAt() *CodingTaskUpsertOne {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// Exec executes the query.
func (u *CodingTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodingTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodingTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CodingTaskUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CodingTaskUpsertOne.ID is not supported by MySQL driver. Use CodingTaskUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CodingTaskUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CodingTaskCreateBulk is the builder for creating many CodingTask entities in bulk.
type CodingTaskCreateBulk struct {
	config
	err      error
	builders []*CodingTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the CodingTask entities in the database.
func (_c *CodingTaskCreateBulk) Save(ctx context.Context) ([]*CodingTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodingTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodingTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodingTaskCreateBulk) SaveX(ctx context.Context) []*CodingTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodingTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodingTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CodingTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CodingTaskUpsert) {
//			SetWorkspace(v+v).
//		}).
//		Exec(ctx)
func (_c *CodingTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *CodingTaskUpsertBulk {
	_c.conflict = opts
	return &CodingTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CodingTaskCreateBulk) OnConflictColumns(columns ...string) *CodingTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CodingTaskUpsertBulk{
		create: _c,
	}
}

// CodingTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of CodingTask nodes.
type CodingTaskUpsertBulk struct {
	create *CodingTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(codingtask.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CodingTaskUpsertBulk) UpdateNewValues() *CodingTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(codingtask.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CodingTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CodingTaskUpsertBulk) Ignore() *CodingTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CodingTaskUpsertBulk) DoNothing() *CodingTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CodingTaskCreateBulk.OnConflict
// documentation for more info.
func (u *CodingTaskUpsertBulk) Update(set func(*CodingTaskUpsert)) *CodingTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CodingTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetWorkspace sets the "workspace" field.
func (u *CodingTaskUpsertBulk) SetWorkspace(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetWorkspace(v)
	})
}

// UpdateWorkspace sets the "workspace" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateWorkspace() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateWorkspace()
	})
}

// SetSessionID sets the "session_id" field.
func (u *CodingTaskUpsertBulk) SetSessionID(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateSessionID() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateSessionID()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *CodingTaskUpsertBulk) SetAgentID(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateAgentID() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateAgentID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *CodingTaskUpsertBulk) SetProjectID(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateProjectID() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateProjectID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *CodingTaskUpsertBulk) SetPrompt(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdatePrompt() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdatePrompt()
	})
}

// SetStatus sets the "status" field.
func (u *CodingTaskUpsertBulk) SetStatus(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateStatus() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetAcpSessionID sets the "acp_session_id" field.
func (u *CodingTaskUpsertBulk) SetAcpSessionID(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetAcpSessionID(v)
	})
}

// UpdateAcpSessionID sets the "acp_session_id" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateAcpSessionID() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateAcpSessionID()
	})
}

// SetSummary sets the "summary" field.
func (u *CodingTaskUpsertBulk) SetSummary(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateSummary() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateSummary()
	})
}

// SetError sets the "error" field.
func (u *CodingTaskUpsertBulk) SetError(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateError() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateError()
	})
}

// SetProgressCount sets the "progress_count" field.
func (u *CodingTaskUpsertBulk) SetProgressCount(v int) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetProgressCount(v)
	})
}

// AddProgressCount adds v to the "progress_count" field.
func (u *CodingTaskUpsertBulk) AddProgressCount(v int) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.AddProgressCount(v)
	})
}

// UpdateProgressCount sets the "progress_count" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateProgressCount() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateProgressCount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CodingTaskUpsertBulk) SetCreatedAt(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateCreatedAt() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CodingTaskUpsertBulk) SetUpdatedAt(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateUpdatedAt() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *CodingTaskUpsertBulk) SetCompletedAt(v string) *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *CodingTaskUpsertBulk) UpdateCompletedAt() *CodingTaskUpsertBulk {
	return u.Update(func(s *CodingTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// Exec executes the query.
func (u *CodingTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CodingTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CodingTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CodingTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
