// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/evalcase"
	"aranea-agents/internal/data/ent/evalcaseresult"
	"aranea-agents/internal/data/ent/evalrun"
	"aranea-agents/internal/data/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EvalCaseResultUpdate is the builder for updating EvalCaseResult entities.
type EvalCaseResultUpdate struct {
	config
	hooks    []Hook
	mutation *EvalCaseResultMutation
}

// Where appends a list predicates to the EvalCaseResultUpdate builder.
func (_u *EvalCaseResultUpdate) Where(ps ...predicate.EvalCaseResult) *EvalCaseResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *EvalCaseResultUpdate) SetRunID(v string) *EvalCaseResultUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableRunID(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetCaseID sets the "case_id" field.
func (_u *EvalCaseResultUpdate) SetCaseID(v string) *EvalCaseResultUpdate {
	_u.mutation.SetCaseID(v)
	return _u
}

// SetNillableCaseID sets the "case_id" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableCaseID(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetCaseID(*v)
	}
	return _u
}

// SetActualOutput sets the "actual_output" field.
func (_u *EvalCaseResultUpdate) SetActualOutput(v string) *EvalCaseResultUpdate {
	_u.mutation.SetActualOutput(v)
	return _u
}

// SetNillableActualOutput sets the "actual_output" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableActualOutput(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetActualOutput(*v)
	}
	return _u
}

// SetExactMatch sets the "exact_match" field.
func (_u *EvalCaseResultUpdate) SetExactMatch(v int) *EvalCaseResultUpdate {
	_u.mutation.ResetExactMatch()
	_u.mutation.SetExactMatch(v)
	return _u
}

// SetNillableExactMatch sets the "exact_match" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableExactMatch(v *int) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetExactMatch(*v)
	}
	return _u
}

// AddExactMatch adds value to the "exact_match" field.
func (_u *EvalCaseResultUpdate) AddExactMatch(v int) *EvalCaseResultUpdate {
	_u.mutation.AddExactMatch(v)
	return _u
}

// SetContainsMatch sets the "contains_match" field.
func (_u *EvalCaseResultUpdate) SetContainsMatch(v int) *EvalCaseResultUpdate {
	_u.mutation.ResetContainsMatch()
	_u.mutation.SetContainsMatch(v)
	return _u
}

// SetNillableContainsMatch sets the "contains_match" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableContainsMatch(v *int) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetContainsMatch(*v)
	}
	return _u
}

// AddContainsMatch adds value to the "contains_match" field.
func (_u *EvalCaseResultUpdate) AddContainsMatch(v int) *EvalCaseResultUpdate {
	_u.mutation.AddContainsMatch(v)
	return _u
}

// SetLlmJudgeScore sets the "llm_judge_score" field.
func (_u *EvalCaseResultUpdate) SetLlmJudgeScore(v float64) *EvalCaseResultUpdate {
	_u.mutation.ResetLlmJudgeScore()
	_u.mutation.SetLlmJudgeScore(v)
	return _u
}

// SetNillableLlmJudgeScore sets the "llm_judge_score" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableLlmJudgeScore(v *float64) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetLlmJudgeScore(*v)
	}
	return _u
}

// AddLlmJudgeScore adds value to the "llm_judge_score" field.
func (_u *EvalCaseResultUpdate) AddLlmJudgeScore(v float64) *EvalCaseResultUpdate {
	_u.mutation.AddLlmJudgeScore(v)
	return _u
}

// SetToolCallAccuracy sets the "tool_call_accuracy" field.
func (_u *EvalCaseResultUpdate) SetToolCallAccuracy(v float64) *EvalCaseResultUpdate {
	_u.mutation.ResetToolCallAccuracy()
	_u.mutation.SetToolCallAccuracy(v)
	return _u
}

// SetNillableToolCallAccuracy sets the "tool_call_accuracy" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableToolCallAccuracy(v *float64) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetToolCallAccuracy(*v)
	}
	return _u
}

// AddToolCallAccuracy adds value to the "tool_call_accuracy" field.
func (_u *EvalCaseResultUpdate) AddToolCallAccuracy(v float64) *EvalCaseResultUpdate {
	_u.mutation.AddToolCallAccuracy(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EvalCaseResultUpdate) SetErrorMessage(v string) *EvalCaseResultUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableErrorMessage(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EvalCaseResultUpdate) SetCreatedAt(v string) *EvalCaseResultUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableCreatedAt(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetHumanPass sets the "human_pass" field.
func (_u *EvalCaseResultUpdate) SetHumanPass(v int) *EvalCaseResultUpdate {
	_u.mutation.ResetHumanPass()
	_u.mutation.SetHumanPass(v)
	return _u
}

// SetNillableHumanPass sets the "human_pass" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableHumanPass(v *int) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetHumanPass(*v)
	}
	return _u
}

// AddHumanPass adds value to the "human_pass" field.
func (_u *EvalCaseResultUpdate) AddHumanPass(v int) *EvalCaseResultUpdate {
	_u.mutation.AddHumanPass(v)
	return _u
}

// ClearHumanPass clears the value of the "human_pass" field.
func (_u *EvalCaseResultUpdate) ClearHumanPass() *EvalCaseResultUpdate {
	_u.mutation.ClearHumanPass()
	return _u
}

// SetHumanScore sets the "human_score" field.
func (_u *EvalCaseResultUpdate) SetHumanScore(v float64) *EvalCaseResultUpdate {
	_u.mutation.ResetHumanScore()
	_u.mutation.SetHumanScore(v)
	return _u
}

// SetNillableHumanScore sets the "human_score" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableHumanScore(v *float64) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetHumanScore(*v)
	}
	return _u
}

// AddHumanScore adds value to the "human_score" field.
func (_u *EvalCaseResultUpdate) AddHumanScore(v float64) *EvalCaseResultUpdate {
	_u.mutation.AddHumanScore(v)
	return _u
}

// ClearHumanScore clears the value of the "human_score" field.
func (_u *EvalCaseResultUpdate) ClearHumanScore() *EvalCaseResultUpdate {
	_u.mutation.ClearHumanScore()
	return _u
}

// SetHumanComment sets the "human_comment" field.
func (_u *EvalCaseResultUpdate) SetHumanComment(v string) *EvalCaseResultUpdate {
	_u.mutation.SetHumanComment(v)
	return _u
}

// SetNillableHumanComment sets the "human_comment" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableHumanComment(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetHumanComment(*v)
	}
	return _u
}

// SetAnnotatedAt sets the "annotated_at" field.
func (_u *EvalCaseResultUpdate) SetAnnotatedAt(v string) *EvalCaseResultUpdate {
	_u.mutation.SetAnnotatedAt(v)
	return _u
}

// SetNillableAnnotatedAt sets the "annotated_at" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableAnnotatedAt(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetAnnotatedAt(*v)
	}
	return _u
}

// SetAnnotatedBy sets the "annotated_by" field.
func (_u *EvalCaseResultUpdate) SetAnnotatedBy(v string) *EvalCaseResultUpdate {
	_u.mutation.SetAnnotatedBy(v)
	return _u
}

// SetNillableAnnotatedBy sets the "annotated_by" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableAnnotatedBy(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetAnnotatedBy(*v)
	}
	return _u
}

// SetScoresJSON sets the "scores_json" field.
func (_u *EvalCaseResultUpdate) SetScoresJSON(v string) *EvalCaseResultUpdate {
	_u.mutation.SetScoresJSON(v)
	return _u
}

// SetNillableScoresJSON sets the "scores_json" field if the given value is not nil.
func (_u *EvalCaseResultUpdate) SetNillableScoresJSON(v *string) *EvalCaseResultUpdate {
	if v != nil {
		_u.SetScoresJSON(*v)
	}
	return _u
}

// SetRun sets the "run" edge to the EvalRun entity.
func (_u *EvalCaseResultUpdate) SetRun(v *EvalRun) *EvalCaseResultUpdate {
	return _u.SetRunID(v.ID)
}

// SetCase sets the "case" edge to the EvalCase entity.
func (_u *EvalCaseResultUpdate) SetCase(v *EvalCase) *EvalCaseResultUpdate {
	return _u.SetCaseID(v.ID)
}

// Mutation returns the EvalCaseResultMutation object of the builder.
func (_u *EvalCaseResultUpdate) Mutation() *EvalCaseResultMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the EvalRun entity.
func (_u *EvalCaseResultUpdate) ClearRun() *EvalCaseResultUpdate {
	_u.mutation.ClearRun()
	return _u
}

// ClearCase clears the "case" edge to the EvalCase entity.
func (_u *EvalCaseResultUpdate) ClearCase() *EvalCaseResultUpdate {
	_u.mutation.ClearCase()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvalCaseResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvalCaseResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvalCaseResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvalCaseResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvalCaseResultUpdate) check() error {
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvalCaseResult.run"`)
	}
	if _u.mutation.CaseCleared() && len(_u.mutation.CaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvalCaseResult.case"`)
	}
	return nil
}

func (_u *EvalCaseResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evalcaseresult.Table, evalcaseresult.Columns, sqlgraph.NewFieldSpec(evalcaseresult.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualOutput(); ok {
		_spec.SetField(evalcaseresult.FieldActualOutput, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExactMatch(); ok {
		_spec.SetField(evalcaseresult.FieldExactMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExactMatch(); ok {
		_spec.AddField(evalcaseresult.FieldExactMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContainsMatch(); ok {
		_spec.SetField(evalcaseresult.FieldContainsMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContainsMatch(); ok {
		_spec.AddField(evalcaseresult.FieldContainsMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LlmJudgeScore(); ok {
		_spec.SetField(evalcaseresult.FieldLlmJudgeScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLlmJudgeScore(); ok {
		_spec.AddField(evalcaseresult.FieldLlmJudgeScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ToolCallAccuracy(); ok {
		_spec.SetField(evalcaseresult.FieldToolCallAccuracy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedToolCallAccuracy(); ok {
		_spec.AddField(evalcaseresult.FieldToolCallAccuracy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(evalcaseresult.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(evalcaseresult.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.HumanPass(); ok {
		_spec.SetField(evalcaseresult.FieldHumanPass, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHumanPass(); ok {
		_spec.AddField(evalcaseresult.FieldHumanPass, field.TypeInt, value)
	}
	if _u.mutation.HumanPassCleared() {
		_spec.ClearField(evalcaseresult.FieldHumanPass, field.TypeInt)
	}
	if value, ok := _u.mutation.HumanScore(); ok {
		_spec.SetField(evalcaseresult.FieldHumanScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHumanScore(); ok {
		_spec.AddField(evalcaseresult.FieldHumanScore, field.TypeFloat64, value)
	}
	if _u.mutation.HumanScoreCleared() {
		_spec.ClearField(evalcaseresult.FieldHumanScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.HumanComment(); ok {
		_spec.SetField(evalcaseresult.FieldHumanComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnotatedAt(); ok {
		_spec.SetField(evalcaseresult.FieldAnnotatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnotatedBy(); ok {
		_spec.SetField(evalcaseresult.FieldAnnotatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoresJSON(); ok {
		_spec.SetField(evalcaseresult.FieldScoresJSON, field.TypeString, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.RunTable,
			Columns: []string{evalcaseresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.RunTable,
			Columns: []string{evalcaseresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.CaseTable,
			Columns: []string{evalcaseresult.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalcase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.CaseTable,
			Columns: []string{evalcaseresult.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalcase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evalcaseresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvalCaseResultUpdateOne is the builder for updating a single EvalCaseResult entity.
type EvalCaseResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvalCaseResultMutation
}

// SetRunID sets the "run_id" field.
func (_u *EvalCaseResultUpdateOne) SetRunID(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableRunID(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetCaseID sets the "case_id" field.
func (_u *EvalCaseResultUpdateOne) SetCaseID(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetCaseID(v)
	return _u
}

// SetNillableCaseID sets the "case_id" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableCaseID(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetCaseID(*v)
	}
	return _u
}

// SetActualOutput sets the "actual_output" field.
func (_u *EvalCaseResultUpdateOne) SetActualOutput(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetActualOutput(v)
	return _u
}

// SetNillableActualOutput sets the "actual_output" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableActualOutput(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetActualOutput(*v)
	}
	return _u
}

// SetExactMatch sets the "exact_match" field.
func (_u *EvalCaseResultUpdateOne) SetExactMatch(v int) *EvalCaseResultUpdateOne {
	_u.mutation.ResetExactMatch()
	_u.mutation.SetExactMatch(v)
	return _u
}

// SetNillableExactMatch sets the "exact_match" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableExactMatch(v *int) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetExactMatch(*v)
	}
	return _u
}

// AddExactMatch adds value to the "exact_match" field.
func (_u *EvalCaseResultUpdateOne) AddExactMatch(v int) *EvalCaseResultUpdateOne {
	_u.mutation.AddExactMatch(v)
	return _u
}

// SetContainsMatch sets the "contains_match" field.
func (_u *EvalCaseResultUpdateOne) SetContainsMatch(v int) *EvalCaseResultUpdateOne {
	_u.mutation.ResetContainsMatch()
	_u.mutation.SetContainsMatch(v)
	return _u
}

// SetNillableContainsMatch sets the "contains_match" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableContainsMatch(v *int) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetContainsMatch(*v)
	}
	return _u
}

// AddContainsMatch adds value to the "contains_match" field.
func (_u *EvalCaseResultUpdateOne) AddContainsMatch(v int) *EvalCaseResultUpdateOne {
	_u.mutation.AddContainsMatch(v)
	return _u
}

// SetLlmJudgeScore sets the "llm_judge_score" field.
func (_u *EvalCaseResultUpdateOne) SetLlmJudgeScore(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.ResetLlmJudgeScore()
	_u.mutation.SetLlmJudgeScore(v)
	return _u
}

// SetNillableLlmJudgeScore sets the "llm_judge_score" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableLlmJudgeScore(v *float64) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetLlmJudgeScore(*v)
	}
	return _u
}

// AddLlmJudgeScore adds value to the "llm_judge_score" field.
func (_u *EvalCaseResultUpdateOne) AddLlmJudgeScore(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.AddLlmJudgeScore(v)
	return _u
}

// SetToolCallAccuracy sets the "tool_call_accuracy" field.
func (_u *EvalCaseResultUpdateOne) SetToolCallAccuracy(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.ResetToolCallAccuracy()
	_u.mutation.SetToolCallAccuracy(v)
	return _u
}

// SetNillableToolCallAccuracy sets the "tool_call_accuracy" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableToolCallAccuracy(v *float64) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetToolCallAccuracy(*v)
	}
	return _u
}

// AddToolCallAccuracy adds value to the "tool_call_accuracy" field.
func (_u *EvalCaseResultUpdateOne) AddToolCallAccuracy(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.AddToolCallAccuracy(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *EvalCaseResultUpdateOne) SetErrorMessage(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableErrorMessage(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EvalCaseResultUpdateOne) SetCreatedAt(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableCreatedAt(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetHumanPass sets the "human_pass" field.
func (_u *EvalCaseResultUpdateOne) SetHumanPass(v int) *EvalCaseResultUpdateOne {
	_u.mutation.ResetHumanPass()
	_u.mutation.SetHumanPass(v)
	return _u
}

// SetNillableHumanPass sets the "human_pass" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableHumanPass(v *int) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetHumanPass(*v)
	}
	return _u
}

// AddHumanPass adds value to the "human_pass" field.
func (_u *EvalCaseResultUpdateOne) AddHumanPass(v int) *EvalCaseResultUpdateOne {
	_u.mutation.AddHumanPass(v)
	return _u
}

// ClearHumanPass clears the value of the "human_pass" field.
func (_u *EvalCaseResultUpdateOne) ClearHumanPass() *EvalCaseResultUpdateOne {
	_u.mutation.ClearHumanPass()
	return _u
}

// SetHumanScore sets the "human_score" field.
func (_u *EvalCaseResultUpdateOne) SetHumanScore(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.ResetHumanScore()
	_u.mutation.SetHumanScore(v)
	return _u
}

// SetNillableHumanScore sets the "human_score" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableHumanScore(v *float64) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetHumanScore(*v)
	}
	return _u
}

// AddHumanScore adds value to the "human_score" field.
func (_u *EvalCaseResultUpdateOne) AddHumanScore(v float64) *EvalCaseResultUpdateOne {
	_u.mutation.AddHumanScore(v)
	return _u
}

// ClearHumanScore clears the value of the "human_score" field.
func (_u *EvalCaseResultUpdateOne) ClearHumanScore() *EvalCaseResultUpdateOne {
	_u.mutation.ClearHumanScore()
	return _u
}

// SetHumanComment sets the "human_comment" field.
func (_u *EvalCaseResultUpdateOne) SetHumanComment(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetHumanComment(v)
	return _u
}

// SetNillableHumanComment sets the "human_comment" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableHumanComment(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetHumanComment(*v)
	}
	return _u
}

// SetAnnotatedAt sets the "annotated_at" field.
func (_u *EvalCaseResultUpdateOne) SetAnnotatedAt(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetAnnotatedAt(v)
	return _u
}

// SetNillableAnnotatedAt sets the "annotated_at" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableAnnotatedAt(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetAnnotatedAt(*v)
	}
	return _u
}

// SetAnnotatedBy sets the "annotated_by" field.
func (_u *EvalCaseResultUpdateOne) SetAnnotatedBy(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetAnnotatedBy(v)
	return _u
}

// SetNillableAnnotatedBy sets the "annotated_by" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableAnnotatedBy(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetAnnotatedBy(*v)
	}
	return _u
}

// SetScoresJSON sets the "scores_json" field.
func (_u *EvalCaseResultUpdateOne) SetScoresJSON(v string) *EvalCaseResultUpdateOne {
	_u.mutation.SetScoresJSON(v)
	return _u
}

// SetNillableScoresJSON sets the "scores_json" field if the given value is not nil.
func (_u *EvalCaseResultUpdateOne) SetNillableScoresJSON(v *string) *EvalCaseResultUpdateOne {
	if v != nil {
		_u.SetScoresJSON(*v)
	}
	return _u
}

// SetRun sets the "run" edge to the EvalRun entity.
func (_u *EvalCaseResultUpdateOne) SetRun(v *EvalRun) *EvalCaseResultUpdateOne {
	return _u.SetRunID(v.ID)
}

// SetCase sets the "case" edge to the EvalCase entity.
func (_u *EvalCaseResultUpdateOne) SetCase(v *EvalCase) *EvalCaseResultUpdateOne {
	return _u.SetCaseID(v.ID)
}

// Mutation returns the EvalCaseResultMutation object of the builder.
func (_u *EvalCaseResultUpdateOne) Mutation() *EvalCaseResultMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the EvalRun entity.
func (_u *EvalCaseResultUpdateOne) ClearRun() *EvalCaseResultUpdateOne {
	_u.mutation.ClearRun()
	return _u
}

// ClearCase clears the "case" edge to the EvalCase entity.
func (_u *EvalCaseResultUpdateOne) ClearCase() *EvalCaseResultUpdateOne {
	_u.mutation.ClearCase()
	return _u
}

// Where appends a list predicates to the EvalCaseResultUpdate builder.
func (_u *EvalCaseResultUpdateOne) Where(ps ...predicate.EvalCaseResult) *EvalCaseResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvalCaseResultUpdateOne) Select(field string, fields ...string) *EvalCaseResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvalCaseResult entity.
func (_u *EvalCaseResultUpdateOne) Save(ctx context.Context) (*EvalCaseResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvalCaseResultUpdateOne) SaveX(ctx context.Context) *EvalCaseResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvalCaseResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvalCaseResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvalCaseResultUpdateOne) check() error {
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvalCaseResult.run"`)
	}
	if _u.mutation.CaseCleared() && len(_u.mutation.CaseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EvalCaseResult.case"`)
	}
	return nil
}

func (_u *EvalCaseResultUpdateOne) sqlSave(ctx context.Context) (_node *EvalCaseResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evalcaseresult.Table, evalcaseresult.Columns, sqlgraph.NewFieldSpec(evalcaseresult.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EvalCaseResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evalcaseresult.FieldID)
		for _, f := range fields {
			if !evalcaseresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != evalcaseresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActualOutput(); ok {
		_spec.SetField(evalcaseresult.FieldActualOutput, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExactMatch(); ok {
		_spec.SetField(evalcaseresult.FieldExactMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExactMatch(); ok {
		_spec.AddField(evalcaseresult.FieldExactMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContainsMatch(); ok {
		_spec.SetField(evalcaseresult.FieldContainsMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContainsMatch(); ok {
		_spec.AddField(evalcaseresult.FieldContainsMatch, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LlmJudgeScore(); ok {
		_spec.SetField(evalcaseresult.FieldLlmJudgeScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLlmJudgeScore(); ok {
		_spec.AddField(evalcaseresult.FieldLlmJudgeScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ToolCallAccuracy(); ok {
		_spec.SetField(evalcaseresult.FieldToolCallAccuracy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedToolCallAccuracy(); ok {
		_spec.AddField(evalcaseresult.FieldToolCallAccuracy, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(evalcaseresult.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(evalcaseresult.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.HumanPass(); ok {
		_spec.SetField(evalcaseresult.FieldHumanPass, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHumanPass(); ok {
		_spec.AddField(evalcaseresult.FieldHumanPass, field.TypeInt, value)
	}
	if _u.mutation.HumanPassCleared() {
		_spec.ClearField(evalcaseresult.FieldHumanPass, field.TypeInt)
	}
	if value, ok := _u.mutation.HumanScore(); ok {
		_spec.SetField(evalcaseresult.FieldHumanScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHumanScore(); ok {
		_spec.AddField(evalcaseresult.FieldHumanScore, field.TypeFloat64, value)
	}
	if _u.mutation.HumanScoreCleared() {
		_spec.ClearField(evalcaseresult.FieldHumanScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.HumanComment(); ok {
		_spec.SetField(evalcaseresult.FieldHumanComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnotatedAt(); ok {
		_spec.SetField(evalcaseresult.FieldAnnotatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnotatedBy(); ok {
		_spec.SetField(evalcaseresult.FieldAnnotatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScoresJSON(); ok {
		_spec.SetField(evalcaseresult.FieldScoresJSON, field.TypeString, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.RunTable,
			Columns: []string{evalcaseresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.RunTable,
			Columns: []string{evalcaseresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CaseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.CaseTable,
			Columns: []string{evalcaseresult.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalcase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evalcaseresult.CaseTable,
			Columns: []string{evalcaseresult.CaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evalcase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EvalCaseResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evalcaseresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
