// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/gatewaywebhook"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayWebhookCreate is the builder for creating a GatewayWebhook entity.
type GatewayWebhookCreate struct {
	config
	mutation *GatewayWebhookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *GatewayWebhookCreate) SetName(v string) *GatewayWebhookCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *GatewayWebhookCreate) SetURL(v string) *GatewayWebhookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetEventTypesJSON sets the "event_types_json" field.
func (_c *GatewayWebhookCreate) SetEventTypesJSON(v string) *GatewayWebhookCreate {
	_c.mutation.SetEventTypesJSON(v)
	return _c
}

// SetNillableEventTypesJSON sets the "event_types_json" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableEventTypesJSON(v *string) *GatewayWebhookCreate {
	if v != nil {
		_c.SetEventTypesJSON(*v)
	}
	return _c
}

// SetSecret sets the "secret" field.
func (_c *GatewayWebhookCreate) SetSecret(v string) *GatewayWebhookCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableSecret(v *string) *GatewayWebhookCreate {
	if v != nil {
		_c.SetSecret(*v)
	}
	return _c
}

// SetHeadersJSON sets the "headers_json" field.
func (_c *GatewayWebhookCreate) SetHeadersJSON(v string) *GatewayWebhookCreate {
	_c.mutation.SetHeadersJSON(v)
	return _c
}

// SetNillableHeadersJSON sets the "headers_json" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableHeadersJSON(v *string) *GatewayWebhookCreate {
	if v != nil {
		_c.SetHeadersJSON(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *GatewayWebhookCreate) SetEnabled(v bool) *GatewayWebhookCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableEnabled(v *bool) *GatewayWebhookCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayWebhookCreate) SetCreatedAt(v string) *GatewayWebhookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableCreatedAt(v *string) *GatewayWebhookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GatewayWebhookCreate) SetUpdatedAt(v string) *GatewayWebhookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GatewayWebhookCreate) SetNillableUpdatedAt(v *string) *GatewayWebhookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GatewayWebhookCreate) SetID(v string) *GatewayWebhookCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GatewayWebhookMutation object of the builder.
func (_c *GatewayWebhookCreate) Mutation() *GatewayWebhookMutation {
	return _c.mutation
}

// Save creates the GatewayWebhook in the database.
func (_c *GatewayWebhookCreate) Save(ctx context.Context) (*GatewayWebhook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayWebhookCreate) SaveX(ctx context.Context) *GatewayWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayWebhookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayWebhookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayWebhookCreate) defaults() {
	if _, ok := _c.mutation.EventTypesJSON(); !ok {
		v := gatewaywebhook.DefaultEventTypesJSON
		_c.mutation.SetEventTypesJSON(v)
	}
	if _, ok := _c.mutation.Secret(); !ok {
		v := gatewaywebhook.DefaultSecret
		_c.mutation.SetSecret(v)
	}
	if _, ok := _c.mutation.HeadersJSON(); !ok {
		v := gatewaywebhook.DefaultHeadersJSON
		_c.mutation.SetHeadersJSON(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := gatewaywebhook.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewaywebhook.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gatewaywebhook.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayWebhookCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GatewayWebhook.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := gatewaywebhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GatewayWebhook.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "GatewayWebhook.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := gatewaywebhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "GatewayWebhook.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventTypesJSON(); !ok {
		return &ValidationError{Name: "event_types_json", err: errors.New(`ent: missing required field "GatewayWebhook.event_types_json"`)}
	}
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required field "GatewayWebhook.secret"`)}
	}
	if v, ok := _c.mutation.Secret(); ok {
		if err := gatewaywebhook.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "GatewayWebhook.secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeadersJSON(); !ok {
		return &ValidationError{Name: "headers_json", err: errors.New(`ent: missing required field "GatewayWebhook.headers_json"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "GatewayWebhook.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayWebhook.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GatewayWebhook.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := gatewaywebhook.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "GatewayWebhook.id": %w`, err)}
		}
	}
	return nil
}

func (_c *GatewayWebhookCreate) sqlSave(ctx context.Context) (*GatewayWebhook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GatewayWebhook.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayWebhookCreate) createSpec() (*GatewayWebhook, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayWebhook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewaywebhook.Table, sqlgraph.NewFieldSpec(gatewaywebhook.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(gatewaywebhook.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(gatewaywebhook.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.EventTypesJSON(); ok {
		_spec.SetField(gatewaywebhook.FieldEventTypesJSON, field.TypeString, value)
		_node.EventTypesJSON = value
	}
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(gatewaywebhook.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.HeadersJSON(); ok {
		_spec.SetField(gatewaywebhook.FieldHeadersJSON, field.TypeString, value)
		_node.HeadersJSON = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(gatewaywebhook.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewaywebhook.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaywebhook.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GatewayWebhook.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GatewayWebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *GatewayWebhookCreate) OnConflict(opts ...sql.ConflictOption) *GatewayWebhookUpsertOne {
	_c.conflict = opts
	return &GatewayWebhookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GatewayWebhookCreate) OnConflictColumns(columns ...string) *GatewayWebhookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GatewayWebhookUpsertOne{
		create: _c,
	}
}

type (
	// GatewayWebhookUpsertOne is the builder for "upsert"-ing
	//  one GatewayWebhook node.
	GatewayWebhookUpsertOne struct {
		create *GatewayWebhookCreate
	}

	// GatewayWebhookUpsert is the "OnConflict" setter.
	GatewayWebhookUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *GatewayWebhookUpsert) SetName(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateName() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *GatewayWebhookUpsert) SetURL(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateURL() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldURL)
	return u
}

// SetEventTypesJSON sets the "event_types_json" field.
func (u *GatewayWebhookUpsert) SetEventTypesJSON(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldEventTypesJSON, v)
	return u
}

// UpdateEventTypesJSON sets the "event_types_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateEventTypesJSON() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldEventTypesJSON)
	return u
}

// SetSecret sets the "secret" field.
func (u *GatewayWebhookUpsert) SetSecret(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldSecret, v)
	return u
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateSecret() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldSecret)
	return u
}

// SetHeadersJSON sets the "headers_json" field.
func (u *GatewayWebhookUpsert) SetHeadersJSON(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldHeadersJSON, v)
	return u
}

// UpdateHeadersJSON sets the "headers_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateHeadersJSON() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldHeadersJSON)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *GatewayWebhookUpsert) SetEnabled(v bool) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateEnabled() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldEnabled)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GatewayWebhookUpsert) SetCreatedAt(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateCreatedAt() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GatewayWebhookUpsert) SetUpdatedAt(v string) *GatewayWebhookUpsert {
	u.Set(gatewaywebhook.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsert) UpdateUpdatedAt() *GatewayWebhookUpsert {
	u.SetExcluded(gatewaywebhook.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gatewaywebhook.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GatewayWebhookUpsertOne) UpdateNewValues() *GatewayWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(gatewaywebhook.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GatewayWebhookUpsertOne) Ignore() *GatewayWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GatewayWebhookUpsertOne) DoNothing() *GatewayWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GatewayWebhookCreate.OnConflict
// documentation for more info.
func (u *GatewayWebhookUpsertOne) Update(set func(*GatewayWebhookUpsert)) *GatewayWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GatewayWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GatewayWebhookUpsertOne) SetName(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateName() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *GatewayWebhookUpsertOne) SetURL(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateURL() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateURL()
	})
}

// SetEventTypesJSON sets the "event_types_json" field.
func (u *GatewayWebhookUpsertOne) SetEventTypesJSON(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetEventTypesJSON(v)
	})
}

// UpdateEventTypesJSON sets the "event_types_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateEventTypesJSON() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateEventTypesJSON()
	})
}

// SetSecret sets the "secret" field.
func (u *GatewayWebhookUpsertOne) SetSecret(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateSecret() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateSecret()
	})
}

// SetHeadersJSON sets the "headers_json" field.
func (u *GatewayWebhookUpsertOne) SetHeadersJSON(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetHeadersJSON(v)
	})
}

// UpdateHeadersJSON sets the "headers_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateHeadersJSON() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateHeadersJSON()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GatewayWebhookUpsertOne) SetEnabled(v bool) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateEnabled() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GatewayWebhookUpsertOne) SetCreatedAt(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateCreatedAt() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GatewayWebhookUpsertOne) SetUpdatedAt(v string) *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsertOne) UpdateUpdatedAt() *GatewayWebhookUpsertOne {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GatewayWebhookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GatewayWebhookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GatewayWebhookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GatewayWebhookUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GatewayWebhookUpsertOne.ID is not supported by MySQL driver. Use GatewayWebhookUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GatewayWebhookUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GatewayWebhookCreateBulk is the builder for creating many GatewayWebhook entities in bulk.
type GatewayWebhookCreateBulk struct {
	config
	err      error
	builders []*GatewayWebhookCreate
	conflict []sql.ConflictOption
}

// Save creates the GatewayWebhook entities in the database.
func (_c *GatewayWebhookCreateBulk) Save(ctx context.Context) ([]*GatewayWebhook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayWebhook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayWebhookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayWebhookCreateBulk) SaveX(ctx context.Context) []*GatewayWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayWebhookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayWebhookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GatewayWebhook.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GatewayWebhookUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *GatewayWebhookCreateBulk) OnConflict(opts ...sql.ConflictOption) *GatewayWebhookUpsertBulk {
	_c.conflict = opts
	return &GatewayWebhookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GatewayWebhookCreateBulk) OnConflictColumns(columns ...string) *GatewayWebhookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GatewayWebhookUpsertBulk{
		create: _c,
	}
}

// GatewayWebhookUpsertBulk is the builder for "upsert"-ing
// a bulk of GatewayWebhook nodes.
type GatewayWebhookUpsertBulk struct {
	create *GatewayWebhookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gatewaywebhook.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GatewayWebhookUpsertBulk) UpdateNewValues() *GatewayWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(gatewaywebhook.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GatewayWebhook.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GatewayWebhookUpsertBulk) Ignore() *GatewayWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GatewayWebhookUpsertBulk) DoNothing() *GatewayWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GatewayWebhookCreateBulk.OnConflict
// documentation for more info.
func (u *GatewayWebhookUpsertBulk) Update(set func(*GatewayWebhookUpsert)) *GatewayWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GatewayWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *GatewayWebhookUpsertBulk) SetName(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateName() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *GatewayWebhookUpsertBulk) SetURL(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateURL() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateURL()
	})
}

// SetEventTypesJSON sets the "event_types_json" field.
func (u *GatewayWebhookUpsertBulk) SetEventTypesJSON(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetEventTypesJSON(v)
	})
}

// UpdateEventTypesJSON sets the "event_types_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateEventTypesJSON() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateEventTypesJSON()
	})
}

// SetSecret sets the "secret" field.
func (u *GatewayWebhookUpsertBulk) SetSecret(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateSecret() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateSecret()
	})
}

// SetHeadersJSON sets the "headers_json" field.
func (u *GatewayWebhookUpsertBulk) SetHeadersJSON(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetHeadersJSON(v)
	})
}

// UpdateHeadersJSON sets the "headers_json" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateHeadersJSON() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateHeadersJSON()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GatewayWebhookUpsertBulk) SetEnabled(v bool) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateEnabled() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GatewayWebhookUpsertBulk) SetCreatedAt(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateCreatedAt() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GatewayWebhookUpsertBulk) SetUpdatedAt(v string) *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GatewayWebhookUpsertBulk) UpdateUpdatedAt() *GatewayWebhookUpsertBulk {
	return u.Update(func(s *GatewayWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GatewayWebhookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GatewayWebhookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GatewayWebhookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GatewayWebhookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
