// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/membersessionv2"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MemberSessionV2 is the model entity for the MemberSessionV2 schema.
type MemberSessionV2 struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TeamRunID holds the value of the "team_run_id" field.
	TeamRunID string `json:"team_run_id,omitempty"`
	// TeamStageID holds the value of the "team_stage_id" field.
	TeamStageID string `json:"team_stage_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// member own session for lazy load
	SessionID string `json:"session_id,omitempty"`
	// SpiritSessionID holds the value of the "spirit_session_id" field.
	SpiritSessionID string `json:"spirit_session_id,omitempty"`
	// AgentKey holds the value of the "agent_key" field.
	AgentKey string `json:"agent_key,omitempty"`
	// AgentName holds the value of the "agent_name" field.
	AgentName string `json:"agent_name,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Seq holds the value of the "seq" field.
	Seq int64 `json:"seq,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// when member session started
	StartedAt time.Time `json:"started_at,omitempty"`
	// when member session finished (null if not finished)
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// error message if failed (empty if no error)
	Error        string `json:"error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberSessionV2) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case membersessionv2.FieldSeq, membersessionv2.FieldVersion:
			values[i] = new(sql.NullInt64)
		case membersessionv2.FieldID, membersessionv2.FieldTeamRunID, membersessionv2.FieldTeamStageID, membersessionv2.FieldTaskID, membersessionv2.FieldSessionID, membersessionv2.FieldSpiritSessionID, membersessionv2.FieldAgentKey, membersessionv2.FieldAgentName, membersessionv2.FieldAvatarURL, membersessionv2.FieldStatus, membersessionv2.FieldError:
			values[i] = new(sql.NullString)
		case membersessionv2.FieldStartedAt, membersessionv2.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberSessionV2 fields.
func (_m *MemberSessionV2) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case membersessionv2.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case membersessionv2.FieldTeamRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_run_id", values[i])
			} else if value.Valid {
				_m.TeamRunID = value.String
			}
		case membersessionv2.FieldTeamStageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_stage_id", values[i])
			} else if value.Valid {
				_m.TeamStageID = value.String
			}
		case membersessionv2.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case membersessionv2.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case membersessionv2.FieldSpiritSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spirit_session_id", values[i])
			} else if value.Valid {
				_m.SpiritSessionID = value.String
			}
		case membersessionv2.FieldAgentKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_key", values[i])
			} else if value.Valid {
				_m.AgentKey = value.String
			}
		case membersessionv2.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case membersessionv2.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case membersessionv2.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case membersessionv2.FieldSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seq", values[i])
			} else if value.Valid {
				_m.Seq = value.Int64
			}
		case membersessionv2.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case membersessionv2.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case membersessionv2.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case membersessionv2.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberSessionV2.
// This includes values selected through modifiers, order, etc.
func (_m *MemberSessionV2) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MemberSessionV2.
// Note that you need to call MemberSessionV2.Unwrap() before calling this method if this MemberSessionV2
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberSessionV2) Update() *MemberSessionV2UpdateOne {
	return NewMemberSessionV2Client(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberSessionV2 entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberSessionV2) Unwrap() *MemberSessionV2 {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberSessionV2 is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberSessionV2) String() string {
	var builder strings.Builder
	builder.WriteString("MemberSessionV2(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_run_id=")
	builder.WriteString(_m.TeamRunID)
	builder.WriteString(", ")
	builder.WriteString("team_stage_id=")
	builder.WriteString(_m.TeamStageID)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("spirit_session_id=")
	builder.WriteString(_m.SpiritSessionID)
	builder.WriteString(", ")
	builder.WriteString("agent_key=")
	builder.WriteString(_m.AgentKey)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.Seq))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// MemberSessionV2s is a parsable slice of MemberSessionV2.
type MemberSessionV2s []*MemberSessionV2
