// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aranea-agents/internal/data/ent/selfcheckreport"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SelfCheckReportCreate is the builder for creating a SelfCheckReport entity.
type SelfCheckReportCreate struct {
	config
	mutation *SelfCheckReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCheckResultsJSON sets the "check_results_json" field.
func (_c *SelfCheckReportCreate) SetCheckResultsJSON(v string) *SelfCheckReportCreate {
	_c.mutation.SetCheckResultsJSON(v)
	return _c
}

// SetNillableCheckResultsJSON sets the "check_results_json" field if the given value is not nil.
func (_c *SelfCheckReportCreate) SetNillableCheckResultsJSON(v *string) *SelfCheckReportCreate {
	if v != nil {
		_c.SetCheckResultsJSON(*v)
	}
	return _c
}

// SetOverallStatus sets the "overall_status" field.
func (_c *SelfCheckReportCreate) SetOverallStatus(v string) *SelfCheckReportCreate {
	_c.mutation.SetOverallStatus(v)
	return _c
}

// SetNillableOverallStatus sets the "overall_status" field if the given value is not nil.
func (_c *SelfCheckReportCreate) SetNillableOverallStatus(v *string) *SelfCheckReportCreate {
	if v != nil {
		_c.SetOverallStatus(*v)
	}
	return _c
}

// SetRepairActionsJSON sets the "repair_actions_json" field.
func (_c *SelfCheckReportCreate) SetRepairActionsJSON(v string) *SelfCheckReportCreate {
	_c.mutation.SetRepairActionsJSON(v)
	return _c
}

// SetNillableRepairActionsJSON sets the "repair_actions_json" field if the given value is not nil.
func (_c *SelfCheckReportCreate) SetNillableRepairActionsJSON(v *string) *SelfCheckReportCreate {
	if v != nil {
		_c.SetRepairActionsJSON(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SelfCheckReportCreate) SetStartedAt(v time.Time) *SelfCheckReportCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *SelfCheckReportCreate) SetFinishedAt(v time.Time) *SelfCheckReportCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *SelfCheckReportCreate) SetDurationMs(v int64) *SelfCheckReportCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *SelfCheckReportCreate) SetNillableDurationMs(v *int64) *SelfCheckReportCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SelfCheckReportCreate) SetCreatedAt(v time.Time) *SelfCheckReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SelfCheckReportCreate) SetID(v string) *SelfCheckReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SelfCheckReportMutation object of the builder.
func (_c *SelfCheckReportCreate) Mutation() *SelfCheckReportMutation {
	return _c.mutation
}

// Save creates the SelfCheckReport in the database.
func (_c *SelfCheckReportCreate) Save(ctx context.Context) (*SelfCheckReport, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SelfCheckReportCreate) SaveX(ctx context.Context) *SelfCheckReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelfCheckReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelfCheckReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SelfCheckReportCreate) defaults() {
	if _, ok := _c.mutation.CheckResultsJSON(); !ok {
		v := selfcheckreport.DefaultCheckResultsJSON
		_c.mutation.SetCheckResultsJSON(v)
	}
	if _, ok := _c.mutation.OverallStatus(); !ok {
		v := selfcheckreport.DefaultOverallStatus
		_c.mutation.SetOverallStatus(v)
	}
	if _, ok := _c.mutation.RepairActionsJSON(); !ok {
		v := selfcheckreport.DefaultRepairActionsJSON
		_c.mutation.SetRepairActionsJSON(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := selfcheckreport.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SelfCheckReportCreate) check() error {
	if _, ok := _c.mutation.CheckResultsJSON(); !ok {
		return &ValidationError{Name: "check_results_json", err: errors.New(`ent: missing required field "SelfCheckReport.check_results_json"`)}
	}
	if _, ok := _c.mutation.OverallStatus(); !ok {
		return &ValidationError{Name: "overall_status", err: errors.New(`ent: missing required field "SelfCheckReport.overall_status"`)}
	}
	if v, ok := _c.mutation.OverallStatus(); ok {
		if err := selfcheckreport.OverallStatusValidator(v); err != nil {
			return &ValidationError{Name: "overall_status", err: fmt.Errorf(`ent: validator failed for field "SelfCheckReport.overall_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepairActionsJSON(); !ok {
		return &ValidationError{Name: "repair_actions_json", err: errors.New(`ent: missing required field "SelfCheckReport.repair_actions_json"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SelfCheckReport.started_at"`)}
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		return &ValidationError{Name: "finished_at", err: errors.New(`ent: missing required field "SelfCheckReport.finished_at"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "SelfCheckReport.duration_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SelfCheckReport.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := selfcheckreport.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SelfCheckReport.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SelfCheckReportCreate) sqlSave(ctx context.Context) (*SelfCheckReport, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SelfCheckReport.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SelfCheckReportCreate) createSpec() (*SelfCheckReport, *sqlgraph.CreateSpec) {
	var (
		_node = &SelfCheckReport{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(selfcheckreport.Table, sqlgraph.NewFieldSpec(selfcheckreport.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CheckResultsJSON(); ok {
		_spec.SetField(selfcheckreport.FieldCheckResultsJSON, field.TypeString, value)
		_node.CheckResultsJSON = value
	}
	if value, ok := _c.mutation.OverallStatus(); ok {
		_spec.SetField(selfcheckreport.FieldOverallStatus, field.TypeString, value)
		_node.OverallStatus = value
	}
	if value, ok := _c.mutation.RepairActionsJSON(); ok {
		_spec.SetField(selfcheckreport.FieldRepairActionsJSON, field.TypeString, value)
		_node.RepairActionsJSON = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(selfcheckreport.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(selfcheckreport.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(selfcheckreport.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(selfcheckreport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SelfCheckReport.Create().
//		SetCheckResultsJSON(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SelfCheckReportUpsert) {
//			SetCheckResultsJSON(v+v).
//		}).
//		Exec(ctx)
func (_c *SelfCheckReportCreate) OnConflict(opts ...sql.ConflictOption) *SelfCheckReportUpsertOne {
	_c.conflict = opts
	return &SelfCheckReportUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SelfCheckReportCreate) OnConflictColumns(columns ...string) *SelfCheckReportUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SelfCheckReportUpsertOne{
		create: _c,
	}
}

type (
	// SelfCheckReportUpsertOne is the builder for "upsert"-ing
	//  one SelfCheckReport node.
	SelfCheckReportUpsertOne struct {
		create *SelfCheckReportCreate
	}

	// SelfCheckReportUpsert is the "OnConflict" setter.
	SelfCheckReportUpsert struct {
		*sql.UpdateSet
	}
)

// SetCheckResultsJSON sets the "check_results_json" field.
func (u *SelfCheckReportUpsert) SetCheckResultsJSON(v string) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldCheckResultsJSON, v)
	return u
}

// UpdateCheckResultsJSON sets the "check_results_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateCheckResultsJSON() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldCheckResultsJSON)
	return u
}

// SetOverallStatus sets the "overall_status" field.
func (u *SelfCheckReportUpsert) SetOverallStatus(v string) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldOverallStatus, v)
	return u
}

// UpdateOverallStatus sets the "overall_status" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateOverallStatus() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldOverallStatus)
	return u
}

// SetRepairActionsJSON sets the "repair_actions_json" field.
func (u *SelfCheckReportUpsert) SetRepairActionsJSON(v string) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldRepairActionsJSON, v)
	return u
}

// UpdateRepairActionsJSON sets the "repair_actions_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateRepairActionsJSON() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldRepairActionsJSON)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *SelfCheckReportUpsert) SetStartedAt(v time.Time) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateStartedAt() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *SelfCheckReportUpsert) SetFinishedAt(v time.Time) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateFinishedAt() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldFinishedAt)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *SelfCheckReportUpsert) SetDurationMs(v int64) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateDurationMs() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *SelfCheckReportUpsert) AddDurationMs(v int64) *SelfCheckReportUpsert {
	u.Add(selfcheckreport.FieldDurationMs, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SelfCheckReportUpsert) SetCreatedAt(v time.Time) *SelfCheckReportUpsert {
	u.Set(selfcheckreport.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsert) UpdateCreatedAt() *SelfCheckReportUpsert {
	u.SetExcluded(selfcheckreport.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(selfcheckreport.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SelfCheckReportUpsertOne) UpdateNewValues() *SelfCheckReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(selfcheckreport.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SelfCheckReportUpsertOne) Ignore() *SelfCheckReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SelfCheckReportUpsertOne) DoNothing() *SelfCheckReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SelfCheckReportCreate.OnConflict
// documentation for more info.
func (u *SelfCheckReportUpsertOne) Update(set func(*SelfCheckReportUpsert)) *SelfCheckReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SelfCheckReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheckResultsJSON sets the "check_results_json" field.
func (u *SelfCheckReportUpsertOne) SetCheckResultsJSON(v string) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetCheckResultsJSON(v)
	})
}

// UpdateCheckResultsJSON sets the "check_results_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateCheckResultsJSON() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateCheckResultsJSON()
	})
}

// SetOverallStatus sets the "overall_status" field.
func (u *SelfCheckReportUpsertOne) SetOverallStatus(v string) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetOverallStatus(v)
	})
}

// UpdateOverallStatus sets the "overall_status" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateOverallStatus() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateOverallStatus()
	})
}

// SetRepairActionsJSON sets the "repair_actions_json" field.
func (u *SelfCheckReportUpsertOne) SetRepairActionsJSON(v string) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetRepairActionsJSON(v)
	})
}

// UpdateRepairActionsJSON sets the "repair_actions_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateRepairActionsJSON() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateRepairActionsJSON()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SelfCheckReportUpsertOne) SetStartedAt(v time.Time) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateStartedAt() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *SelfCheckReportUpsertOne) SetFinishedAt(v time.Time) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateFinishedAt() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *SelfCheckReportUpsertOne) SetDurationMs(v int64) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *SelfCheckReportUpsertOne) AddDurationMs(v int64) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateDurationMs() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateDurationMs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SelfCheckReportUpsertOne) SetCreatedAt(v time.Time) *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertOne) UpdateCreatedAt() *SelfCheckReportUpsertOne {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SelfCheckReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SelfCheckReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SelfCheckReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SelfCheckReportUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SelfCheckReportUpsertOne.ID is not supported by MySQL driver. Use SelfCheckReportUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SelfCheckReportUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SelfCheckReportCreateBulk is the builder for creating many SelfCheckReport entities in bulk.
type SelfCheckReportCreateBulk struct {
	config
	err      error
	builders []*SelfCheckReportCreate
	conflict []sql.ConflictOption
}

// Save creates the SelfCheckReport entities in the database.
func (_c *SelfCheckReportCreateBulk) Save(ctx context.Context) ([]*SelfCheckReport, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SelfCheckReport, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SelfCheckReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SelfCheckReportCreateBulk) SaveX(ctx context.Context) []*SelfCheckReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelfCheckReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelfCheckReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SelfCheckReport.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SelfCheckReportUpsert) {
//			SetCheckResultsJSON(v+v).
//		}).
//		Exec(ctx)
func (_c *SelfCheckReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *SelfCheckReportUpsertBulk {
	_c.conflict = opts
	return &SelfCheckReportUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SelfCheckReportCreateBulk) OnConflictColumns(columns ...string) *SelfCheckReportUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SelfCheckReportUpsertBulk{
		create: _c,
	}
}

// SelfCheckReportUpsertBulk is the builder for "upsert"-ing
// a bulk of SelfCheckReport nodes.
type SelfCheckReportUpsertBulk struct {
	create *SelfCheckReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(selfcheckreport.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SelfCheckReportUpsertBulk) UpdateNewValues() *SelfCheckReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(selfcheckreport.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SelfCheckReport.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SelfCheckReportUpsertBulk) Ignore() *SelfCheckReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SelfCheckReportUpsertBulk) DoNothing() *SelfCheckReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SelfCheckReportCreateBulk.OnConflict
// documentation for more info.
func (u *SelfCheckReportUpsertBulk) Update(set func(*SelfCheckReportUpsert)) *SelfCheckReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SelfCheckReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetCheckResultsJSON sets the "check_results_json" field.
func (u *SelfCheckReportUpsertBulk) SetCheckResultsJSON(v string) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetCheckResultsJSON(v)
	})
}

// UpdateCheckResultsJSON sets the "check_results_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateCheckResultsJSON() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateCheckResultsJSON()
	})
}

// SetOverallStatus sets the "overall_status" field.
func (u *SelfCheckReportUpsertBulk) SetOverallStatus(v string) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetOverallStatus(v)
	})
}

// UpdateOverallStatus sets the "overall_status" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateOverallStatus() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateOverallStatus()
	})
}

// SetRepairActionsJSON sets the "repair_actions_json" field.
func (u *SelfCheckReportUpsertBulk) SetRepairActionsJSON(v string) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetRepairActionsJSON(v)
	})
}

// UpdateRepairActionsJSON sets the "repair_actions_json" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateRepairActionsJSON() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateRepairActionsJSON()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SelfCheckReportUpsertBulk) SetStartedAt(v time.Time) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateStartedAt() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *SelfCheckReportUpsertBulk) SetFinishedAt(v time.Time) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateFinishedAt() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateFinishedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *SelfCheckReportUpsertBulk) SetDurationMs(v int64) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *SelfCheckReportUpsertBulk) AddDurationMs(v int64) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateDurationMs() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateDurationMs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SelfCheckReportUpsertBulk) SetCreatedAt(v time.Time) *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SelfCheckReportUpsertBulk) UpdateCreatedAt() *SelfCheckReportUpsertBulk {
	return u.Update(func(s *SelfCheckReportUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SelfCheckReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SelfCheckReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SelfCheckReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SelfCheckReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
