// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: kratos/session/v1/session.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionService_SearchSessions_FullMethodName          = "/kratos.session.v1.SessionService/SearchSessions"
	SessionService_CreateSession_FullMethodName           = "/kratos.session.v1.SessionService/CreateSession"
	SessionService_DeleteSessionsByAgent_FullMethodName   = "/kratos.session.v1.SessionService/DeleteSessionsByAgent"
	SessionService_GetSession_FullMethodName              = "/kratos.session.v1.SessionService/GetSession"
	SessionService_UpdateSession_FullMethodName           = "/kratos.session.v1.SessionService/UpdateSession"
	SessionService_DeleteSession_FullMethodName           = "/kratos.session.v1.SessionService/DeleteSession"
	SessionService_ArchiveSession_FullMethodName          = "/kratos.session.v1.SessionService/ArchiveSession"
	SessionService_RestoreSession_FullMethodName          = "/kratos.session.v1.SessionService/RestoreSession"
	SessionService_PinSession_FullMethodName              = "/kratos.session.v1.SessionService/PinSession"
	SessionService_UnpinSession_FullMethodName            = "/kratos.session.v1.SessionService/UnpinSession"
	SessionService_ExportSession_FullMethodName           = "/kratos.session.v1.SessionService/ExportSession"
	SessionService_ListSessionRuns_FullMethodName         = "/kratos.session.v1.SessionService/ListSessionRuns"
	SessionService_ListSessionParticipants_FullMethodName = "/kratos.session.v1.SessionService/ListSessionParticipants"
	SessionService_GetSessionTimeline_FullMethodName      = "/kratos.session.v1.SessionService/GetSessionTimeline"
	SessionService_ListSessionMessages_FullMethodName     = "/kratos.session.v1.SessionService/ListSessionMessages"
	SessionService_SearchSessionMessages_FullMethodName   = "/kratos.session.v1.SessionService/SearchSessionMessages"
	SessionService_ListSessionTurns_FullMethodName        = "/kratos.session.v1.SessionService/ListSessionTurns"
	SessionService_BatchPreviewSessions_FullMethodName    = "/kratos.session.v1.SessionService/BatchPreviewSessions"
	SessionService_BatchArchiveSessions_FullMethodName    = "/kratos.session.v1.SessionService/BatchArchiveSessions"
	SessionService_BatchDeleteSessions_FullMethodName     = "/kratos.session.v1.SessionService/BatchDeleteSessions"
	SessionService_CompactSession_FullMethodName          = "/kratos.session.v1.SessionService/CompactSession"
	SessionService_GetCompressStatus_FullMethodName       = "/kratos.session.v1.SessionService/GetCompressStatus"
	SessionService_ListChildSessions_FullMethodName       = "/kratos.session.v1.SessionService/ListChildSessions"
	SessionService_GetSessionTree_FullMethodName          = "/kratos.session.v1.SessionService/GetSessionTree"
	SessionService_ListActivities_FullMethodName          = "/kratos.session.v1.SessionService/ListActivities"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	SearchSessions(ctx context.Context, in *SearchSessionsRequest, opts ...grpc.CallOption) (*SearchSessionsResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	DeleteSessionsByAgent(ctx context.Context, in *DeleteSessionsByAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ArchiveSession(ctx context.Context, in *ArchiveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*Session, error)
	PinSession(ctx context.Context, in *PinSessionRequest, opts ...grpc.CallOption) (*Session, error)
	UnpinSession(ctx context.Context, in *UnpinSessionRequest, opts ...grpc.CallOption) (*Session, error)
	ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionResponse, error)
	ListSessionRuns(ctx context.Context, in *ListSessionRunsRequest, opts ...grpc.CallOption) (*ListSessionRunsResponse, error)
	ListSessionParticipants(ctx context.Context, in *ListSessionParticipantsRequest, opts ...grpc.CallOption) (*ListSessionParticipantsResponse, error)
	GetSessionTimeline(ctx context.Context, in *GetSessionTimelineRequest, opts ...grpc.CallOption) (*SessionTimeline, error)
	ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error)
	SearchSessionMessages(ctx context.Context, in *SearchSessionMessagesRequest, opts ...grpc.CallOption) (*SearchSessionMessagesResponse, error)
	ListSessionTurns(ctx context.Context, in *ListSessionTurnsRequest, opts ...grpc.CallOption) (*ListSessionTurnsResponse, error)
	BatchPreviewSessions(ctx context.Context, in *BatchPreviewSessionsRequest, opts ...grpc.CallOption) (*BatchPreviewSessionsResponse, error)
	BatchArchiveSessions(ctx context.Context, in *BatchArchiveSessionsRequest, opts ...grpc.CallOption) (*BatchSessionsResponse, error)
	BatchDeleteSessions(ctx context.Context, in *BatchDeleteSessionsRequest, opts ...grpc.CallOption) (*BatchSessionsResponse, error)
	CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error)
	GetCompressStatus(ctx context.Context, in *GetCompressStatusRequest, opts ...grpc.CallOption) (*GetCompressStatusReply, error)
	// ListChildSessions returns child sessions of a parent session (session tree model).
	ListChildSessions(ctx context.Context, in *ListChildSessionsRequest, opts ...grpc.CallOption) (*ListChildSessionsResponse, error)
	// GetSessionTree returns the complete recursive session tree rooted at a spirit session.
	GetSessionTree(ctx context.Context, in *GetSessionTreeRequest, opts ...grpc.CallOption) (*GetSessionTreeResponse, error)
	// ListActivities returns activities for a session turn (Activity-First architecture).
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) SearchSessions(ctx context.Context, in *SearchSessionsRequest, opts ...grpc.CallOption) (*SearchSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_SearchSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) DeleteSessionsByAgent(ctx context.Context, in *DeleteSessionsByAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionService_DeleteSessionsByAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ArchiveSession(ctx context.Context, in *ArchiveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionService_ArchiveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) RestoreSession(ctx context.Context, in *RestoreSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_RestoreSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) PinSession(ctx context.Context, in *PinSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_PinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) UnpinSession(ctx context.Context, in *UnpinSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SessionService_UnpinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_ExportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListSessionRuns(ctx context.Context, in *ListSessionRunsRequest, opts ...grpc.CallOption) (*ListSessionRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionRunsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessionRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListSessionParticipants(ctx context.Context, in *ListSessionParticipantsRequest, opts ...grpc.CallOption) (*ListSessionParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionParticipantsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessionParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSessionTimeline(ctx context.Context, in *GetSessionTimelineRequest, opts ...grpc.CallOption) (*SessionTimeline, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionTimeline)
	err := c.cc.Invoke(ctx, SessionService_GetSessionTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionMessagesResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) SearchSessionMessages(ctx context.Context, in *SearchSessionMessagesRequest, opts ...grpc.CallOption) (*SearchSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSessionMessagesResponse)
	err := c.cc.Invoke(ctx, SessionService_SearchSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListSessionTurns(ctx context.Context, in *ListSessionTurnsRequest, opts ...grpc.CallOption) (*ListSessionTurnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionTurnsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListSessionTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) BatchPreviewSessions(ctx context.Context, in *BatchPreviewSessionsRequest, opts ...grpc.CallOption) (*BatchPreviewSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPreviewSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_BatchPreviewSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) BatchArchiveSessions(ctx context.Context, in *BatchArchiveSessionsRequest, opts ...grpc.CallOption) (*BatchSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_BatchArchiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) BatchDeleteSessions(ctx context.Context, in *BatchDeleteSessionsRequest, opts ...grpc.CallOption) (*BatchSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_BatchDeleteSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CompactSession(ctx context.Context, in *CompactSessionRequest, opts ...grpc.CallOption) (*CompactSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_CompactSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetCompressStatus(ctx context.Context, in *GetCompressStatusRequest, opts ...grpc.CallOption) (*GetCompressStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompressStatusReply)
	err := c.cc.Invoke(ctx, SessionService_GetCompressStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListChildSessions(ctx context.Context, in *ListChildSessionsRequest, opts ...grpc.CallOption) (*ListChildSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChildSessionsResponse)
	err := c.cc.Invoke(ctx, SessionService_ListChildSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetSessionTree(ctx context.Context, in *GetSessionTreeRequest, opts ...grpc.CallOption) (*GetSessionTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTreeResponse)
	err := c.cc.Invoke(ctx, SessionService_GetSessionTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, SessionService_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
type SessionServiceServer interface {
	SearchSessions(context.Context, *SearchSessionsRequest) (*SearchSessionsResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	DeleteSessionsByAgent(context.Context, *DeleteSessionsByAgentRequest) (*emptypb.Empty, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error)
	ArchiveSession(context.Context, *ArchiveSessionRequest) (*emptypb.Empty, error)
	RestoreSession(context.Context, *RestoreSessionRequest) (*Session, error)
	PinSession(context.Context, *PinSessionRequest) (*Session, error)
	UnpinSession(context.Context, *UnpinSessionRequest) (*Session, error)
	ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionResponse, error)
	ListSessionRuns(context.Context, *ListSessionRunsRequest) (*ListSessionRunsResponse, error)
	ListSessionParticipants(context.Context, *ListSessionParticipantsRequest) (*ListSessionParticipantsResponse, error)
	GetSessionTimeline(context.Context, *GetSessionTimelineRequest) (*SessionTimeline, error)
	ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error)
	SearchSessionMessages(context.Context, *SearchSessionMessagesRequest) (*SearchSessionMessagesResponse, error)
	ListSessionTurns(context.Context, *ListSessionTurnsRequest) (*ListSessionTurnsResponse, error)
	BatchPreviewSessions(context.Context, *BatchPreviewSessionsRequest) (*BatchPreviewSessionsResponse, error)
	BatchArchiveSessions(context.Context, *BatchArchiveSessionsRequest) (*BatchSessionsResponse, error)
	BatchDeleteSessions(context.Context, *BatchDeleteSessionsRequest) (*BatchSessionsResponse, error)
	CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error)
	GetCompressStatus(context.Context, *GetCompressStatusRequest) (*GetCompressStatusReply, error)
	// ListChildSessions returns child sessions of a parent session (session tree model).
	ListChildSessions(context.Context, *ListChildSessionsRequest) (*ListChildSessionsResponse, error)
	// GetSessionTree returns the complete recursive session tree rooted at a spirit session.
	GetSessionTree(context.Context, *GetSessionTreeRequest) (*GetSessionTreeResponse, error)
	// ListActivities returns activities for a session turn (Activity-First architecture).
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) SearchSessions(context.Context, *SearchSessionsRequest) (*SearchSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSessions not implemented")
}
func (UnimplementedSessionServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionServiceServer) DeleteSessionsByAgent(context.Context, *DeleteSessionsByAgentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSessionsByAgent not implemented")
}
func (UnimplementedSessionServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedSessionServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedSessionServiceServer) ArchiveSession(context.Context, *ArchiveSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveSession not implemented")
}
func (UnimplementedSessionServiceServer) RestoreSession(context.Context, *RestoreSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSession not implemented")
}
func (UnimplementedSessionServiceServer) PinSession(context.Context, *PinSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method PinSession not implemented")
}
func (UnimplementedSessionServiceServer) UnpinSession(context.Context, *UnpinSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpinSession not implemented")
}
func (UnimplementedSessionServiceServer) ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSession not implemented")
}
func (UnimplementedSessionServiceServer) ListSessionRuns(context.Context, *ListSessionRunsRequest) (*ListSessionRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionRuns not implemented")
}
func (UnimplementedSessionServiceServer) ListSessionParticipants(context.Context, *ListSessionParticipantsRequest) (*ListSessionParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionParticipants not implemented")
}
func (UnimplementedSessionServiceServer) GetSessionTimeline(context.Context, *GetSessionTimelineRequest) (*SessionTimeline, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionTimeline not implemented")
}
func (UnimplementedSessionServiceServer) ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionMessages not implemented")
}
func (UnimplementedSessionServiceServer) SearchSessionMessages(context.Context, *SearchSessionMessagesRequest) (*SearchSessionMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSessionMessages not implemented")
}
func (UnimplementedSessionServiceServer) ListSessionTurns(context.Context, *ListSessionTurnsRequest) (*ListSessionTurnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionTurns not implemented")
}
func (UnimplementedSessionServiceServer) BatchPreviewSessions(context.Context, *BatchPreviewSessionsRequest) (*BatchPreviewSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPreviewSessions not implemented")
}
func (UnimplementedSessionServiceServer) BatchArchiveSessions(context.Context, *BatchArchiveSessionsRequest) (*BatchSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchArchiveSessions not implemented")
}
func (UnimplementedSessionServiceServer) BatchDeleteSessions(context.Context, *BatchDeleteSessionsRequest) (*BatchSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteSessions not implemented")
}
func (UnimplementedSessionServiceServer) CompactSession(context.Context, *CompactSessionRequest) (*CompactSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompactSession not implemented")
}
func (UnimplementedSessionServiceServer) GetCompressStatus(context.Context, *GetCompressStatusRequest) (*GetCompressStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompressStatus not implemented")
}
func (UnimplementedSessionServiceServer) ListChildSessions(context.Context, *ListChildSessionsRequest) (*ListChildSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChildSessions not implemented")
}
func (UnimplementedSessionServiceServer) GetSessionTree(context.Context, *GetSessionTreeRequest) (*GetSessionTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionTree not implemented")
}
func (UnimplementedSessionServiceServer) ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_SearchSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SearchSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_SearchSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SearchSessions(ctx, req.(*SearchSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_DeleteSessionsByAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionsByAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).DeleteSessionsByAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_DeleteSessionsByAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).DeleteSessionsByAgent(ctx, req.(*DeleteSessionsByAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ArchiveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ArchiveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ArchiveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ArchiveSession(ctx, req.(*ArchiveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_RestoreSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).RestoreSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_RestoreSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).RestoreSession(ctx, req.(*RestoreSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_PinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).PinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_PinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).PinSession(ctx, req.(*PinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_UnpinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).UnpinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_UnpinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).UnpinSession(ctx, req.(*UnpinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ExportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ExportSession(ctx, req.(*ExportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListSessionRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessionRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessionRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessionRuns(ctx, req.(*ListSessionRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListSessionParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessionParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessionParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessionParticipants(ctx, req.(*ListSessionParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSessionTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSessionTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSessionTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSessionTimeline(ctx, req.(*GetSessionTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessionMessages(ctx, req.(*ListSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_SearchSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SearchSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_SearchSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SearchSessionMessages(ctx, req.(*SearchSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListSessionTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListSessionTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListSessionTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListSessionTurns(ctx, req.(*ListSessionTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_BatchPreviewSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPreviewSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).BatchPreviewSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_BatchPreviewSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).BatchPreviewSessions(ctx, req.(*BatchPreviewSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_BatchArchiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchArchiveSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).BatchArchiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_BatchArchiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).BatchArchiveSessions(ctx, req.(*BatchArchiveSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_BatchDeleteSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).BatchDeleteSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_BatchDeleteSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).BatchDeleteSessions(ctx, req.(*BatchDeleteSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CompactSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CompactSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CompactSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CompactSession(ctx, req.(*CompactSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetCompressStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompressStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetCompressStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetCompressStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetCompressStatus(ctx, req.(*GetCompressStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListChildSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListChildSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListChildSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListChildSessions(ctx, req.(*ListChildSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetSessionTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetSessionTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_GetSessionTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetSessionTree(ctx, req.(*GetSessionTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kratos.session.v1.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSessions",
			Handler:    _SessionService_SearchSessions_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _SessionService_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSessionsByAgent",
			Handler:    _SessionService_DeleteSessionsByAgent_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _SessionService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionService_DeleteSession_Handler,
		},
		{
			MethodName: "ArchiveSession",
			Handler:    _SessionService_ArchiveSession_Handler,
		},
		{
			MethodName: "RestoreSession",
			Handler:    _SessionService_RestoreSession_Handler,
		},
		{
			MethodName: "PinSession",
			Handler:    _SessionService_PinSession_Handler,
		},
		{
			MethodName: "UnpinSession",
			Handler:    _SessionService_UnpinSession_Handler,
		},
		{
			MethodName: "ExportSession",
			Handler:    _SessionService_ExportSession_Handler,
		},
		{
			MethodName: "ListSessionRuns",
			Handler:    _SessionService_ListSessionRuns_Handler,
		},
		{
			MethodName: "ListSessionParticipants",
			Handler:    _SessionService_ListSessionParticipants_Handler,
		},
		{
			MethodName: "GetSessionTimeline",
			Handler:    _SessionService_GetSessionTimeline_Handler,
		},
		{
			MethodName: "ListSessionMessages",
			Handler:    _SessionService_ListSessionMessages_Handler,
		},
		{
			MethodName: "SearchSessionMessages",
			Handler:    _SessionService_SearchSessionMessages_Handler,
		},
		{
			MethodName: "ListSessionTurns",
			Handler:    _SessionService_ListSessionTurns_Handler,
		},
		{
			MethodName: "BatchPreviewSessions",
			Handler:    _SessionService_BatchPreviewSessions_Handler,
		},
		{
			MethodName: "BatchArchiveSessions",
			Handler:    _SessionService_BatchArchiveSessions_Handler,
		},
		{
			MethodName: "BatchDeleteSessions",
			Handler:    _SessionService_BatchDeleteSessions_Handler,
		},
		{
			MethodName: "CompactSession",
			Handler:    _SessionService_CompactSession_Handler,
		},
		{
			MethodName: "GetCompressStatus",
			Handler:    _SessionService_GetCompressStatus_Handler,
		},
		{
			MethodName: "ListChildSessions",
			Handler:    _SessionService_ListChildSessions_Handler,
		},
		{
			MethodName: "GetSessionTree",
			Handler:    _SessionService_GetSessionTree_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _SessionService_ListActivities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kratos/session/v1/session.proto",
}

const (
	SessionV2Service_ListTasks_FullMethodName          = "/kratos.session.v1.SessionV2Service/ListTasks"
	SessionV2Service_ListTurns_FullMethodName          = "/kratos.session.v1.SessionV2Service/ListTurns"
	SessionV2Service_ListSteps_FullMethodName          = "/kratos.session.v1.SessionV2Service/ListSteps"
	SessionV2Service_GetStep_FullMethodName            = "/kratos.session.v1.SessionV2Service/GetStep"
	SessionV2Service_ListTeamStages_FullMethodName     = "/kratos.session.v1.SessionV2Service/ListTeamStages"
	SessionV2Service_ListTeamRuns_FullMethodName       = "/kratos.session.v1.SessionV2Service/ListTeamRuns"
	SessionV2Service_ListMemberSessions_FullMethodName = "/kratos.session.v1.SessionV2Service/ListMemberSessions"
	SessionV2Service_ListPlanBoards_FullMethodName     = "/kratos.session.v1.SessionV2Service/ListPlanBoards"
	SessionV2Service_ListPlanSteps_FullMethodName      = "/kratos.session.v1.SessionV2Service/ListPlanSteps"
	SessionV2Service_ListGraphStages_FullMethodName    = "/kratos.session.v1.SessionV2Service/ListGraphStages"
	SessionV2Service_ListGraphNodes_FullMethodName     = "/kratos.session.v1.SessionV2Service/ListGraphNodes"
)

// SessionV2ServiceClient is the client API for SessionV2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionV2Service exposes v2 entity read RPCs (Task/Turn/Step) backed by the
// v2 repo tables (tasks_v2/turns_v2/steps_v2). Replaces v1 ListActivities.
type SessionV2ServiceClient interface {
	// ListTasks lists tasks for a session.
	ListTasks(ctx context.Context, in *ListTasksV2Request, opts ...grpc.CallOption) (*ListTasksV2Response, error)
	// ListTurns lists turns for a task.
	ListTurns(ctx context.Context, in *ListTurnsV2Request, opts ...grpc.CallOption) (*ListTurnsV2Response, error)
	// ListSteps lists steps for a turn, task, or session.
	ListSteps(ctx context.Context, in *ListStepsV2Request, opts ...grpc.CallOption) (*ListStepsV2Response, error)
	// GetStep returns a single step by ID (replaces v1 GetActivity for confirm).
	GetStep(ctx context.Context, in *GetStepV2Request, opts ...grpc.CallOption) (*GetStepV2Response, error)
	// === 2026-07-04 问题 6 修复：补齐 7 个 v2 entity 的 REST API ===
	// 刷新页面后前端 fetchSessionHistory 需要重建完整活动树（Plan/Graph/Team/Member），
	// 原先只有 Task/Turn/Step 三个端点，其余 7 类实体无 REST API → 刷新后全部丢失。
	ListTeamStages(ctx context.Context, in *ListTeamStagesV2Request, opts ...grpc.CallOption) (*ListTeamStagesV2Response, error)
	ListTeamRuns(ctx context.Context, in *ListTeamRunsV2Request, opts ...grpc.CallOption) (*ListTeamRunsV2Response, error)
	ListMemberSessions(ctx context.Context, in *ListMemberSessionsV2Request, opts ...grpc.CallOption) (*ListMemberSessionsV2Response, error)
	ListPlanBoards(ctx context.Context, in *ListPlanBoardsV2Request, opts ...grpc.CallOption) (*ListPlanBoardsV2Response, error)
	ListPlanSteps(ctx context.Context, in *ListPlanStepsV2Request, opts ...grpc.CallOption) (*ListPlanStepsV2Response, error)
	ListGraphStages(ctx context.Context, in *ListGraphStagesV2Request, opts ...grpc.CallOption) (*ListGraphStagesV2Response, error)
	ListGraphNodes(ctx context.Context, in *ListGraphNodesV2Request, opts ...grpc.CallOption) (*ListGraphNodesV2Response, error)
}

type sessionV2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionV2ServiceClient(cc grpc.ClientConnInterface) SessionV2ServiceClient {
	return &sessionV2ServiceClient{cc}
}

func (c *sessionV2ServiceClient) ListTasks(ctx context.Context, in *ListTasksV2Request, opts ...grpc.CallOption) (*ListTasksV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListTurns(ctx context.Context, in *ListTurnsV2Request, opts ...grpc.CallOption) (*ListTurnsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTurnsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListSteps(ctx context.Context, in *ListStepsV2Request, opts ...grpc.CallOption) (*ListStepsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStepsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) GetStep(ctx context.Context, in *GetStepV2Request, opts ...grpc.CallOption) (*GetStepV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStepV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_GetStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListTeamStages(ctx context.Context, in *ListTeamStagesV2Request, opts ...grpc.CallOption) (*ListTeamStagesV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamStagesV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListTeamStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListTeamRuns(ctx context.Context, in *ListTeamRunsV2Request, opts ...grpc.CallOption) (*ListTeamRunsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeamRunsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListTeamRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListMemberSessions(ctx context.Context, in *ListMemberSessionsV2Request, opts ...grpc.CallOption) (*ListMemberSessionsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberSessionsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListMemberSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListPlanBoards(ctx context.Context, in *ListPlanBoardsV2Request, opts ...grpc.CallOption) (*ListPlanBoardsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlanBoardsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListPlanBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListPlanSteps(ctx context.Context, in *ListPlanStepsV2Request, opts ...grpc.CallOption) (*ListPlanStepsV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlanStepsV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListPlanSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListGraphStages(ctx context.Context, in *ListGraphStagesV2Request, opts ...grpc.CallOption) (*ListGraphStagesV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGraphStagesV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListGraphStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionV2ServiceClient) ListGraphNodes(ctx context.Context, in *ListGraphNodesV2Request, opts ...grpc.CallOption) (*ListGraphNodesV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGraphNodesV2Response)
	err := c.cc.Invoke(ctx, SessionV2Service_ListGraphNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionV2ServiceServer is the server API for SessionV2Service service.
// All implementations must embed UnimplementedSessionV2ServiceServer
// for forward compatibility.
//
// SessionV2Service exposes v2 entity read RPCs (Task/Turn/Step) backed by the
// v2 repo tables (tasks_v2/turns_v2/steps_v2). Replaces v1 ListActivities.
type SessionV2ServiceServer interface {
	// ListTasks lists tasks for a session.
	ListTasks(context.Context, *ListTasksV2Request) (*ListTasksV2Response, error)
	// ListTurns lists turns for a task.
	ListTurns(context.Context, *ListTurnsV2Request) (*ListTurnsV2Response, error)
	// ListSteps lists steps for a turn, task, or session.
	ListSteps(context.Context, *ListStepsV2Request) (*ListStepsV2Response, error)
	// GetStep returns a single step by ID (replaces v1 GetActivity for confirm).
	GetStep(context.Context, *GetStepV2Request) (*GetStepV2Response, error)
	// === 2026-07-04 问题 6 修复：补齐 7 个 v2 entity 的 REST API ===
	// 刷新页面后前端 fetchSessionHistory 需要重建完整活动树（Plan/Graph/Team/Member），
	// 原先只有 Task/Turn/Step 三个端点，其余 7 类实体无 REST API → 刷新后全部丢失。
	ListTeamStages(context.Context, *ListTeamStagesV2Request) (*ListTeamStagesV2Response, error)
	ListTeamRuns(context.Context, *ListTeamRunsV2Request) (*ListTeamRunsV2Response, error)
	ListMemberSessions(context.Context, *ListMemberSessionsV2Request) (*ListMemberSessionsV2Response, error)
	ListPlanBoards(context.Context, *ListPlanBoardsV2Request) (*ListPlanBoardsV2Response, error)
	ListPlanSteps(context.Context, *ListPlanStepsV2Request) (*ListPlanStepsV2Response, error)
	ListGraphStages(context.Context, *ListGraphStagesV2Request) (*ListGraphStagesV2Response, error)
	ListGraphNodes(context.Context, *ListGraphNodesV2Request) (*ListGraphNodesV2Response, error)
	mustEmbedUnimplementedSessionV2ServiceServer()
}

// UnimplementedSessionV2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionV2ServiceServer struct{}

func (UnimplementedSessionV2ServiceServer) ListTasks(context.Context, *ListTasksV2Request) (*ListTasksV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListTurns(context.Context, *ListTurnsV2Request) (*ListTurnsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTurns not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListSteps(context.Context, *ListStepsV2Request) (*ListStepsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSteps not implemented")
}
func (UnimplementedSessionV2ServiceServer) GetStep(context.Context, *GetStepV2Request) (*GetStepV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStep not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListTeamStages(context.Context, *ListTeamStagesV2Request) (*ListTeamStagesV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamStages not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListTeamRuns(context.Context, *ListTeamRunsV2Request) (*ListTeamRunsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeamRuns not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListMemberSessions(context.Context, *ListMemberSessionsV2Request) (*ListMemberSessionsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberSessions not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListPlanBoards(context.Context, *ListPlanBoardsV2Request) (*ListPlanBoardsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlanBoards not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListPlanSteps(context.Context, *ListPlanStepsV2Request) (*ListPlanStepsV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlanSteps not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListGraphStages(context.Context, *ListGraphStagesV2Request) (*ListGraphStagesV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGraphStages not implemented")
}
func (UnimplementedSessionV2ServiceServer) ListGraphNodes(context.Context, *ListGraphNodesV2Request) (*ListGraphNodesV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGraphNodes not implemented")
}
func (UnimplementedSessionV2ServiceServer) mustEmbedUnimplementedSessionV2ServiceServer() {}
func (UnimplementedSessionV2ServiceServer) testEmbeddedByValue()                          {}

// UnsafeSessionV2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionV2ServiceServer will
// result in compilation errors.
type UnsafeSessionV2ServiceServer interface {
	mustEmbedUnimplementedSessionV2ServiceServer()
}

func RegisterSessionV2ServiceServer(s grpc.ServiceRegistrar, srv SessionV2ServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionV2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionV2Service_ServiceDesc, srv)
}

func _SessionV2Service_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListTasks(ctx, req.(*ListTasksV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTurnsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListTurns(ctx, req.(*ListTurnsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStepsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListSteps(ctx, req.(*ListStepsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_GetStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStepV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).GetStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_GetStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).GetStep(ctx, req.(*GetStepV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListTeamStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamStagesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListTeamStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListTeamStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListTeamStages(ctx, req.(*ListTeamStagesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListTeamRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeamRunsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListTeamRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListTeamRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListTeamRuns(ctx, req.(*ListTeamRunsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListMemberSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberSessionsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListMemberSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListMemberSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListMemberSessions(ctx, req.(*ListMemberSessionsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListPlanBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanBoardsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListPlanBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListPlanBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListPlanBoards(ctx, req.(*ListPlanBoardsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListPlanSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanStepsV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListPlanSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListPlanSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListPlanSteps(ctx, req.(*ListPlanStepsV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListGraphStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGraphStagesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListGraphStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListGraphStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListGraphStages(ctx, req.(*ListGraphStagesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionV2Service_ListGraphNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGraphNodesV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionV2ServiceServer).ListGraphNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionV2Service_ListGraphNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionV2ServiceServer).ListGraphNodes(ctx, req.(*ListGraphNodesV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionV2Service_ServiceDesc is the grpc.ServiceDesc for SessionV2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionV2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kratos.session.v1.SessionV2Service",
	HandlerType: (*SessionV2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _SessionV2Service_ListTasks_Handler,
		},
		{
			MethodName: "ListTurns",
			Handler:    _SessionV2Service_ListTurns_Handler,
		},
		{
			MethodName: "ListSteps",
			Handler:    _SessionV2Service_ListSteps_Handler,
		},
		{
			MethodName: "GetStep",
			Handler:    _SessionV2Service_GetStep_Handler,
		},
		{
			MethodName: "ListTeamStages",
			Handler:    _SessionV2Service_ListTeamStages_Handler,
		},
		{
			MethodName: "ListTeamRuns",
			Handler:    _SessionV2Service_ListTeamRuns_Handler,
		},
		{
			MethodName: "ListMemberSessions",
			Handler:    _SessionV2Service_ListMemberSessions_Handler,
		},
		{
			MethodName: "ListPlanBoards",
			Handler:    _SessionV2Service_ListPlanBoards_Handler,
		},
		{
			MethodName: "ListPlanSteps",
			Handler:    _SessionV2Service_ListPlanSteps_Handler,
		},
		{
			MethodName: "ListGraphStages",
			Handler:    _SessionV2Service_ListGraphStages_Handler,
		},
		{
			MethodName: "ListGraphNodes",
			Handler:    _SessionV2Service_ListGraphNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kratos/session/v1/session.proto",
}
