import psycopg2
conn = psycopg2.connect("postgres://postgres:Hangshan%40123@127.0.0.1:5432/aranea?sslmode=disable")
cur = conn.cursor()
print('--- facts scope distribution ---')
cur.execute("SELECT scope_type, scope_id, user_id, agent_id, COUNT(*) FROM memory_facts WHERE status='active' AND deleted_at='' GROUP BY 1,2,3,4 ORDER BY 5 DESC LIMIT 15")
for r in cur.fetchall(): print(r)
print('--- relations scope distribution ---')
cur.execute("SELECT scope_type, scope_id, relation_type, COUNT(*) FROM memory_relations WHERE status='active' AND deleted_at='' GROUP BY 1,2,3 ORDER BY 4 DESC LIMIT 15")
for r in cur.fetchall(): print(r)
print('--- entities scope distribution ---')
cur.execute("SELECT scope_type, scope_id, COUNT(*) FROM memory_entities WHERE status='active' AND deleted_at='' GROUP BY 1,2 ORDER BY 3 DESC LIMIT 10")
for r in cur.fetchall(): print(r)
print('--- conflicting facts ---')
cur.execute("SELECT scope_type, scope_id, agent_id, COUNT(*) FROM memory_facts WHERE status='active' AND deleted_at='' AND conflict_count > 0 GROUP BY 1,2,3")
for r in cur.fetchall(): print(r)
conn.close()
