import psycopg2
conn = psycopg2.connect(host='127.0.0.1', dbname='aranea', user='postgres', password='Hangshan@123')
cur = conn.cursor()
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='memory_episodes' ORDER BY ordinal_position")
print('episodes cols:', [r[0] for r in cur.fetchall()])
cur.execute('SELECT agent_id, consolidation_status, count(*) FROM memory_episodes GROUP BY 1,2')
print('episodes:', cur.fetchall())
cur.execute('SELECT count(*) FROM memory_l0_assembly_snapshots')
print('l0 snapshots:', cur.fetchone())
cur.execute('SELECT session_id, status, count(*) FROM memory_l1_tasks GROUP BY 1,2 ORDER BY 3 DESC LIMIT 8')
print('l1 tasks by session:', cur.fetchall())
conn.close()
