import psycopg2
SID = open('fts_smoke_session.txt').read().strip()
conn = psycopg2.connect(host='127.0.0.1', dbname='aranea', user='postgres', password='Hangshan@123')
cur = conn.cursor()
cur.execute("SELECT session_id, turn_id, kind, notice_type, status, left(content,100), started_at FROM steps_v2 WHERE turn_id='f6e072f3-9bfb-4dc7-87e7-836f7b4b7939' ORDER BY started_at")
print('steps of notice turn:')
for r in cur.fetchall(): print(' ', r)
cur.execute("SELECT id, session_id, status, created_at FROM turns_v2 WHERE id='f6e072f3-9bfb-4dc7-87e7-836f7b4b7939'")
print('turn:', cur.fetchall())
cur.execute("SELECT turn_id, kind, status, left(content,120), started_at FROM steps_v2 WHERE session_id=%s ORDER BY started_at", (SID,))
print('all steps of our session:')
for r in cur.fetchall(): print(' ', r)
conn.close()
