// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.1
// source: kratos/ecosystem/v1/ecosystem.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEcosystemServiceGetProduct = "/kratos.ecosystem.v1.EcosystemService/GetProduct"
const OperationEcosystemServiceInstallProduct = "/kratos.ecosystem.v1.EcosystemService/InstallProduct"
const OperationEcosystemServiceListProducts = "/kratos.ecosystem.v1.EcosystemService/ListProducts"
const OperationEcosystemServicePublishProduct = "/kratos.ecosystem.v1.EcosystemService/PublishProduct"
const OperationEcosystemServiceUninstallProduct = "/kratos.ecosystem.v1.EcosystemService/UninstallProduct"

type EcosystemServiceHTTPServer interface {
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	InstallProduct(context.Context, *InstallProductRequest) (*InstallResult, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	PublishProduct(context.Context, *PublishProductRequest) (*Product, error)
	UninstallProduct(context.Context, *UninstallProductRequest) (*emptypb.Empty, error)
}

func RegisterEcosystemServiceHTTPServer(s *http.Server, srv EcosystemServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/ecosystem/products", _EcosystemService_ListProducts0_HTTP_Handler(srv))
	r.GET("/v1/ecosystem/products/{id}", _EcosystemService_GetProduct0_HTTP_Handler(srv))
	r.POST("/v1/ecosystem/products", _EcosystemService_PublishProduct0_HTTP_Handler(srv))
	r.POST("/v1/ecosystem/products/{id}/install", _EcosystemService_InstallProduct0_HTTP_Handler(srv))
	r.DELETE("/v1/ecosystem/products/{id}/install", _EcosystemService_UninstallProduct0_HTTP_Handler(srv))
}

func _EcosystemService_ListProducts0_HTTP_Handler(srv EcosystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcosystemServiceListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _EcosystemService_GetProduct0_HTTP_Handler(srv EcosystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcosystemServiceGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Product)
		return ctx.Result(200, reply)
	}
}

func _EcosystemService_PublishProduct0_HTTP_Handler(srv EcosystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcosystemServicePublishProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishProduct(ctx, req.(*PublishProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Product)
		return ctx.Result(200, reply)
	}
}

func _EcosystemService_InstallProduct0_HTTP_Handler(srv EcosystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InstallProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcosystemServiceInstallProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InstallProduct(ctx, req.(*InstallProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InstallResult)
		return ctx.Result(200, reply)
	}
}

func _EcosystemService_UninstallProduct0_HTTP_Handler(srv EcosystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UninstallProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcosystemServiceUninstallProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UninstallProduct(ctx, req.(*UninstallProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type EcosystemServiceHTTPClient interface {
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *Product, err error)
	InstallProduct(ctx context.Context, req *InstallProductRequest, opts ...http.CallOption) (rsp *InstallResult, err error)
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsResponse, err error)
	PublishProduct(ctx context.Context, req *PublishProductRequest, opts ...http.CallOption) (rsp *Product, err error)
	UninstallProduct(ctx context.Context, req *UninstallProductRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type EcosystemServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEcosystemServiceHTTPClient(client *http.Client) EcosystemServiceHTTPClient {
	return &EcosystemServiceHTTPClientImpl{client}
}

func (c *EcosystemServiceHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*Product, error) {
	var out Product
	pattern := "/v1/ecosystem/products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEcosystemServiceGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EcosystemServiceHTTPClientImpl) InstallProduct(ctx context.Context, in *InstallProductRequest, opts ...http.CallOption) (*InstallResult, error) {
	var out InstallResult
	pattern := "/v1/ecosystem/products/{id}/install"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcosystemServiceInstallProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EcosystemServiceHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsResponse, error) {
	var out ListProductsResponse
	pattern := "/v1/ecosystem/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEcosystemServiceListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EcosystemServiceHTTPClientImpl) PublishProduct(ctx context.Context, in *PublishProductRequest, opts ...http.CallOption) (*Product, error) {
	var out Product
	pattern := "/v1/ecosystem/products"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcosystemServicePublishProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EcosystemServiceHTTPClientImpl) UninstallProduct(ctx context.Context, in *UninstallProductRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/ecosystem/products/{id}/install"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEcosystemServiceUninstallProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
