// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: kratos/learning_loop/v1/learning_loop.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{0}
}

func (x *Observation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Observation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Observation) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Observation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Observation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Observation) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Observation) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Frequency     int32                  `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Evidence      string                 `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	DetectedAt    string                 `protobuf:"bytes,9,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{1}
}

func (x *Pattern) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pattern) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Pattern) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Pattern) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pattern) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *Pattern) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Pattern) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *Pattern) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pattern) GetDetectedAt() string {
	if x != nil {
		return x.DetectedAt
	}
	return ""
}

type KnowledgeProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PatternId     string                 `protobuf:"bytes,3,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Kind          string                 `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ValidatedAt   string                 `protobuf:"bytes,8,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,9,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeProposal) Reset() {
	*x = KnowledgeProposal{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeProposal) ProtoMessage() {}

func (x *KnowledgeProposal) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeProposal.ProtoReflect.Descriptor instead.
func (*KnowledgeProposal) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{2}
}

func (x *KnowledgeProposal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeProposal) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KnowledgeProposal) GetPatternId() string {
	if x != nil {
		return x.PatternId
	}
	return ""
}

func (x *KnowledgeProposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeProposal) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeProposal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KnowledgeProposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KnowledgeProposal) GetValidatedAt() string {
	if x != nil {
		return x.ValidatedAt
	}
	return ""
}

func (x *KnowledgeProposal) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *KnowledgeProposal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KnowledgeProposal) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProposalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsRequest) Reset() {
	*x = ListProposalsRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsRequest) ProtoMessage() {}

func (x *ListProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsRequest.ProtoReflect.Descriptor instead.
func (*ListProposalsRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{3}
}

func (x *ListProposalsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListProposalsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProposalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeProposal   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsResponse) Reset() {
	*x = ListProposalsResponse{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsResponse) ProtoMessage() {}

func (x *ListProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsResponse.ProtoReflect.Descriptor instead.
func (*ListProposalsResponse) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{4}
}

func (x *ListProposalsResponse) GetItems() []*KnowledgeProposal {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatternsRequest) Reset() {
	*x = ListPatternsRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatternsRequest) ProtoMessage() {}

func (x *ListPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatternsRequest.ProtoReflect.Descriptor instead.
func (*ListPatternsRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{5}
}

func (x *ListPatternsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListPatternsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListPatternsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Pattern             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatternsResponse) Reset() {
	*x = ListPatternsResponse{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatternsResponse) ProtoMessage() {}

func (x *ListPatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatternsResponse.ProtoReflect.Descriptor instead.
func (*ListPatternsResponse) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{6}
}

func (x *ListPatternsResponse) GetItems() []*Pattern {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListObservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Since         string                 `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObservationsRequest) Reset() {
	*x = ListObservationsRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObservationsRequest) ProtoMessage() {}

func (x *ListObservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObservationsRequest.ProtoReflect.Descriptor instead.
func (*ListObservationsRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{7}
}

func (x *ListObservationsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListObservationsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type ListObservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Observation         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObservationsResponse) Reset() {
	*x = ListObservationsResponse{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObservationsResponse) ProtoMessage() {}

func (x *ListObservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObservationsResponse.ProtoReflect.Descriptor instead.
func (*ListObservationsResponse) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{8}
}

func (x *ListObservationsResponse) GetItems() []*Observation {
	if x != nil {
		return x.Items
	}
	return nil
}

type ApproveProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveProposalRequest) Reset() {
	*x = ApproveProposalRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveProposalRequest) ProtoMessage() {}

func (x *ApproveProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveProposalRequest.ProtoReflect.Descriptor instead.
func (*ApproveProposalRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{9}
}

func (x *ApproveProposalRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ApproveProposalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectProposalRequest) Reset() {
	*x = RejectProposalRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectProposalRequest) ProtoMessage() {}

func (x *RejectProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectProposalRequest.ProtoReflect.Descriptor instead.
func (*RejectProposalRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{10}
}

func (x *RejectProposalRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RejectProposalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RunLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLoopRequest) Reset() {
	*x = RunLoopRequest{}
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLoopRequest) ProtoMessage() {}

func (x *RunLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kratos_learning_loop_v1_learning_loop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLoopRequest.ProtoReflect.Descriptor instead.
func (*RunLoopRequest) Descriptor() ([]byte, []int) {
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP(), []int{11}
}

func (x *RunLoopRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_kratos_learning_loop_v1_learning_loop_proto protoreflect.FileDescriptor

const file_kratos_learning_loop_v1_learning_loop_proto_rawDesc = "" +
	"\n" +
	"+kratos/learning_loop/v1/learning_loop.proto\x12\x17kratos.learning_loop.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc2\x01\n" +
	"\vObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12\x1f\n" +
	"\vobserved_at\x18\a \x01(\tR\n" +
	"observedAt\"\xfd\x01\n" +
	"\aPattern\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\x05R\tfrequency\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bevidence\x18\a \x01(\tR\bevidence\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1f\n" +
	"\vdetected_at\x18\t \x01(\tR\n" +
	"detectedAt\"\xbb\x02\n" +
	"\x11KnowledgeProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"pattern_id\x18\x03 \x01(\tR\tpatternId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fvalidated_at\x18\b \x01(\tR\vvalidatedAt\x12\x1f\n" +
	"\vapproved_by\x18\t \x01(\tR\n" +
	"approvedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"O\n" +
	"\x14ListProposalsRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"Y\n" +
	"\x15ListProposalsResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.kratos.learning_loop.v1.KnowledgeProposalR\x05items\"N\n" +
	"\x13ListPatternsRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x14ListPatternsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .kratos.learning_loop.v1.PatternR\x05items\"P\n" +
	"\x17ListObservationsRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId\x12\x14\n" +
	"\x05since\x18\x02 \x01(\tR\x05since\"V\n" +
	"\x18ListObservationsResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.kratos.learning_loop.v1.ObservationR\x05items\"O\n" +
	"\x16ApproveProposalRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId\x12\x14\n" +
	"\x02id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x02id\"N\n" +
	"\x15RejectProposalRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId\x12\x14\n" +
	"\x02id\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x02id\"1\n" +
	"\x0eRunLoopRequest\x12\x1f\n" +
	"\bagent_id\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aagentId2\xe4\a\n" +
	"\x13LearningLoopService\x12\xa0\x01\n" +
	"\rListProposals\x12-.kratos.learning_loop.v1.ListProposalsRequest\x1a..kratos.learning_loop.v1.ListProposalsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/agents/{agent_id}/learning/proposals\x12\x9c\x01\n" +
	"\fListPatterns\x12,.kratos.learning_loop.v1.ListPatternsRequest\x1a-.kratos.learning_loop.v1.ListPatternsResponse\"/\x82\xd3\xe4\x93\x02)\x12'/v1/agents/{agent_id}/learning/patterns\x12\xac\x01\n" +
	"\x10ListObservations\x120.kratos.learning_loop.v1.ListObservationsRequest\x1a1.kratos.learning_loop.v1.ListObservationsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/agents/{agent_id}/learning/observations\x12\xb0\x01\n" +
	"\x0fApproveProposal\x12/.kratos.learning_loop.v1.ApproveProposalRequest\x1a*.kratos.learning_loop.v1.KnowledgeProposal\"@\x82\xd3\xe4\x93\x02::\x01*\"5/v1/agents/{agent_id}/learning/proposals/{id}/approve\x12\xad\x01\n" +
	"\x0eRejectProposal\x12..kratos.learning_loop.v1.RejectProposalRequest\x1a*.kratos.learning_loop.v1.KnowledgeProposal\"?\x82\xd3\xe4\x93\x029:\x01*\"4/v1/agents/{agent_id}/learning/proposals/{id}/reject\x12y\n" +
	"\aRunLoop\x12'.kratos.learning_loop.v1.RunLoopRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/agents/{agent_id}/learning/runBM\n" +
	"\x1bapi.kratos.learning_loop.v1P\x01Z,aranea-agents/api/kratos/learning_loop/v1;v1b\x06proto3"

var (
	file_kratos_learning_loop_v1_learning_loop_proto_rawDescOnce sync.Once
	file_kratos_learning_loop_v1_learning_loop_proto_rawDescData []byte
)

func file_kratos_learning_loop_v1_learning_loop_proto_rawDescGZIP() []byte {
	file_kratos_learning_loop_v1_learning_loop_proto_rawDescOnce.Do(func() {
		file_kratos_learning_loop_v1_learning_loop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kratos_learning_loop_v1_learning_loop_proto_rawDesc), len(file_kratos_learning_loop_v1_learning_loop_proto_rawDesc)))
	})
	return file_kratos_learning_loop_v1_learning_loop_proto_rawDescData
}

var file_kratos_learning_loop_v1_learning_loop_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_kratos_learning_loop_v1_learning_loop_proto_goTypes = []any{
	(*Observation)(nil),              // 0: kratos.learning_loop.v1.Observation
	(*Pattern)(nil),                  // 1: kratos.learning_loop.v1.Pattern
	(*KnowledgeProposal)(nil),        // 2: kratos.learning_loop.v1.KnowledgeProposal
	(*ListProposalsRequest)(nil),     // 3: kratos.learning_loop.v1.ListProposalsRequest
	(*ListProposalsResponse)(nil),    // 4: kratos.learning_loop.v1.ListProposalsResponse
	(*ListPatternsRequest)(nil),      // 5: kratos.learning_loop.v1.ListPatternsRequest
	(*ListPatternsResponse)(nil),     // 6: kratos.learning_loop.v1.ListPatternsResponse
	(*ListObservationsRequest)(nil),  // 7: kratos.learning_loop.v1.ListObservationsRequest
	(*ListObservationsResponse)(nil), // 8: kratos.learning_loop.v1.ListObservationsResponse
	(*ApproveProposalRequest)(nil),   // 9: kratos.learning_loop.v1.ApproveProposalRequest
	(*RejectProposalRequest)(nil),    // 10: kratos.learning_loop.v1.RejectProposalRequest
	(*RunLoopRequest)(nil),           // 11: kratos.learning_loop.v1.RunLoopRequest
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_kratos_learning_loop_v1_learning_loop_proto_depIdxs = []int32{
	2,  // 0: kratos.learning_loop.v1.ListProposalsResponse.items:type_name -> kratos.learning_loop.v1.KnowledgeProposal
	1,  // 1: kratos.learning_loop.v1.ListPatternsResponse.items:type_name -> kratos.learning_loop.v1.Pattern
	0,  // 2: kratos.learning_loop.v1.ListObservationsResponse.items:type_name -> kratos.learning_loop.v1.Observation
	3,  // 3: kratos.learning_loop.v1.LearningLoopService.ListProposals:input_type -> kratos.learning_loop.v1.ListProposalsRequest
	5,  // 4: kratos.learning_loop.v1.LearningLoopService.ListPatterns:input_type -> kratos.learning_loop.v1.ListPatternsRequest
	7,  // 5: kratos.learning_loop.v1.LearningLoopService.ListObservations:input_type -> kratos.learning_loop.v1.ListObservationsRequest
	9,  // 6: kratos.learning_loop.v1.LearningLoopService.ApproveProposal:input_type -> kratos.learning_loop.v1.ApproveProposalRequest
	10, // 7: kratos.learning_loop.v1.LearningLoopService.RejectProposal:input_type -> kratos.learning_loop.v1.RejectProposalRequest
	11, // 8: kratos.learning_loop.v1.LearningLoopService.RunLoop:input_type -> kratos.learning_loop.v1.RunLoopRequest
	4,  // 9: kratos.learning_loop.v1.LearningLoopService.ListProposals:output_type -> kratos.learning_loop.v1.ListProposalsResponse
	6,  // 10: kratos.learning_loop.v1.LearningLoopService.ListPatterns:output_type -> kratos.learning_loop.v1.ListPatternsResponse
	8,  // 11: kratos.learning_loop.v1.LearningLoopService.ListObservations:output_type -> kratos.learning_loop.v1.ListObservationsResponse
	2,  // 12: kratos.learning_loop.v1.LearningLoopService.ApproveProposal:output_type -> kratos.learning_loop.v1.KnowledgeProposal
	2,  // 13: kratos.learning_loop.v1.LearningLoopService.RejectProposal:output_type -> kratos.learning_loop.v1.KnowledgeProposal
	12, // 14: kratos.learning_loop.v1.LearningLoopService.RunLoop:output_type -> google.protobuf.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kratos_learning_loop_v1_learning_loop_proto_init() }
func file_kratos_learning_loop_v1_learning_loop_proto_init() {
	if File_kratos_learning_loop_v1_learning_loop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kratos_learning_loop_v1_learning_loop_proto_rawDesc), len(file_kratos_learning_loop_v1_learning_loop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kratos_learning_loop_v1_learning_loop_proto_goTypes,
		DependencyIndexes: file_kratos_learning_loop_v1_learning_loop_proto_depIdxs,
		MessageInfos:      file_kratos_learning_loop_v1_learning_loop_proto_msgTypes,
	}.Build()
	File_kratos_learning_loop_v1_learning_loop_proto = out.File
	file_kratos_learning_loop_v1_learning_loop_proto_goTypes = nil
	file_kratos_learning_loop_v1_learning_loop_proto_depIdxs = nil
}
