// MOCK（骨架期）：M57 公网商城后端尚未实现，本文件提供演示数据驱动 UI 骨架。
// 后端就绪后删除本文件，api.ts 中对应函数替换为真实 RPC。
// 数据尽量贴近真实场景，便于验证信息密度与交互细节。
import type {
  CategoryNode,
  MarketAsset,
  MarketCreator,
  MyInstall,
  MyOrder,
  OrgPickNode,
  StudioAsset,
  StudioInboxItem,
  StudioStats,
} from './types';

// ── 三级分类树（对齐需求文档 §4.2 领域 → 子领域 → 场景） ──────────

function cat(path: string, children?: CategoryNode[]): CategoryNode {
  const label = path.split('/').pop() ?? path;
  return { key: path, label, children };
}

/** 一级分类图标（演示数据自带，组件不硬编码中文映射） */
function domain(path: string, icon: string, children?: CategoryNode[]): CategoryNode {
  return { ...cat(path, children), icon };
}

export const MOCK_CATEGORIES: CategoryNode[] = [
  domain('研发', 'code', [
    cat('研发/编程', [
      cat('研发/编程/代码生成'),
      cat('研发/编程/代码审查'),
      cat('研发/编程/单测生成'),
      cat('研发/编程/性能分析'),
    ]),
    cat('研发/DevOps', [
      cat('研发/DevOps/CI 编排'),
      cat('研发/DevOps/容器编排'),
      cat('研发/DevOps/监控告警'),
      cat('研发/DevOps/Runbook'),
    ]),
    cat('研发/数据工程', [cat('研发/数据工程/ETL 编排'), cat('研发/数据工程/数据质量'), cat('研发/数据工程/SQL 优化')]),
  ]),
  domain('办公', 'work_outline', [
    cat('办公/会议', [cat('办公/会议/纪要生成'), cat('办公/会议/待办抽取'), cat('办公/会议/多语翻译')]),
    cat('办公/文档', [cat('办公/文档/文档撰写'), cat('办公/文档/摘要'), cat('办公/文档/校对')]),
    cat('办公/协作', [cat('办公/协作/任务调度'), cat('办公/协作/周报生成'), cat('办公/协作/群机器人')]),
  ]),
  cat('客户', [
    cat('客户/客服', [cat('客户/客服/FAQ'), cat('客户/客服/工单分流'), cat('客户/客服/多语客服')]),
    cat('客户/销售', [cat('客户/销售/线索打分'), cat('客户/销售/销售助手'), cat('客户/销售/CRM 集成')]),
    cat('客户/营销', [cat('客户/营销/文案生成'), cat('客户/营销/选品分析'), cat('客户/营销/A/B 推荐')]),
  ]),
  domain('行业', 'domain', [
    cat('行业/法律', [cat('行业/法律/合同审阅'), cat('行业/法律/案例检索')]),
    cat('行业/医疗', [cat('行业/医疗/病历摘要'), cat('行业/医疗/用药咨询')]),
    cat('行业/金融', [cat('行业/金融/财报分析'), cat('行业/金融/风控辅助')]),
    cat('行业/教育', [cat('行业/教育/答疑助手'), cat('行业/教育/习题生成')]),
  ]),
  cat('内容', [
    cat('内容/创意', [cat('内容/创意/故事生成'), cat('内容/创意/角色扮演')]),
    cat('内容/多模态', [cat('内容/多模态/图文生成'), cat('内容/多模态/视频脚本'), cat('内容/多模态/字幕')]),
    cat('内容/翻译', [cat('内容/翻译/多语翻译'), cat('内容/翻译/本地化')]),
  ]),
  domain('其它', 'more_horiz', [cat('其它/实验性'), cat('其它/工具集合'), cat('其它/节日活动')]),
];

// ── 创作者 ─────────────────────────────────────────────────────

export const MOCK_CREATORS: MarketCreator[] = [
  {
    handle: 'aranea-official',
    name: 'Aranea 官方',
    verified: true,
    avatarColor: '#E9A23B',
    bio: 'Aranea 官方团队，维护平台级参考资产与最佳实践模板。',
    assetCount: 6,
    totalInstalls: 23840,
    avgRating: 4.8,
    followers: 3120,
  },
  {
    handle: 'devops-lab',
    name: 'DevOps 实验室',
    verified: true,
    avatarColor: '#4CAF7C',
    bio: '专注研发效能与云原生编排的资产工作室。',
    assetCount: 4,
    totalInstalls: 8210,
    avgRating: 4.6,
    followers: 980,
  },
  {
    handle: 'cx-studio',
    name: 'CX Studio',
    verified: true,
    avatarColor: '#A855F7',
    bio: '客户体验解决方案团队，电商/客服场景深耕者。',
    assetCount: 3,
    totalInstalls: 15300,
    avgRating: 4.9,
    followers: 2140,
  },
  {
    handle: 'linwei',
    name: '林蔚',
    verified: false,
    avatarColor: '#5E8BF0',
    bio: '独立开发者，喜欢把日常工作流沉淀成可复用资产。',
    assetCount: 2,
    totalInstalls: 1240,
    avgRating: 4.3,
    followers: 126,
  },
  {
    handle: 'data-craft',
    name: '数工匠',
    verified: false,
    avatarColor: '#E55C5C',
    bio: '数据工程与 BI 自动化小团队。',
    assetCount: 1,
    totalInstalls: 660,
    avgRating: 4.1,
    followers: 58,
  },
];

const creatorsByHandle = new Map(MOCK_CREATORS.map((c) => [c.handle, c]));

function creator(handle: string): MarketCreator {
  const c = creatorsByHandle.get(handle);
  if (!c) throw new Error(`mock creator missing: ${handle}`);
  return c;
}

// ── 资产（16 个，覆盖全部 11 类） ──────────────────────────────

export const MOCK_ASSETS: MarketAsset[] = [
  {
    id: 'skill.pr-description',
    slug: 'pr-description-generator',
    name: 'PR 描述生成器',
    type: 'skill',
    tagline: '根据 diff 自动生成结构化 PR 描述与风险点提示',
    description:
      '读取当前分支 diff，生成包含变更摘要、影响面、测试建议的 PR 描述，支持中英文双语输出，可配置团队模板。',
    readme:
      '## 能力\n\n- 解析 git diff，按模块聚合变更\n- 输出「摘要 / 影响面 / 测试建议 / 风险点」四段式描述\n- 支持自定义团队 PR 模板\n\n## 使用方式\n\n在任意 Agent 上启用本 Skill 后，对 Agent 说「帮我写 PR 描述」即可。\n\n## 权限说明\n\n只读本地 git 仓库，不访问网络。',
    creator: creator('aranea-official'),
    categories: ['研发/编程/代码审查'],
    tags: ['tool-use', 'github', 'zh'],
    version: '1.4.2',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.8,
    ratingCount: 326,
    ratingDist: [262, 44, 14, 4, 2],
    installCount: 8930,
    activity30d: 92.5,
    health7d: 99.2,
    permissions: [
      { kind: 'fs', value: 'read:.git', note: '读取本地 git 仓库 diff', risk: 'low' },
      { kind: 'model', value: 'invoke', note: '调用模型生成描述', risk: 'low' },
    ],
    screenshotCount: 2,
    deps: [],
    status: 'published',
    publishedAt: '2026-03-12',
    updatedAt: '2026-07-18',
    installed: true,
    versions: [
      { version: '1.4.2', date: '2026-07-18', note: '修复 monorepo 下 diff 解析错误' },
      { version: '1.4.0', date: '2026-06-20', note: '新增风险点检测' },
      { version: '1.3.0', date: '2026-05-11', note: '支持自定义 PR 模板' },
      { version: '1.0.0', date: '2026-03-12', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r1',
        author: '陈默',
        rating: 5,
        content: '接进团队流水线后，PR 描述质量明显提升，评审效率高了不少。模板配置很灵活。',
        createdAt: '2026-07-20',
        likes: 42,
        reply: {
          author: 'Aranea 官方',
          content: '感谢反馈！下个版本会支持 monorepo 子包级模板。',
          createdAt: '2026-07-21',
        },
      },
      {
        id: 'r2',
        author: 'Kira',
        rating: 4,
        content: '整体好用，希望支持 GitLab 的 MR 描述格式。',
        createdAt: '2026-07-08',
        likes: 15,
      },
      {
        id: 'r3',
        author: '阿澈',
        rating: 5,
        content: '风险点提示比想象中准，帮我们拦住过一次配置误删。',
        createdAt: '2026-06-28',
        likes: 23,
      },
    ],
  },
  {
    id: 'skill.sql-optimizer',
    slug: 'sql-optimizer',
    name: 'SQL 优化助手',
    type: 'skill',
    tagline: '慢 SQL 诊断、索引建议与执行计划解读',
    description: '输入慢查询或执行计划，输出索引建议、重写方案与风险提示，支持 PostgreSQL / MySQL 方言。',
    readme:
      '## 能力\n\n- 慢 SQL 诊断与改写建议\n- EXPLAIN 执行计划解读\n- 索引推荐（含覆盖索引）\n\n## 注意\n\n仅输出建议，不会自动执行任何 DDL。',
    creator: creator('data-craft'),
    categories: ['研发/数据工程/SQL 优化'],
    tags: ['text-gen', 'zh', 'en'],
    version: '0.9.1',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.1,
    ratingCount: 58,
    ratingDist: [30, 18, 7, 2, 1],
    installCount: 660,
    activity30d: 21.4,
    health7d: 96.8,
    permissions: [{ kind: 'model', value: 'invoke', risk: 'low' }],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-06-02',
    updatedAt: '2026-07-10',
    installed: false,
    versions: [
      { version: '0.9.1', date: '2026-07-10', note: '补充 MySQL 8 窗口函数改写规则' },
      { version: '0.9.0', date: '2026-06-02', note: '首个公开版本' },
    ],
    reviews: [
      {
        id: 'r4',
        author: '老张',
        rating: 4,
        content: '给出的索引建议靠谱，但执行计划解读部分对新手不够友好。',
        createdAt: '2026-07-12',
        likes: 6,
      },
    ],
  },
  {
    id: 'skill.weekly-report',
    slug: 'weekly-report',
    name: '周报生成器',
    type: 'skill',
    tagline: '汇总本周会话与任务产出，一键生成结构化周报',
    description: '自动聚合本周 Agent 会话、任务完成记录与文档产出，按「本周进展 / 下周计划 / 风险」生成周报。',
    readme: '## 能力\n\n- 聚合本周任务与产出\n- 多种周报模板（技术 / 运营 / 管理）\n- 支持导出 Markdown\n',
    creator: creator('linwei'),
    categories: ['办公/协作/周报生成'],
    tags: ['text-gen', 'scheduled', 'zh'],
    version: '1.1.0',
    compatibility: 'aranea>=1.5',
    priceModel: 'one_time',
    priceCents: 1200,
    rating: 4.3,
    ratingCount: 87,
    ratingDist: [48, 26, 9, 3, 1],
    installCount: 1240,
    activity30d: 45.2,
    health7d: 98.5,
    permissions: [
      { kind: 'fs', value: 'read:sessions', note: '读取本周会话与任务记录', risk: 'medium' },
      { kind: 'model', value: 'invoke', risk: 'low' },
    ],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-05-20',
    updatedAt: '2026-07-02',
    installed: false,
    versions: [
      { version: '1.1.0', date: '2026-07-02', note: '新增管理版模板' },
      { version: '1.0.0', date: '2026-05-20', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r5',
        author: 'Sandra',
        rating: 4,
        content: '每周五省了我半小时，管理版模板比技术版实用。',
        createdAt: '2026-07-05',
        likes: 11,
      },
    ],
  },
  {
    id: 'mcp.github',
    slug: 'github-mcp',
    name: 'GitHub MCP 连接器',
    type: 'mcp_server',
    tagline: 'Issue / PR / Actions 全量读写能力的官方 MCP Server',
    description:
      '封装 GitHub REST API 为 MCP 工具集：Issue 管理、PR 审查、Actions 触发与日志读取，凭据走本地 Credential 引用。',
    readme:
      '## 包含工具\n\n- `github.list_issues` / `github.create_issue`\n- `github.review_pr` / `github.merge_pr`\n- `github.trigger_action` / `github.read_logs`\n\n## 凭据\n\n安装后需在「凭据管理」中绑定 GitHub PAT（repo 权限）。',
    creator: creator('aranea-official'),
    categories: ['研发/编程/代码审查', '研发/DevOps/CI 编排'],
    tags: ['integration:github', 'tool-use'],
    version: '2.1.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.7,
    ratingCount: 412,
    ratingDist: [330, 58, 16, 6, 2],
    installCount: 7640,
    activity30d: 88.1,
    health7d: 99.6,
    permissions: [
      { kind: 'credential', value: 'github_pat', note: '读取你绑定的 GitHub 访问令牌', risk: 'high' },
      { kind: 'network', value: 'api.github.com', note: '访问 GitHub API', risk: 'medium' },
    ],
    screenshotCount: 2,
    deps: [],
    status: 'published',
    publishedAt: '2026-02-28',
    updatedAt: '2026-07-22',
    installed: true,
    versions: [
      { version: '2.1.0', date: '2026-07-22', note: '新增 Actions 日志流式读取' },
      { version: '2.0.0', date: '2026-06-01', note: '凭据迁移到 Credential 引用（破坏性变更）' },
      { version: '1.5.0', date: '2026-04-15', note: '支持 Draft PR' },
    ],
    reviews: [
      {
        id: 'r6',
        author: 'Yuki',
        rating: 5,
        content: '和 PR Review Team 搭配是绝配，凭据引用的方式也比直接填 token 安心。',
        createdAt: '2026-07-24',
        likes: 31,
      },
      {
        id: 'r7',
        author: 'Leo',
        rating: 4,
        content: '企业内网 GitHub EE 需要手动改 base URL，文档里写清楚就更好了。',
        createdAt: '2026-07-01',
        likes: 9,
      },
    ],
  },
  {
    id: 'mcp.notion',
    slug: 'notion-mcp',
    name: 'Notion MCP 连接器',
    type: 'mcp_server',
    tagline: '读写 Notion 页面与数据库，知识库双向同步',
    description: 'Notion 页面检索、内容读写、数据库查询工具集，适合把 Notion 作为团队知识中枢的场景。',
    readme: '## 包含工具\n\n- `notion.search` / `notion.read_page`\n- `notion.write_page` / `notion.query_db`\n',
    creator: creator('linwei'),
    categories: ['办公/文档/文档撰写'],
    tags: ['integration:notion', 'rag'],
    version: '1.0.3',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.0,
    ratingCount: 45,
    ratingDist: [20, 15, 7, 2, 1],
    installCount: 540,
    activity30d: 18.9,
    health7d: 95.4,
    permissions: [
      { kind: 'credential', value: 'notion_token', note: 'Notion integration token', risk: 'high' },
      { kind: 'network', value: 'api.notion.com', risk: 'medium' },
    ],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-06-15',
    updatedAt: '2026-07-08',
    installed: false,
    versions: [
      { version: '1.0.3', date: '2026-07-08', note: '修复分页 bug' },
      { version: '1.0.0', date: '2026-06-15', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r8',
        author: 'Momo',
        rating: 4,
        content: '基本够用，写入大页面时偶尔超时。',
        createdAt: '2026-07-09',
        likes: 3,
      },
    ],
  },
  {
    id: 'tool.web-search',
    slug: 'web-search-toolkit',
    name: 'Web 搜索工具包',
    type: 'tool',
    tagline: '多引擎搜索 + 网页正文抽取 + 结果去重',
    description: '聚合搜索（Bing / Google / 自建 Searx）+ 正文抽取 + 去重排序，为 Agent 提供干净的联网检索能力。',
    readme:
      '## 工具\n\n- `web.search`：多引擎聚合搜索\n- `web.fetch`：正文抽取（去广告/导航）\n- `web.dedupe`：结果去重合并\n',
    creator: creator('devops-lab'),
    categories: ['其它/工具集合'],
    tags: ['tool-use', 'rag'],
    version: '3.2.0',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.5,
    ratingCount: 203,
    ratingDist: [140, 42, 15, 4, 2],
    installCount: 5210,
    activity30d: 76.3,
    health7d: 98.9,
    permissions: [{ kind: 'network', value: '*', note: '访问搜索引擎与目标网页', risk: 'medium' }],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-03-30',
    updatedAt: '2026-07-15',
    installed: false,
    versions: [
      { version: '3.2.0', date: '2026-07-15', note: '新增 Searx 自建引擎支持' },
      { version: '3.0.0', date: '2026-05-20', note: '重写正文抽取管线' },
    ],
    reviews: [
      {
        id: 'r9',
        author: 'Kevin',
        rating: 5,
        content: '正文抽取质量比官方内置搜索好一截。',
        createdAt: '2026-07-16',
        likes: 18,
      },
    ],
  },
  {
    id: 'agent.code-reviewer',
    slug: 'code-reviewer-agent',
    name: '代码审查员 Agent 模板',
    type: 'agent',
    tagline: '预置审查清单与语气风格的 Code Review Agent',
    description: '内置安全 / 性能 / 可读性三层审查清单，输出按严重度分级的评审意见，预调温度与上下文策略，开箱即用。',
    readme:
      '## 预置配置\n\n- 系统提示词：资深工程师视角，分级输出（阻塞 / 建议 / 点赞）\n- 模型策略：推荐 medium 档及以上\n- 建议搭配：PR 描述生成器 Skill + GitHub MCP\n',
    creator: creator('aranea-official'),
    categories: ['研发/编程/代码审查'],
    tags: ['text-gen', 'tool-use', 'zh', 'en'],
    version: '1.2.0',
    compatibility: 'aranea>=1.5',
    priceModel: 'one_time',
    priceCents: 2900,
    rating: 4.6,
    ratingCount: 178,
    ratingDist: [125, 36, 12, 3, 2],
    installCount: 3980,
    activity30d: 64.7,
    health7d: 99.0,
    permissions: [{ kind: 'model', value: 'invoke', risk: 'low' }],
    screenshotCount: 2,
    deps: [
      { id: 'skill.pr-description', name: 'PR 描述生成器', range: '^1.0', kind: 'skill' },
      { id: 'mcp.github', name: 'GitHub MCP 连接器', range: '^2.0', kind: 'mcp_server' },
    ],
    status: 'published',
    publishedAt: '2026-04-10',
    updatedAt: '2026-07-11',
    installed: false,
    versions: [
      { version: '1.2.0', date: '2026-07-11', note: '审查清单 v3：新增并发安全类目' },
      { version: '1.1.0', date: '2026-05-25', note: '支持按语言切换审查重点' },
      { version: '1.0.0', date: '2026-04-10', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r10',
        author: 'Iris',
        rating: 5,
        content: '分级输出太重要了，团队终于不会在 nitpick 上浪费时间。',
        createdAt: '2026-07-14',
        likes: 26,
      },
      {
        id: 'r11',
        author: '大成',
        rating: 4,
        content: '对 Go 的审查质量明显好于 Python，希望继续补强。',
        createdAt: '2026-06-30',
        likes: 8,
      },
    ],
  },
  {
    id: 'agent.faq-bot',
    slug: 'faq-bot-agent',
    name: '客服问答 Agent',
    type: 'agent',
    tagline: '接入知识库即可上岗的 FAQ 客服，含转人工策略',
    description: '预置检索增强与拒答策略，命中知识库直接回答，低置信度自动转人工并生成工单摘要。',
    readme: '## 特性\n\n- 低置信度拒答 + 转人工话术\n- 工单摘要自动生成\n- 建议搭配：跨境电商 FAQ 知识包\n',
    creator: creator('cx-studio'),
    categories: ['客户/客服/FAQ'],
    tags: ['rag', 'text-gen', 'zh'],
    version: '2.0.1',
    compatibility: 'aranea>=1.6',
    priceModel: 'subscription',
    priceCents: 3900,
    rating: 4.9,
    ratingCount: 264,
    ratingDist: [238, 20, 4, 1, 1],
    installCount: 6850,
    activity30d: 95.8,
    health7d: 99.4,
    permissions: [
      { kind: 'model', value: 'invoke', risk: 'low' },
      { kind: 'tool', value: 'knowledge.search', note: '检索你绑定的知识库', risk: 'low' },
    ],
    screenshotCount: 2,
    deps: [{ id: 'knowledge.ecommerce-faq', name: '跨境电商 FAQ 知识包', range: '^1.0', kind: 'knowledge_pack' }],
    status: 'published',
    publishedAt: '2026-03-05',
    updatedAt: '2026-07-25',
    installed: false,
    versions: [
      { version: '2.0.1', date: '2026-07-25', note: '修复多轮上下文丢失问题' },
      { version: '2.0.0', date: '2026-06-18', note: '全新拒答策略，转人工率下降 40%' },
      { version: '1.3.0', date: '2026-04-22', note: '新增工单摘要' },
    ],
    reviews: [
      {
        id: 'r12',
        author: 'Elena',
        rating: 5,
        content: '转人工策略很实用，客户满意度反而比纯人工时更高。',
        createdAt: '2026-07-26',
        likes: 35,
        reply: { author: 'CX Studio', content: '谢谢认可！v2.1 会加入多语言转人工。', createdAt: '2026-07-27' },
      },
      {
        id: 'r13',
        author: '北岛',
        rating: 5,
        content: '知识包一挂就能用，部署最顺的一次。',
        createdAt: '2026-07-02',
        likes: 12,
      },
    ],
  },
  {
    id: 'team.pr-review',
    slug: 'pr-review-team',
    name: 'PR Review 流水线 Team',
    type: 'team',
    tagline: '描述生成 → 代码审查 → 汇总意见的三段式评审编排',
    description: '三段式编排：PR 描述生成器产出变更摘要，代码审查员分级评审，汇总成员输出最终意见并回写 GitHub。',
    readme:
      '## 编排结构\n\n1. **describe**：生成变更摘要\n2. **review**：分级评审（并行检查安全/性能/可读性）\n3. **summarize**：汇总并回写 PR 评论\n\n含完整失败重试与超时策略。',
    creator: creator('aranea-official'),
    categories: ['研发/编程/代码审查'],
    tags: ['tool-use', 'integration:github'],
    version: '1.4.2',
    compatibility: 'aranea>=1.6',
    priceModel: 'one_time',
    priceCents: 5900,
    rating: 4.7,
    ratingCount: 156,
    ratingDist: [118, 26, 8, 3, 1],
    installCount: 2870,
    activity30d: 71.2,
    health7d: 98.7,
    permissions: [
      { kind: 'model', value: 'invoke', risk: 'low' },
      { kind: 'network', value: 'api.github.com', risk: 'medium' },
      { kind: 'credential', value: 'github_pat', risk: 'high' },
    ],
    screenshotCount: 3,
    deps: [
      { id: 'agent.code-reviewer', name: '代码审查员 Agent 模板', range: '^1.2', kind: 'agent' },
      { id: 'skill.pr-description', name: 'PR 描述生成器', range: '^1.4', kind: 'skill' },
      { id: 'mcp.github', name: 'GitHub MCP 连接器', range: '^2.0', kind: 'mcp_server' },
    ],
    status: 'published',
    publishedAt: '2026-04-25',
    updatedAt: '2026-07-19',
    installed: false,
    versions: [
      { version: '1.4.2', date: '2026-07-19', note: '修复 summarize 阶段偶发空评论' },
      { version: '1.4.0', date: '2026-06-28', note: 'review 阶段支持并行' },
      { version: '1.0.0', date: '2026-04-25', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r14',
        author: 'Frank',
        rating: 5,
        content: '依赖一键装齐的体验很好，装完跑个 smoke 就直接进生产了。',
        createdAt: '2026-07-21',
        likes: 19,
      },
    ],
  },
  {
    id: 'team.support-triage',
    slug: 'support-triage-team',
    name: '客服分流 Team',
    type: 'team',
    tagline: '意图识别 → 专属客服 → 工单归档的多语言分流编排',
    description: '先识别客户意图与语言，再路由到对应品类客服 Agent，未解决会话自动归档为工单。',
    readme: '## 编排\n\n1. triage：意图 + 语言识别\n2. route：按品类路由\n3. archive：未解决自动建工单\n',
    creator: creator('cx-studio'),
    categories: ['客户/客服/工单分流'],
    tags: ['multimodal', 'zh', '多语'],
    version: '1.1.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'subscription',
    priceCents: 5900,
    rating: 4.4,
    ratingCount: 92,
    ratingDist: [55, 26, 8, 2, 1],
    installCount: 1760,
    activity30d: 52.6,
    health7d: 97.9,
    permissions: [{ kind: 'model', value: 'invoke', risk: 'low' }],
    screenshotCount: 2,
    deps: [{ id: 'agent.faq-bot', name: '客服问答 Agent', range: '^2.0', kind: 'agent' }],
    status: 'published',
    publishedAt: '2026-05-15',
    updatedAt: '2026-07-06',
    installed: false,
    versions: [
      { version: '1.1.0', date: '2026-07-06', note: '新增西班牙语路由' },
      { version: '1.0.0', date: '2026-05-15', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r15',
        author: 'Cici',
        rating: 4,
        content: '分流准确率不错，就是小语种偶尔误判。',
        createdAt: '2026-07-10',
        likes: 7,
      },
    ],
  },
  {
    id: 'channel.feishu-bot',
    slug: 'feishu-group-bot',
    name: '飞书群机器人 Channel 模板',
    type: 'channel_template',
    tagline: '飞书群消息收发 + 卡片回复 + @提醒的接入模板',
    description: '预置飞书开放平台接入配置：消息接收、卡片回复、群成员 @提醒，凭据由买家侧绑定。',
    readme:
      '## 配置项\n\n- App ID / App Secret（凭据引用）\n- 事件订阅：消息 / 群变更\n- 卡片模板：文本 / 进度 / 审批\n',
    creator: creator('devops-lab'),
    categories: ['办公/协作/群机器人'],
    tags: ['integration:feishu', 'zh'],
    version: '1.3.0',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.6,
    ratingCount: 188,
    ratingDist: [140, 32, 12, 3, 1],
    installCount: 4630,
    activity30d: 68.4,
    health7d: 99.1,
    permissions: [
      { kind: 'credential', value: 'feishu_app', note: '飞书应用凭据', risk: 'high' },
      { kind: 'network', value: 'open.feishu.cn', risk: 'medium' },
    ],
    screenshotCount: 2,
    deps: [],
    status: 'published',
    publishedAt: '2026-03-20',
    updatedAt: '2026-07-01',
    installed: true,
    versions: [
      { version: '1.3.0', date: '2026-07-01', note: '新增审批卡片模板' },
      { version: '1.0.0', date: '2026-03-20', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r16',
        author: 'Han',
        rating: 5,
        content: '十分钟接入飞书群，卡片模板很全。',
        createdAt: '2026-07-03',
        likes: 14,
      },
    ],
  },
  {
    id: 'knowledge.ecommerce-faq',
    slug: 'ecommerce-faq-pack',
    name: '跨境电商 FAQ 知识包',
    type: 'knowledge_pack',
    tagline: '物流 / 关税 / 退换货 300+ 条中英双语 FAQ 语料',
    description:
      '覆盖主流跨境平台（亚马逊 / Shopify / 速卖通）的物流、关税、退换货高频问题，中英双语，含持续更新承诺。',
    readme:
      '## 语料统计\n\n- 物流 142 条 / 关税 86 条 / 退换货 95 条\n- 中英双语对照\n- 每月更新一次\n\n语料已取得公开渠道整理授权。',
    creator: creator('cx-studio'),
    categories: ['客户/客服/FAQ', '客户/客服/多语客服'],
    tags: ['rag', 'zh', 'en', '多语'],
    version: '2026.07',
    compatibility: 'aranea>=1.5',
    priceModel: 'subscription',
    priceCents: 1900,
    rating: 4.8,
    ratingCount: 143,
    ratingDist: [118, 19, 4, 1, 1],
    installCount: 3320,
    activity30d: 81.5,
    health7d: 99.7,
    permissions: [],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-02-14',
    updatedAt: '2026-07-20',
    installed: false,
    versions: [
      { version: '2026.07', date: '2026-07-20', note: '新增欧盟 IOSS 关税问答 12 条' },
      { version: '2026.06', date: '2026-06-20', note: '例行更新' },
    ],
    reviews: [
      {
        id: 'r17',
        author: 'Wendy',
        rating: 5,
        content: '关税部分质量很高，客服命中率直接上了 15 个点。',
        createdAt: '2026-07-22',
        likes: 22,
      },
    ],
  },
  {
    id: 'workflow.content-pipeline',
    slug: 'content-pipeline',
    name: '内容发布流水线',
    type: 'workflow',
    tagline: '选题 → 初稿 → 审校 → 多平台分发的内容生产流',
    description: '从选题脑暴到多平台分发的完整内容流水线：初稿生成、事实核查、风格审校、定时分发与数据回收。',
    readme:
      '## 阶段\n\n1. 选题：热点抓取 + 脑暴\n2. 初稿：多风格生成\n3. 审校：事实核查 + 合规\n4. 分发：公众号 / 小红书 / X\n',
    creator: creator('linwei'),
    categories: ['内容/创意/故事生成', '客户/营销/文案生成'],
    tags: ['scheduled', 'text-gen', 'zh'],
    version: '0.8.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'one_time',
    priceCents: 4500,
    rating: 4.2,
    ratingCount: 36,
    ratingDist: [18, 12, 4, 1, 1],
    installCount: 480,
    activity30d: 16.8,
    health7d: 96.2,
    permissions: [
      { kind: 'network', value: '*', note: '抓取热点与分发到内容平台', risk: 'medium' },
      { kind: 'credential', value: 'platform_tokens', note: '各内容平台凭据', risk: 'high' },
    ],
    screenshotCount: 2,
    deps: [{ id: 'tool.web-search', name: 'Web 搜索工具包', range: '^3.0', kind: 'tool' }],
    status: 'published',
    publishedAt: '2026-06-25',
    updatedAt: '2026-07-14',
    installed: false,
    versions: [{ version: '0.8.0', date: '2026-06-25', note: '首个公开版本（Beta）' }],
    reviews: [
      {
        id: 'r18',
        author: '小七',
        rating: 4,
        content: 'Beta 版已经能跑通全流程，期待分发端更多平台。',
        createdAt: '2026-07-15',
        likes: 5,
      },
    ],
  },
  {
    id: 'bundle.ecommerce-cs',
    slug: 'ecommerce-cs-bundle',
    name: '跨境电商客服整包',
    type: 'company_bundle',
    tagline: '飞书接入 + 7 个 Agent + 3 个 Team + FAQ 知识的完整客服方案',
    description:
      '面向跨境电商的完整客服工作区：含飞书 Channel、售前/售后/物流 7 个 Agent、分流与升级 3 个 Team 编排、FAQ 知识包，安装向导逐步引导配置凭据与模型。',
    readme:
      '## 整包内容\n\n- Channel：飞书群机器人 ×1\n- Agent：售前咨询 / 售后工单 / 物流查询 / 差评安抚 / 多语翻译 / 质检 / 值班经理\n- Team：客服分流 / 升级处理 / 夜间值守\n- 知识包：跨境电商 FAQ\n\n## 安装方式\n\n进入 Workspace 初始化向导，按步骤配置凭据、模型与 Channel 绑定。',
    creator: creator('cx-studio'),
    categories: ['客户/客服/FAQ'],
    tags: ['integration:feishu', 'rag', '多语'],
    version: '2.3.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'enterprise',
    priceCents: 0,
    rating: 4.9,
    ratingCount: 67,
    ratingDist: [62, 4, 1, 0, 0],
    installCount: 890,
    activity30d: 48.3,
    health7d: 99.5,
    permissions: [
      { kind: 'credential', value: 'feishu_app', risk: 'high' },
      { kind: 'network', value: 'open.feishu.cn', risk: 'medium' },
      { kind: 'model', value: 'invoke', risk: 'low' },
    ],
    screenshotCount: 3,
    deps: [
      { id: 'team.support-triage', name: '客服分流 Team', range: '^1.1', kind: 'team' },
      { id: 'agent.faq-bot', name: '客服问答 Agent', range: '^2.0', kind: 'agent' },
      { id: 'knowledge.ecommerce-faq', name: '跨境电商 FAQ 知识包', range: '^2026.07', kind: 'knowledge_pack' },
      { id: 'channel.feishu-bot', name: '飞书群机器人 Channel 模板', range: '^1.3', kind: 'channel_template' },
    ],
    status: 'published',
    publishedAt: '2026-04-01',
    updatedAt: '2026-07-21',
    installed: false,
    versions: [
      { version: '2.3.0', date: '2026-07-21', note: '新增夜间值守 Team' },
      { version: '2.0.0', date: '2026-05-10', note: '整包重构，支持 Diff 模式叠加安装' },
      { version: '1.0.0', date: '2026-04-01', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r19',
        author: 'Sandra',
        rating: 5,
        content: '向导式安装体验非常好，凭据一步一提示，半天就上线了完整客服体系。',
        createdAt: '2026-07-23',
        likes: 28,
      },
    ],
  },
  {
    id: 'bundle.ecommerce-org',
    slug: 'ecommerce-cs-org',
    name: '跨境电商客服组织架构包',
    type: 'org_bundle',
    tagline: '客服部 / 运营部 / 质检部完整组织架构，岗位与 Agent 一键就位',
    description:
      '把经过实战验证的客服组织架构整体打包：3 个部门、9 个岗位、12 个岗位专属 Agent。安装后自动生成部门-岗位树并把 Agent 挂到对应岗位，组织架构即刻可运转。',
    readme:
      '## 包含内容\n\n- **客服部**：售前顾问 / 售后专员 / 物流跟进 / 夜班值守\n- **运营部**：活动运营 / 内容运营 / 数据分析\n- **质检部**：会话质检 / 知识库维护\n\n每个岗位绑定专属 Agent（含提示词与工具策略）。\n\n## 安装说明\n\nDiff 模式：已存在的部门/岗位保留，仅补充缺失节点；冲突岗位可选择跳过 / 覆盖 / 重命名。',
    creator: creator('cx-studio'),
    categories: ['客户/客服/FAQ'],
    tags: ['zh', '多语', 'rag'],
    version: '1.2.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'enterprise',
    priceCents: 0,
    rating: 4.8,
    ratingCount: 41,
    ratingDist: [36, 4, 1, 0, 0],
    installCount: 620,
    activity30d: 38.6,
    health7d: 99.3,
    permissions: [{ kind: 'model', value: 'invoke', risk: 'low' }],
    screenshotCount: 3,
    deps: [
      { id: 'agent.faq-bot', name: '客服问答 Agent', range: '^2.0', kind: 'agent' },
      { id: 'knowledge.ecommerce-faq', name: '跨境电商 FAQ 知识包', range: '^2026.07', kind: 'knowledge_pack' },
    ],
    status: 'published',
    publishedAt: '2026-05-28',
    updatedAt: '2026-07-17',
    installed: false,
    orgBundle: {
      departments: [
        {
          key: 'cs',
          name: '客服部',
          positions: [
            { key: 'cs-pre', name: '售前顾问', agents: ['售前咨询 Agent', '商品推荐 Agent'] },
            { key: 'cs-after', name: '售后专员', agents: ['售后工单 Agent', '差评安抚 Agent'] },
            { key: 'cs-logistics', name: '物流跟进', agents: ['物流查询 Agent'] },
            { key: 'cs-night', name: '夜班值守', agents: ['夜间值班 Agent'] },
          ],
        },
        {
          key: 'ops',
          name: '运营部',
          positions: [
            { key: 'ops-campaign', name: '活动运营', agents: ['活动策划 Agent', '文案生成 Agent'] },
            { key: 'ops-content', name: '内容运营', agents: ['内容编辑 Agent'] },
            { key: 'ops-data', name: '数据分析', agents: ['经营分析 Agent'] },
          ],
        },
        {
          key: 'qa',
          name: '质检部',
          positions: [
            { key: 'qa-review', name: '会话质检', agents: ['质检 Agent'] },
            { key: 'qa-kb', name: '知识库维护', agents: ['知识库维护 Agent'] },
          ],
        },
      ],
      totals: { departments: 3, positions: 9, agents: 12 },
    },
    versions: [
      { version: '1.2.0', date: '2026-07-17', note: '新增夜班值守岗位' },
      { version: '1.1.0', date: '2026-06-20', note: '支持 Diff 模式冲突处理' },
      { version: '1.0.0', date: '2026-05-28', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r20',
        author: 'Elena',
        rating: 5,
        content: '新 workspace 装上直接有了完整客服团队雏形，岗位职责划分帮我们少踩了很多坑。',
        createdAt: '2026-07-19',
        likes: 16,
      },
    ],
  },
  {
    id: 'plugin.audit-log',
    slug: 'audit-log-plugin',
    name: '审计日志插件',
    type: 'plugin',
    tagline: '全量工具调用审计 + 敏感操作拦截（企业市场）',
    description: '拦截器型插件：记录全量工具调用审计链，支持敏感操作人工确认与合规报表导出。仅在企业市场提供。',
    readme: '## 能力\n\n- 工具调用全量审计\n- 敏感操作二次确认钩子\n- 合规报表导出\n\n> 插件类资产仅企业市场可用。',
    creator: creator('aranea-official'),
    categories: ['其它/工具集合'],
    tags: ['runtime:local-only'],
    version: '1.0.0',
    compatibility: 'aranea>=1.6',
    priceModel: 'enterprise',
    priceCents: 0,
    rating: 4.7,
    ratingCount: 12,
    ratingDist: [10, 1, 1, 0, 0],
    installCount: 96,
    activity30d: 9.4,
    health7d: 100,
    permissions: [{ kind: 'command', value: 'execute', note: '拦截并审计命令执行', risk: 'high' }],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-06-30',
    updatedAt: '2026-06-30',
    installed: false,
    versions: [{ version: '1.0.0', date: '2026-06-30', note: '首个版本' }],
    reviews: [
      {
        id: 'r21',
        author: '安全组',
        rating: 5,
        content: '合规审计终于不用自己拼了。',
        createdAt: '2026-07-05',
        likes: 4,
      },
    ],
  },
  {
    id: 'skill.meeting-notes',
    slug: 'meeting-notes',
    name: '会议纪要生成',
    type: 'skill',
    tagline: '转写文本一键生成纪要：决议 / 待办 / 责任人',
    description: '输入会议转写文本，输出结构化纪要：核心决议、待办事项（含责任人与 deadline）、分歧点记录。',
    readme: '## 能力\n\n- 决议 / 待办 / 分歧三段式纪要\n- 待办自动抽取责任人\n- 支持飞书文档导出\n',
    creator: creator('devops-lab'),
    categories: ['办公/会议/纪要生成'],
    tags: ['text-gen', 'zh'],
    version: '1.0.2',
    compatibility: 'aranea>=1.5',
    priceModel: 'free',
    priceCents: 0,
    rating: 4.4,
    ratingCount: 76,
    ratingDist: [45, 22, 6, 2, 1],
    installCount: 2140,
    activity30d: 33.7,
    health7d: 98.1,
    permissions: [{ kind: 'model', value: 'invoke', risk: 'low' }],
    screenshotCount: 1,
    deps: [],
    status: 'published',
    publishedAt: '2026-05-08',
    updatedAt: '2026-06-28',
    installed: false,
    versions: [
      { version: '1.0.2', date: '2026-06-28', note: '提升待办抽取准确率' },
      { version: '1.0.0', date: '2026-05-08', note: '首个版本' },
    ],
    reviews: [
      {
        id: 'r22',
        author: 'Daniel',
        rating: 4,
        content: '待办抽取很准，希望支持英文会议。',
        createdAt: '2026-07-01',
        likes: 8,
      },
    ],
  },
];

// ── 买家工作台 ─────────────────────────────────────────────────

export const MOCK_MY_INSTALLS: MyInstall[] = [
  {
    assetId: 'skill.pr-description',
    name: 'PR 描述生成器',
    type: 'skill',
    version: '1.4.2',
    installedAt: '2026-06-12',
    health7d: 99.2,
    status: 'healthy',
  },
  {
    assetId: 'mcp.github',
    name: 'GitHub MCP 连接器',
    type: 'mcp_server',
    version: '2.1.0',
    installedAt: '2026-06-12',
    health7d: 99.6,
    status: 'healthy',
  },
  {
    assetId: 'channel.feishu-bot',
    name: '飞书群机器人 Channel 模板',
    type: 'channel_template',
    version: '1.3.0',
    installedAt: '2026-05-30',
    health7d: 99.1,
    updateAvailable: '1.4.0',
    status: 'healthy',
  },
  {
    assetId: 'agent.faq-bot',
    name: '客服问答 Agent',
    type: 'agent',
    version: '1.3.0',
    installedAt: '2026-05-18',
    health7d: 91.4,
    updateAvailable: '2.0.1',
    status: 'degraded',
  },
  {
    assetId: 'skill.weekly-report',
    name: '周报生成器',
    type: 'skill',
    version: '1.1.0',
    installedAt: '2026-06-25',
    health7d: 98.5,
    status: 'healthy',
  },
  {
    assetId: 'tool.web-search',
    name: 'Web 搜索工具包',
    type: 'tool',
    version: '3.0.0',
    installedAt: '2026-06-20',
    health7d: 62.3,
    updateAvailable: '3.2.0',
    status: 'failed',
  },
];

export const MOCK_MY_ORDERS: MyOrder[] = [
  {
    id: 'MKT-20260718-0082',
    assetId: 'skill.weekly-report',
    name: '周报生成器',
    type: 'skill',
    priceModel: 'one_time',
    amountCents: 1200,
    status: 'paid',
    createdAt: '2026-06-25',
  },
  {
    id: 'MKT-20260602-0147',
    assetId: 'agent.faq-bot',
    name: '客服问答 Agent',
    type: 'agent',
    priceModel: 'subscription',
    amountCents: 3900,
    status: 'paid',
    createdAt: '2026-07-01',
  },
  {
    id: 'MKT-20260520-0063',
    assetId: 'agent.code-reviewer',
    name: '代码审查员 Agent 模板',
    type: 'agent',
    priceModel: 'one_time',
    amountCents: 2900,
    status: 'refunded',
    createdAt: '2026-05-20',
  },
  {
    id: 'MKT-20260726-0019',
    assetId: 'team.pr-review',
    name: 'PR Review 流水线 Team',
    type: 'team',
    priceModel: 'one_time',
    amountCents: 5900,
    status: 'refunding',
    createdAt: '2026-07-26',
  },
];

// ── 创作者中心 ─────────────────────────────────────────────────

export const MOCK_STUDIO_STATS: StudioStats = {
  totalInstalls: 12480,
  revenueCents: 864200,
  avgRating: 4.7,
  activeAssets: 4,
  installTrend: [42, 55, 48, 61, 58, 72, 66, 81, 77, 90, 84, 96],
  revenueTrend: [120, 180, 150, 240, 210, 320, 280, 360, 340, 420, 390, 480],
};

export const MOCK_STUDIO_ASSETS: StudioAsset[] = [
  {
    id: 'skill.pr-description',
    name: 'PR 描述生成器',
    type: 'skill',
    version: '1.4.2',
    reviewStatus: 'published',
    installs: 8930,
    rating: 4.8,
    revenueCents: 0,
    updatedAt: '2026-07-18',
  },
  {
    id: 'agent.code-reviewer',
    name: '代码审查员 Agent 模板',
    type: 'agent',
    version: '1.2.0',
    reviewStatus: 'published',
    installs: 3980,
    rating: 4.6,
    revenueCents: 623000,
    updatedAt: '2026-07-11',
  },
  {
    id: 'team.pr-review',
    name: 'PR Review 流水线 Team',
    type: 'team',
    version: '1.4.2',
    reviewStatus: 'published',
    installs: 2870,
    rating: 4.7,
    revenueCents: 241200,
    updatedAt: '2026-07-19',
  },
  {
    id: 'skill.pr-checklist',
    name: 'PR 自查清单 Skill',
    type: 'skill',
    version: '0.3.0',
    reviewStatus: 'manual',
    installs: 0,
    rating: 0,
    revenueCents: 0,
    updatedAt: '2026-07-27',
  },
  {
    id: 'tool.api-diff',
    name: 'API Diff 工具',
    type: 'tool',
    version: '0.1.2',
    reviewStatus: 'needs_fix',
    installs: 0,
    rating: 0,
    revenueCents: 0,
    updatedAt: '2026-07-25',
  },
];

export const MOCK_STUDIO_INBOX: StudioInboxItem[] = [
  {
    id: 'i1',
    assetName: 'PR 描述生成器',
    author: 'Kira',
    rating: 4,
    content: '整体好用，希望支持 GitLab 的 MR 描述格式。',
    createdAt: '2026-07-08',
    replied: false,
  },
  {
    id: 'i2',
    assetName: '代码审查员 Agent 模板',
    author: '大成',
    rating: 4,
    content: '对 Go 的审查质量明显好于 Python，希望继续补强。',
    createdAt: '2026-06-30',
    replied: false,
  },
  {
    id: 'i3',
    assetName: 'PR 描述生成器',
    author: '陈默',
    rating: 5,
    content: '接进团队流水线后，PR 描述质量明显提升，评审效率高了不少。',
    createdAt: '2026-07-20',
    replied: true,
  },
  {
    id: 'i4',
    assetName: 'PR Review 流水线 Team',
    author: 'Frank',
    rating: 5,
    content: '依赖一键装齐的体验很好，装完跑个 smoke 就直接进生产了。',
    createdAt: '2026-07-21',
    replied: false,
  },
];

// ── 发布向导：组织整包可选节点（从当前 workspace 组织模块读取的模拟快照） ──

export const MOCK_ORG_PICK_TREE: OrgPickNode[] = [
  {
    key: 'dept-cs',
    label: '客服部',
    children: [
      { key: 'pos-pre', label: '售前顾问', agents: ['售前咨询 Agent', '商品推荐 Agent'] },
      { key: 'pos-after', label: '售后专员', agents: ['售后工单 Agent', '差评安抚 Agent'] },
      { key: 'pos-night', label: '夜班值守', agents: ['夜间值班 Agent'] },
    ],
  },
  {
    key: 'dept-ops',
    label: '运营部',
    children: [
      { key: 'pos-campaign', label: '活动运营', agents: ['活动策划 Agent', '文案生成 Agent'] },
      { key: 'pos-data', label: '数据分析', agents: ['经营分析 Agent'] },
    ],
  },
  {
    key: 'dept-qa',
    label: '质检部',
    children: [{ key: 'pos-review', label: '会话质检', agents: ['质检 Agent'] }],
  },
];
