// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.32.1
// source: kratos/agentbridge/v1/agentbridge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentBridgeServiceCancelTask = "/kratos.agentbridge.v1.AgentBridgeService/CancelTask"
const OperationAgentBridgeServiceDeleteProject = "/kratos.agentbridge.v1.AgentBridgeService/DeleteProject"
const OperationAgentBridgeServiceGetTask = "/kratos.agentbridge.v1.AgentBridgeService/GetTask"
const OperationAgentBridgeServiceListAgents = "/kratos.agentbridge.v1.AgentBridgeService/ListAgents"
const OperationAgentBridgeServiceListProjects = "/kratos.agentbridge.v1.AgentBridgeService/ListProjects"
const OperationAgentBridgeServiceListTasks = "/kratos.agentbridge.v1.AgentBridgeService/ListTasks"
const OperationAgentBridgeServiceProbeAgent = "/kratos.agentbridge.v1.AgentBridgeService/ProbeAgent"
const OperationAgentBridgeServiceUpsertAgent = "/kratos.agentbridge.v1.AgentBridgeService/UpsertAgent"
const OperationAgentBridgeServiceUpsertProject = "/kratos.agentbridge.v1.AgentBridgeService/UpsertProject"

type AgentBridgeServiceHTTPServer interface {
	CancelTask(context.Context, *CancelTaskRequest) (*CodingTask, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*emptypb.Empty, error)
	GetTask(context.Context, *GetTaskRequest) (*CodingTask, error)
	ListAgents(context.Context, *emptypb.Empty) (*ListAgentsResponse, error)
	ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error)
	// ListTasks 任务查询/取消
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	ProbeAgent(context.Context, *ProbeAgentRequest) (*ProbeAgentResponse, error)
	// UpsertAgent 工具注册管理（删除经 enabled=false，M1 不提供物理删除）
	UpsertAgent(context.Context, *UpsertAgentRequest) (*CodingAgent, error)
	// UpsertProject 项目目录注册管理
	UpsertProject(context.Context, *UpsertProjectRequest) (*CodingProject, error)
}

func RegisterAgentBridgeServiceHTTPServer(s *http.Server, srv AgentBridgeServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/agentbridge/agents", _AgentBridgeService_UpsertAgent0_HTTP_Handler(srv))
	r.GET("/v1/agentbridge/agents", _AgentBridgeService_ListAgents1_HTTP_Handler(srv))
	r.POST("/v1/agentbridge/agents/probe", _AgentBridgeService_ProbeAgent0_HTTP_Handler(srv))
	r.POST("/v1/agentbridge/projects", _AgentBridgeService_UpsertProject0_HTTP_Handler(srv))
	r.GET("/v1/agentbridge/projects", _AgentBridgeService_ListProjects0_HTTP_Handler(srv))
	r.DELETE("/v1/agentbridge/projects/{id}", _AgentBridgeService_DeleteProject0_HTTP_Handler(srv))
	r.GET("/v1/agentbridge/tasks", _AgentBridgeService_ListTasks0_HTTP_Handler(srv))
	r.GET("/v1/agentbridge/tasks/{id}", _AgentBridgeService_GetTask0_HTTP_Handler(srv))
	r.POST("/v1/agentbridge/tasks/{id}/cancel", _AgentBridgeService_CancelTask0_HTTP_Handler(srv))
}

func _AgentBridgeService_UpsertAgent0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertAgentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceUpsertAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertAgent(ctx, req.(*UpsertAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CodingAgent)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_ListAgents1_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceListAgents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAgents(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAgentsResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_ProbeAgent0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProbeAgentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceProbeAgent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProbeAgent(ctx, req.(*ProbeAgentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProbeAgentResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_UpsertProject0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceUpsertProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertProject(ctx, req.(*UpsertProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CodingProject)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_ListProjects0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceListProjects)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProjects(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectsResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_DeleteProject0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProjectRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceDeleteProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProject(ctx, req.(*DeleteProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_ListTasks0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_GetTask0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CodingTask)
		return ctx.Result(200, reply)
	}
}

func _AgentBridgeService_CancelTask0_HTTP_Handler(srv AgentBridgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentBridgeServiceCancelTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelTask(ctx, req.(*CancelTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CodingTask)
		return ctx.Result(200, reply)
	}
}

type AgentBridgeServiceHTTPClient interface {
	CancelTask(ctx context.Context, req *CancelTaskRequest, opts ...http.CallOption) (rsp *CodingTask, err error)
	DeleteProject(ctx context.Context, req *DeleteProjectRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetTask(ctx context.Context, req *GetTaskRequest, opts ...http.CallOption) (rsp *CodingTask, err error)
	ListAgents(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListAgentsResponse, err error)
	ListProjects(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListProjectsResponse, err error)
	// ListTasks 任务查询/取消
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksResponse, err error)
	ProbeAgent(ctx context.Context, req *ProbeAgentRequest, opts ...http.CallOption) (rsp *ProbeAgentResponse, err error)
	// UpsertAgent 工具注册管理（删除经 enabled=false，M1 不提供物理删除）
	UpsertAgent(ctx context.Context, req *UpsertAgentRequest, opts ...http.CallOption) (rsp *CodingAgent, err error)
	// UpsertProject 项目目录注册管理
	UpsertProject(ctx context.Context, req *UpsertProjectRequest, opts ...http.CallOption) (rsp *CodingProject, err error)
}

type AgentBridgeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentBridgeServiceHTTPClient(client *http.Client) AgentBridgeServiceHTTPClient {
	return &AgentBridgeServiceHTTPClientImpl{client}
}

func (c *AgentBridgeServiceHTTPClientImpl) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...http.CallOption) (*CodingTask, error) {
	var out CodingTask
	pattern := "/v1/agentbridge/tasks/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceCancelTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentBridgeServiceHTTPClientImpl) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/agentbridge/projects/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceDeleteProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentBridgeServiceHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskRequest, opts ...http.CallOption) (*CodingTask, error) {
	var out CodingTask
	pattern := "/v1/agentbridge/tasks/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentBridgeServiceHTTPClientImpl) ListAgents(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListAgentsResponse, error) {
	var out ListAgentsResponse
	pattern := "/v1/agentbridge/agents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceListAgents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentBridgeServiceHTTPClientImpl) ListProjects(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListProjectsResponse, error) {
	var out ListProjectsResponse
	pattern := "/v1/agentbridge/projects"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceListProjects))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks 任务查询/取消
func (c *AgentBridgeServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksResponse, error) {
	var out ListTasksResponse
	pattern := "/v1/agentbridge/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AgentBridgeServiceHTTPClientImpl) ProbeAgent(ctx context.Context, in *ProbeAgentRequest, opts ...http.CallOption) (*ProbeAgentResponse, error) {
	var out ProbeAgentResponse
	pattern := "/v1/agentbridge/agents/probe"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceProbeAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpsertAgent 工具注册管理（删除经 enabled=false，M1 不提供物理删除）
func (c *AgentBridgeServiceHTTPClientImpl) UpsertAgent(ctx context.Context, in *UpsertAgentRequest, opts ...http.CallOption) (*CodingAgent, error) {
	var out CodingAgent
	pattern := "/v1/agentbridge/agents"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceUpsertAgent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpsertProject 项目目录注册管理
func (c *AgentBridgeServiceHTTPClientImpl) UpsertProject(ctx context.Context, in *UpsertProjectRequest, opts ...http.CallOption) (*CodingProject, error) {
	var out CodingProject
	pattern := "/v1/agentbridge/projects"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentBridgeServiceUpsertProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
