// Code generated by ent, DO NOT EDIT.

package memoryfactpending

import (
	"aranea-agents/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldID, id))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldAgentID, v))
}

// FactKey applies equality check predicate on the "fact_key" field. It's identical to FactKeyEQ.
func FactKey(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldFactKey, v))
}

// Verdict applies equality check predicate on the "verdict" field. It's identical to VerdictEQ.
func Verdict(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldVerdict, v))
}

// ProposedBody applies equality check predicate on the "proposed_body" field. It's identical to ProposedBodyEQ.
func ProposedBody(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldProposedBody, v))
}

// PriorBody applies equality check predicate on the "prior_body" field. It's identical to PriorBodyEQ.
func PriorBody(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldPriorBody, v))
}

// AdjudicatorReason applies equality check predicate on the "adjudicator_reason" field. It's identical to AdjudicatorReasonEQ.
func AdjudicatorReason(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldAdjudicatorReason, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldPayloadJSON, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldStatus, v))
}

// Approver applies equality check predicate on the "approver" field. It's identical to ApproverEQ.
func Approver(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldApprover, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldCreatedAt, v))
}

// DecidedAt applies equality check predicate on the "decided_at" field. It's identical to DecidedAtEQ.
func DecidedAt(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldDecidedAt, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldAgentID, v))
}

// FactKeyEQ applies the EQ predicate on the "fact_key" field.
func FactKeyEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldFactKey, v))
}

// FactKeyNEQ applies the NEQ predicate on the "fact_key" field.
func FactKeyNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldFactKey, v))
}

// FactKeyIn applies the In predicate on the "fact_key" field.
func FactKeyIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldFactKey, vs...))
}

// FactKeyNotIn applies the NotIn predicate on the "fact_key" field.
func FactKeyNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldFactKey, vs...))
}

// FactKeyGT applies the GT predicate on the "fact_key" field.
func FactKeyGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldFactKey, v))
}

// FactKeyGTE applies the GTE predicate on the "fact_key" field.
func FactKeyGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldFactKey, v))
}

// FactKeyLT applies the LT predicate on the "fact_key" field.
func FactKeyLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldFactKey, v))
}

// FactKeyLTE applies the LTE predicate on the "fact_key" field.
func FactKeyLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldFactKey, v))
}

// FactKeyContains applies the Contains predicate on the "fact_key" field.
func FactKeyContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldFactKey, v))
}

// FactKeyHasPrefix applies the HasPrefix predicate on the "fact_key" field.
func FactKeyHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldFactKey, v))
}

// FactKeyHasSuffix applies the HasSuffix predicate on the "fact_key" field.
func FactKeyHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldFactKey, v))
}

// FactKeyEqualFold applies the EqualFold predicate on the "fact_key" field.
func FactKeyEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldFactKey, v))
}

// FactKeyContainsFold applies the ContainsFold predicate on the "fact_key" field.
func FactKeyContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldFactKey, v))
}

// VerdictEQ applies the EQ predicate on the "verdict" field.
func VerdictEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldVerdict, v))
}

// VerdictNEQ applies the NEQ predicate on the "verdict" field.
func VerdictNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldVerdict, v))
}

// VerdictIn applies the In predicate on the "verdict" field.
func VerdictIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldVerdict, vs...))
}

// VerdictNotIn applies the NotIn predicate on the "verdict" field.
func VerdictNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldVerdict, vs...))
}

// VerdictGT applies the GT predicate on the "verdict" field.
func VerdictGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldVerdict, v))
}

// VerdictGTE applies the GTE predicate on the "verdict" field.
func VerdictGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldVerdict, v))
}

// VerdictLT applies the LT predicate on the "verdict" field.
func VerdictLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldVerdict, v))
}

// VerdictLTE applies the LTE predicate on the "verdict" field.
func VerdictLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldVerdict, v))
}

// VerdictContains applies the Contains predicate on the "verdict" field.
func VerdictContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldVerdict, v))
}

// VerdictHasPrefix applies the HasPrefix predicate on the "verdict" field.
func VerdictHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldVerdict, v))
}

// VerdictHasSuffix applies the HasSuffix predicate on the "verdict" field.
func VerdictHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldVerdict, v))
}

// VerdictEqualFold applies the EqualFold predicate on the "verdict" field.
func VerdictEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldVerdict, v))
}

// VerdictContainsFold applies the ContainsFold predicate on the "verdict" field.
func VerdictContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldVerdict, v))
}

// ProposedBodyEQ applies the EQ predicate on the "proposed_body" field.
func ProposedBodyEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldProposedBody, v))
}

// ProposedBodyNEQ applies the NEQ predicate on the "proposed_body" field.
func ProposedBodyNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldProposedBody, v))
}

// ProposedBodyIn applies the In predicate on the "proposed_body" field.
func ProposedBodyIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldProposedBody, vs...))
}

// ProposedBodyNotIn applies the NotIn predicate on the "proposed_body" field.
func ProposedBodyNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldProposedBody, vs...))
}

// ProposedBodyGT applies the GT predicate on the "proposed_body" field.
func ProposedBodyGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldProposedBody, v))
}

// ProposedBodyGTE applies the GTE predicate on the "proposed_body" field.
func ProposedBodyGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldProposedBody, v))
}

// ProposedBodyLT applies the LT predicate on the "proposed_body" field.
func ProposedBodyLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldProposedBody, v))
}

// ProposedBodyLTE applies the LTE predicate on the "proposed_body" field.
func ProposedBodyLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldProposedBody, v))
}

// ProposedBodyContains applies the Contains predicate on the "proposed_body" field.
func ProposedBodyContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldProposedBody, v))
}

// ProposedBodyHasPrefix applies the HasPrefix predicate on the "proposed_body" field.
func ProposedBodyHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldProposedBody, v))
}

// ProposedBodyHasSuffix applies the HasSuffix predicate on the "proposed_body" field.
func ProposedBodyHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldProposedBody, v))
}

// ProposedBodyEqualFold applies the EqualFold predicate on the "proposed_body" field.
func ProposedBodyEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldProposedBody, v))
}

// ProposedBodyContainsFold applies the ContainsFold predicate on the "proposed_body" field.
func ProposedBodyContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldProposedBody, v))
}

// PriorBodyEQ applies the EQ predicate on the "prior_body" field.
func PriorBodyEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldPriorBody, v))
}

// PriorBodyNEQ applies the NEQ predicate on the "prior_body" field.
func PriorBodyNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldPriorBody, v))
}

// PriorBodyIn applies the In predicate on the "prior_body" field.
func PriorBodyIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldPriorBody, vs...))
}

// PriorBodyNotIn applies the NotIn predicate on the "prior_body" field.
func PriorBodyNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldPriorBody, vs...))
}

// PriorBodyGT applies the GT predicate on the "prior_body" field.
func PriorBodyGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldPriorBody, v))
}

// PriorBodyGTE applies the GTE predicate on the "prior_body" field.
func PriorBodyGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldPriorBody, v))
}

// PriorBodyLT applies the LT predicate on the "prior_body" field.
func PriorBodyLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldPriorBody, v))
}

// PriorBodyLTE applies the LTE predicate on the "prior_body" field.
func PriorBodyLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldPriorBody, v))
}

// PriorBodyContains applies the Contains predicate on the "prior_body" field.
func PriorBodyContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldPriorBody, v))
}

// PriorBodyHasPrefix applies the HasPrefix predicate on the "prior_body" field.
func PriorBodyHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldPriorBody, v))
}

// PriorBodyHasSuffix applies the HasSuffix predicate on the "prior_body" field.
func PriorBodyHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldPriorBody, v))
}

// PriorBodyEqualFold applies the EqualFold predicate on the "prior_body" field.
func PriorBodyEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldPriorBody, v))
}

// PriorBodyContainsFold applies the ContainsFold predicate on the "prior_body" field.
func PriorBodyContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldPriorBody, v))
}

// AdjudicatorReasonEQ applies the EQ predicate on the "adjudicator_reason" field.
func AdjudicatorReasonEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonNEQ applies the NEQ predicate on the "adjudicator_reason" field.
func AdjudicatorReasonNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonIn applies the In predicate on the "adjudicator_reason" field.
func AdjudicatorReasonIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldAdjudicatorReason, vs...))
}

// AdjudicatorReasonNotIn applies the NotIn predicate on the "adjudicator_reason" field.
func AdjudicatorReasonNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldAdjudicatorReason, vs...))
}

// AdjudicatorReasonGT applies the GT predicate on the "adjudicator_reason" field.
func AdjudicatorReasonGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonGTE applies the GTE predicate on the "adjudicator_reason" field.
func AdjudicatorReasonGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonLT applies the LT predicate on the "adjudicator_reason" field.
func AdjudicatorReasonLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonLTE applies the LTE predicate on the "adjudicator_reason" field.
func AdjudicatorReasonLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonContains applies the Contains predicate on the "adjudicator_reason" field.
func AdjudicatorReasonContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonHasPrefix applies the HasPrefix predicate on the "adjudicator_reason" field.
func AdjudicatorReasonHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonHasSuffix applies the HasSuffix predicate on the "adjudicator_reason" field.
func AdjudicatorReasonHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonEqualFold applies the EqualFold predicate on the "adjudicator_reason" field.
func AdjudicatorReasonEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldAdjudicatorReason, v))
}

// AdjudicatorReasonContainsFold applies the ContainsFold predicate on the "adjudicator_reason" field.
func AdjudicatorReasonContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldAdjudicatorReason, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldPayloadJSON, v))
}

// PayloadJSONContains applies the Contains predicate on the "payload_json" field.
func PayloadJSONContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldPayloadJSON, v))
}

// PayloadJSONHasPrefix applies the HasPrefix predicate on the "payload_json" field.
func PayloadJSONHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldPayloadJSON, v))
}

// PayloadJSONHasSuffix applies the HasSuffix predicate on the "payload_json" field.
func PayloadJSONHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldPayloadJSON, v))
}

// PayloadJSONEqualFold applies the EqualFold predicate on the "payload_json" field.
func PayloadJSONEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldPayloadJSON, v))
}

// PayloadJSONContainsFold applies the ContainsFold predicate on the "payload_json" field.
func PayloadJSONContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldPayloadJSON, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldStatus, v))
}

// ApproverEQ applies the EQ predicate on the "approver" field.
func ApproverEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldApprover, v))
}

// ApproverNEQ applies the NEQ predicate on the "approver" field.
func ApproverNEQ(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldApprover, v))
}

// ApproverIn applies the In predicate on the "approver" field.
func ApproverIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldApprover, vs...))
}

// ApproverNotIn applies the NotIn predicate on the "approver" field.
func ApproverNotIn(vs ...string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldApprover, vs...))
}

// ApproverGT applies the GT predicate on the "approver" field.
func ApproverGT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldApprover, v))
}

// ApproverGTE applies the GTE predicate on the "approver" field.
func ApproverGTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldApprover, v))
}

// ApproverLT applies the LT predicate on the "approver" field.
func ApproverLT(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldApprover, v))
}

// ApproverLTE applies the LTE predicate on the "approver" field.
func ApproverLTE(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldApprover, v))
}

// ApproverContains applies the Contains predicate on the "approver" field.
func ApproverContains(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContains(FieldApprover, v))
}

// ApproverHasPrefix applies the HasPrefix predicate on the "approver" field.
func ApproverHasPrefix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasPrefix(FieldApprover, v))
}

// ApproverHasSuffix applies the HasSuffix predicate on the "approver" field.
func ApproverHasSuffix(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldHasSuffix(FieldApprover, v))
}

// ApproverEqualFold applies the EqualFold predicate on the "approver" field.
func ApproverEqualFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEqualFold(FieldApprover, v))
}

// ApproverContainsFold applies the ContainsFold predicate on the "approver" field.
func ApproverContainsFold(v string) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldContainsFold(FieldApprover, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldCreatedAt, v))
}

// DecidedAtEQ applies the EQ predicate on the "decided_at" field.
func DecidedAtEQ(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldEQ(FieldDecidedAt, v))
}

// DecidedAtNEQ applies the NEQ predicate on the "decided_at" field.
func DecidedAtNEQ(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNEQ(FieldDecidedAt, v))
}

// DecidedAtIn applies the In predicate on the "decided_at" field.
func DecidedAtIn(vs ...int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldIn(FieldDecidedAt, vs...))
}

// DecidedAtNotIn applies the NotIn predicate on the "decided_at" field.
func DecidedAtNotIn(vs ...int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldNotIn(FieldDecidedAt, vs...))
}

// DecidedAtGT applies the GT predicate on the "decided_at" field.
func DecidedAtGT(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGT(FieldDecidedAt, v))
}

// DecidedAtGTE applies the GTE predicate on the "decided_at" field.
func DecidedAtGTE(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldGTE(FieldDecidedAt, v))
}

// DecidedAtLT applies the LT predicate on the "decided_at" field.
func DecidedAtLT(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLT(FieldDecidedAt, v))
}

// DecidedAtLTE applies the LTE predicate on the "decided_at" field.
func DecidedAtLTE(v int64) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.FieldLTE(FieldDecidedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryFactPending) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryFactPending) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryFactPending) predicate.MemoryFactPending {
	return predicate.MemoryFactPending(sql.NotPredicates(p))
}
