package biz

// DefaultAgentRuntimeSettings returns built-in defaults for missing agent_runtime_settings rows.
func DefaultAgentRuntimeSettings() AgentRuntimeSettings {
	return AgentRuntimeSettings{
		SelfEvolve:                        true,
		SubagentsEnabled:                  true,
		SubagentsMaxConcurrency:           20,
		SubagentsMaxGenerationDepth:       1,
		SubagentsMaxChildrenPerAgent:      5,
		SubagentsArchiveAfterMinutes:      60,
		SubagentsMaxRetries:               2,
		SubagentsStoredResultRunes:        4000,
		SubagentsStoredSummaryRunes:       240,
		ToolsEnabled:                      true,
		ToolsProfile:                      "coding",
		ToolsAllowJSON:                    "[]",
		ToolsDenyJSON:                     DefaultToolsDenyFrameworkMemory,
		ToolsConcurrentAllowJSON:          "[]",
		MemoryEnabled:                     true,
		MemoryMaxChunkLength:              1000,
		MemoryMaxResults:                  6,
		MemoryMinScore:                    0.35,
		HeartbeatIntervalMinutes:          30,
		EvolutionSelfEvolve:               true,
		EvolutionSkillEvolve:              true,
		EvolutionMetricsEnabled:           true,
		EvolutionSuggestionsEnabled:       true,
		GuardrailMaxChangePerPeriod:       0.1,
		GuardrailMinDataPoints:            100,
		GuardrailRollbackOnDeclinePercent: 20,
		L0RecentWindowTurns:               12,
		L0RecentWindowTokens:              0,
		L0SummaryThreshold:                0.6,
		L0SummaryKeepTurns:                4,
		L0CompressMinGapSec:               600,
		L0TruncateStrategy:                "summary",
		L0InjectL1:                        true,
		L0InjectL3:                        true,
		L0InjectL4:                        false,
		L0L3MaxChunks:                     5,
		L0L4MaxPaths:                      3,
		L0SnapshotMode:                    "on_warning",
		L0SnapshotEnabled:                 true,
		L1Enabled:                         true,
		L1BudgetTokens:                    8192,
		L1FieldMaxTokens:                  2048,
		L1HistoryKeepRevisions:            10,
		L1HistoryEnabled:                  false,
		L1ArchiveOnIdleMinutes:            60,
		L2EpisodeEnabled:                  true,
		L2EpisodeMinImportance:            0.3,
		L2IndexEnabled:                    true,
		L2RecallMax:                       3,
		L2RetentionDays:                   90,
		L2ArchiveAfterDays:                30,
		L3Enabled:                         true,
		L3RecallTopK:                      5,
		L3RecallMinScore:                  0.55,
		L3RecallScopesJSON:                `["agent","user","team","workspace"]`,
		L3DecayIntervalHours:              24,
		L3ArchiveThreshold:                0.2,
		L3MaxPerRecallChars:               1500,
		L4Enabled:                         true,
		L4GraphInjectNeighbors:            true,
		L4GraphMaxNeighbors:               6,
		L4GraphMaxHops:                    2,
		L4IdentityInject:                  true,
		L4StrategyInject:                  false,
		EvoEnabled:                        false,
		EvoAutoApply:                      false,
		EvoMinEpisodes:                    20,
		EvoMinNegativeFeedback:            3,
		EvoThrottleHours:                  24,
		EvoProposalTTLDays:                14,
		EvoPersonaMaxChars:                1500,
		EvoSystemPromptMaxAppends:         5,
		SkillRuntimeJSON:                  "{}",
		IntentPassEnabled:                 true,
		ClarificationEnabled:              true,
		CodeExecutorType:                  "local",
		PlannerConfigJSON:                 "{}",
		ToolsRetryEnabled:                 false,
		ToolsRetryMaxAttempts:             2,
		ToolsRetryInitialIntervalMs:       500,
		ToolsRetryBackoffFactor:           2.0,
		ToolsRetryMaxIntervalMs:           5000,
		ToolsRetryJitter:                  true,
		// P2-B1: 默认开启并行工具执行。安全性由项目层 ToolDecorator
		// (internal/tools/decorator.go) 保证：每次工具调用都经过 60s 超时
		// 和 10KB 结果预算保护。ConcurrentSafe 工具可安全并行且启用确定性
		// 缓存；Exclusive 工具虽然也可能被框架并行调度，但装饰器的超时
		// 和结果预算同样适用。详见 ADR: docs/reports/2026-06-15-review-adr-tool-parallel-execution.md
		ToolsParallelEnabled:      true,
		ToolsStreamingEnabled:     false,
		L4DecayIntervalHours:      168,
		VerificationTruncateChars: 2000,
		CompressionBufferRatio:    DefaultCompressionBufferRatio,
		SoftTriggerRatio:          DefaultSoftTriggerRatio,
		HardTriggerRatio:          DefaultHardTriggerRatio,
	}
}
